### ISSUE TITLE
Dont start any containers at OS startup

### ISSUE THREAD

**Issue by tbfisher** [lando/lando#725] opened 2018-02-26 19:03 UTC
Bug Report
==========

mac os 10.13.3, lando v3.0.0-beta.35

after OS restart, lando traefik container is running

**Comment by pirog** [comment] 2018-03-15 18:05
@tbfisher going to close this as a dupe of https://github.com/lando/lando/issues/761 which has a bit better description of the issue

**Closed by pirog** 2018-03-15 18:05 UTC
