### ISSUE TITLE
Add support for arch

### ISSUE THREAD

**Issue by inverse** [lando/lando#814] opened 2018-03-24 20:19 UTC
# Feature Request
How difficult would it be to add support for arch? `fpm` should be able to make pacman packages right?

**Comment by dustinleblanc** [comment] 2018-03-25 12:54
@inverse part of the issue is testing/building releases on arch. The more platforms we support, the more we have to test.

I'd imagine to make the commitment to support arch based distros, we'd need to have a solid group of users wanting this.

**Comment by anavarre** [comment] 2018-03-26 17:24
Just registering I'd like this as well.

**Comment by pirog** [comment] 2018-03-26 17:50
@inverse @anavarre you can currently install on arch by just installing from source. it might be no big deal to roll pacman packages, and it might "just work", but the bigger issue is just providing support around that as @dustinleblanc mentions

**Comment by inverse** [comment] 2018-03-26 18:20
@dustinleblanc thanks for getting back to me. It definitely would be another dimension on the testing front.

@pirog That could be one thing we could do. I'm currently doing that but was thinking of a more user friendly way. Recently switched to arch and wanting to learn the packaging system in more detail. Creating a `lando-git` package on AUR to be a good way to dig into this topic.

**Comment by pirog** [comment] 2018-03-28 05:53
Summoning @uberhacker

**Comment by uberhacker** [comment] 2018-03-28 14:37
Lucky me.  See #827.

**Comment by uberhacker** [comment] 2018-03-28 16:20
Hey @inverse @anavarre @dustinleblanc @pirog: Please test out PR #827 when you get a chance.  Make sure you follow the steps outlined [here](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user) and that you are testing on the master branch.  Earlier branches don't have `systemctl` support needed by Arch/Manjaro.  Also note if you are using Manjaro, you will need the AUR repository enabled for some of the dependencies needed by Lando.  Let me know how it goes!

**Comment by pirog** [comment] 2018-03-28 16:23
@uberhacker that info would be great to add to the install docs as part of the PR!!! ;)

**Comment by pirog** [comment] 2018-04-01 17:38
Going to close this out but there is EXPERIMENTAL/DEV support for this over here now
https://docs.devwithlando.io/installation/installing.html#development-builds

If the packages seem to be good then we can add them to our official releases.

**Closed by pirog** 2018-04-01 17:38 UTC
Labels: feature

**Comment by inverse** [comment] 2018-04-01 18:43
Thanks for pushing this out. I'll be running with this and will let you know!

**Comment by pirog** [comment] 2018-04-01 19:41
@inverse interesting. im guessing this is because its a dev release which is why you get that `-8` at the end of the version string. What's weird is the "dev" version should actually append something more like `-8-g8827`. This doesnt seem to be an issue with deb/rpm but maybe arch has stricter guidelines around version validation?

**Comment by inverse** [comment] 2018-04-01 21:01
@pirog From their [documentation][0] i found this

> Package versions should be the same as the version released by the author. Versions can include letters if need be (eg, nmap's version is 2.54BETA32). Version tags may not include hyphens! Letters, numbers, and periods only.

However I am not entirely sure 


[0]: https://wiki.archlinux.org/index.php/Arch_packaging_standards

**Comment by pirog** [comment] 2018-04-02 00:06
@inverse yup. i just tried to install this on a fresh manjaro and got more or less the same thing. there are a few things i think we can change to make this easier nad more reliable

1. I dont think we need the `cgroup` dep anymore, which should allow us to not worry about AUR
2. I think we need to make sure pacman builds do not include the hyphens in the version string, it might be easier to switch the hyphens we use in fpm to `.` since i think that is supported on deb/rpm as well.

**Comment by pirog** [comment] 2018-04-02 07:04
@inverse alright, i think the latest posted dev release for pacman should do the trick, at least i was able to get rolling with it on manjaro

**Comment by inverse** [comment] 2018-04-02 10:28
@pirog  I can confirm the fix worked! thanks for rolling that out quickly.

**Comment by anavarre** [comment] 2018-04-17 09:12
I'm late to the party but also want to report back success into trying to install the `.pacman` build. Thanks!

**Comment by ElijahLynn** [comment] 2018-11-21 18:52
Crosslinking https://github.com/lando/lando/pull/832

**Comment by hkirsman** [comment] 2019-01-26 07:48
If anybody as noob as me in Arch would ever visit here then download .pacman file and execute

    sudo pacman -U lando-v3.0.0-rc.1.pacman

I tried also to lando-git version from AUR but didn't get that working. Still, I have installed the docker-git version.

**Comment by inverse** [comment] 2019-01-26 09:06
> If anybody as noob as me in Arch would ever visit here then download .pacman file and execute
> 
> ```
> sudo pacman -U lando-v3.0.0-rc.1.pacman
> ```
> I tried also to lando-git version from AUR but didn't get that working. Still, I have installed the docker-git version.

What's not working? any errors?

**Comment by ElijahLynn** [comment] 2019-01-28 18:59
I suggest that the path for Arch support would be not actually creating a pacman build but in documenting the installation of the `lando-git` AUR package here https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=lando-git. (In Arch, you can maintain a package in an AUR build file and just issue build commands for a git repo, it truly is amazing, kind like `composer` can pull in git packages).

And then, we support the `lando-git`AUR build script only. 

Now, @hkirsman says they tried that and it didn't work. However, I just tried it with `yay -S lando-git` and it was installed to /usr/bin/lando and `lando version` shows `v3.0.0-rc.1`.

**Comment by ElijahLynn** [comment] 2019-01-28 19:05
FYI: @dmp1ce Actually maintains the lando-git AUR PKGBUILD file. He has an open issue here https://github.com/lando/lando/issues/1309.

**Comment by ElijahLynn** [comment] 2019-01-28 19:15
If `lando-git` AUR is not working it is suggested to contact maintainer, which is David Parrish <daveparrish@tutanota.com> (@dmp1ce)

https://wiki.archlinux.org/index.php/Arch_User_Repository#Foo_in_the_AUR_is_outdated;_what_should_I_do?

**Comment by inverse** [comment] 2019-01-28 19:23
@ElijahLynn are you suggesting dropping the pacman builds and instead building from source each time?  What's the benefits aside from easier maintenance from an upgrade perspective?

**Comment by ElijahLynn** [comment] 2019-01-28 23:59
Just easier maintenance, and also there is no such thing as a pacman file, it was invented here. That was really confusing to me initially. Having a user install anything manually on Arch is not really a thing, yay throws warnings that Lando wasn't installed with a package manager. It just makes sense to guide Arch users to the "Arch way". Or somehow get the pacman binary shipped as an actual binary to the Arch Community repo. 

I am new to Arch, so apologies if this doesn't make perfect sense.

**Comment by dmp1ce** [comment] 2019-01-29 01:03
I'm happy to help maintain the Arch Linux PKGBUILD on the AUR but I am not currently using Lando. Let me know if the PKGBUILD is broken in any way. Keep in mind that `lando-git` builds from the latest code from `master` so it could be unstable.

**Comment by hkirsman** [comment] 2019-01-30 11:19
@ElijahLynn lando-git installed but didn't actually work when starting with 'lando start'.

**Comment by hkirsman** [comment] 2019-01-30 11:21
@dmp1ce I would rather use stable version than get always the bleeding edge from git. Also it's important because others in my team are using the stable version that can be downloaded from the installation page.

**Comment by dmp1ce** [comment] 2019-01-30 14:55
@hkirsman How do you know `lando start` didn't work? Did any errors display? I ran `lando init` and `lando start` which seems to work for me.

I'll create another AUR package which will be called `lando` which will build from the stable release.

**Comment by hkirsman** [comment] 2019-01-31 07:36
Yeah, there where errors but can't say exactly what. Something about sh and wrong parameter. I can try both today.

**Comment by inverse** [comment] 2019-01-31 20:45
@dmp1ce thanks for https://aur.archlinux.org/packages/lando/ - just installed and works nicely :+1:

**Comment by hkirsman** [comment] 2019-05-27 07:17
@dmp1ce Hey! Could you update https://aur.archlinux.org/packages/lando-git/ ?  :)

**Comment by dmp1ce** [comment] 2019-05-27 13:41
Updated. Arch users can just reinstall the package to get the latest version since it is a `-git` package. The version will change according to the tag in git.

**Comment by hkirsman** [comment] 2019-05-28 05:55
It's interesting that the last version there was 3.0.0.rc.13.r12.gc0e229e8 but I currently have 3.0.0.rc.14.r2.g70a094b6-1.

**Comment by hkirsman** [comment] 2019-05-28 05:56
And tx @dmp1ce
