### ISSUE TITLE
Pantheon recipe: varnish cache age

### ISSUE THREAD

**Issue by rbomhof** [lando/lando#1536] opened 2019-03-15 14:53 UTC
Lando Version: v3.0.0-rc.1
OS: High Sierra 10.13.3

.lando.yml:

name: test-base
recipe: pantheon
config:
  framework: drupal8
  site: test-base
  id: 39804e8f-253e-474e-82cf-725b36fddde0
  webroot: web
  database:
       portforward: 3308
tooling:
  drush:
    cmd: /app/vendor/bin/drush
  gulp:
    service: appserver
  drupal:
    service: appserver
    cmd:
      - "/app/vendor/bin/drupal"
      - "--root=/app/web"

We are trying to ensure Varnish is working properly using the pantheon recipe. We do see the right headers when we run curl against pantheon directly (it is aging properly), but when we run them against our Lando site everything looks ok for the age - it never increases from 0. We went ahead and configured Drupal for 15 minutes (which we see represented in the max-age) and we don't have any local settings files preventing it from caching.

curl -kIL http://testbase.lndo.site/page/asdf

HTTP/2 200 
accept-ranges: bytes
age: 0
cache-control: max-age=900, public
content-language: en
content-type: text/html; charset=UTF-8
date: Fri, 15 Mar 2019 13:08:26 GMT
etag: "1552655395"
expires: Sun, 19 Nov 1978 05:00:00 GMT
last-modified: Fri, 15 Mar 2019 13:09:55 GMT
link: <http://testbase.lndo.site/page/asdf>; rel="alternate"; hreflang="en"
link: </page/asdf>; rel="canonical"
link: </node/1>; rel="shortlink"
link: </page/asdf>; rel="revision"
server: nginx
vary: Accept-Encoding, Cookie, Cookie
via: 1.1 varnish-v4
x-content-type-options: nosniff
x-drupal-cache: HIT
x-drupal-dynamic-cache: HIT
x-frame-options: SAMEORIGIN
x-generator: Drupal 8 (https://www.drupal.org)
x-host: testbase.lndo.site
x-pantheon-environment: lando
x-pantheon-phpreq: yes
x-pantheon-site: TBD
x-ua-compatible: IE=edge
x-url: /page/asdf
x-varnish: 131203

We aren't experts in this area by any means, so any advice on how to troubleshoot this would be appreciated.

**Comment by pirog** [comment] 2019-03-18 14:17
@rbomhof this is the expected behavior. We don't actually cache any pages since that would make development fairly tedious. You can, however, override the pantheon vcl file we ship if you want different functionality.

The primary reason we include varnish is so you can develop code and test it against the "cookie stripping" that pantheon does since this often causes a lot of "but it works on my local" situations
https://pantheon.io/docs/cookies/

**Comment by pirog** [comment] 2019-03-18 18:04
@rbomhof im going to close this out since it "works as expected" however, it might be worth opening a feature request to set some sort of cache header to know if varnish "cached" a page or not. by this i mean satisfied the conditions needed to cache a page since we dont actually want ot cache pages.

**Closed by pirog** 2019-03-18 18:04 UTC
Labels: bug
