### ISSUE TITLE
D7 Simpletests don't run on Lando

### ISSUE THREAD

**Issue by cboyden** [lando/lando#973] opened 2018-05-17 23:49 UTC
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.45 on Mac OSX 10.13.4

**Tell us about your `.lando.yml`**

```yml
name: vanilla
recipe: drupal7
config:
  webroot: .
  php: '5.6'
  via: nginx
```
Also, here's the last bit of settings.php with base_url set to the one of the nginx urls reported by `lando info`:

```php
$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => 'drupal7',
      'username' => 'drupal7',
      'password' => 'drupal7',
      'host' => 'database',
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);

$base_url = 'http://vanilla.localhost:8000';  // NO trailing slash!
```
I am using the offline development strategy outlined at https://docs.devwithlando.io/tutorials/offline-dev.html because I need to be using *.localhost domains in order to use my organization's single sign-on setup. It's been working great so far.

**Tell us generally about your bug**

This is a plain-vanilla local Drupal 7 site on which I'm trying to run some simpletests for contrib module development. I am unable to run even the basic core tests such as node creation. Any test that has to visit a page results in an error such as `GET http://vanilla.localhost:8000/user returned 0 (0 bytes).`

I tried a few things such as:
* using the local URLs in the form http://localhost:32774
* using apache instead of nginx
* using PHP 7.1
* running tests from the command line using run-tests.sh
* `lando ssh appserver` and then running tests from the command line

To reproduce:
1. Spin up a Lando app using the above .lando.yml
2. Install Drupal using all the defaults
3. Enable the simpletest module
4. Log in as user 1 and navigate to admin/config/development/testing
5. Expand the Node group and check the box for Node creation
6. Click the Run tests button

The first bit of the test results are outlined below:

Message | Group | Filename | Line | Function | Status
------- | ----- | -------- | ---- | -------- | ------
Enabled modules: node_test_exception | Other | node.test | 605 | NodeCreationTestCase->setUp() | Pass
Created role of name: omaPJH1p, id: 4 | Role | node.test | 607 | NodeCreationTestCase->setUp() | Pass
Created permissions: create page content, edit own page content | Role | node.test | 607 | NodeCreationTestCase->setUp() | Pass
User created with name wpVRur5B and pass 9arycvy2WE | User login | node.test | 607 | NodeCreationTestCase->setUp() | Pass
GET http://vanilla.localhost:8000/user returned 0 (0 bytes). | Browser | node.test | 608 | NodeCreationTestCase->setUp() | Fail
Verbose message | Debug | node.test | 608 | NodeCreationTestCase->setUp() | Debug
Valid HTML found on "http://vanilla.localhost:8000/user" | Browser | node.test | 608 | NodeCreationTestCase->setUp() | Pass
simplexml_import_dom(): Invalid Nodetype to import | Warning | drupal_web_test_case.php | 1955 | DrupalWebTestCase->parse() | Exception
Parsed page successfully. | Browser | node.test | 608 | NodeCreationTestCase->setUp() | Fail

Is there some other configuration I need to add in order to get these working? When I run the tests on a different, non-Docker stack, they pass as expected.

**Comment by cboyden** [comment] 2018-05-18 00:03
In case it's helpful, here's a full-page screenshot of some test results, from one of the runs when I was testing with a different local URL.
![lando-d7-simpletest-failures](https://user-images.githubusercontent.com/725267/40209473-3718a140-59f4-11e8-862c-55fb6dccab3a.png)

**Comment by dsnopek** [comment] 2018-05-18 05:54
I also experienced issues with running a contrib module's Simpletest in Drupal 7 while using Lando and had assumed it was something up with that contrib module's tests. So, when I saw this, I thought maybe it was actually a Lando issue with Simpletest! But I just tried the steps to reproduce here (with a slightly simpler .lando.yml and under Ubuntu 16.04) and the "Node creation" test actually passed for me.

I'm NOT using the offline development configuration - the site ends up at `http://d759.lndo.site` in my configuration, and I think that might be why it's passing for me and failing for you (more below).

Here's the .lando.yml I tried:

```
name: d-759
recipe: drupal7
config:
  webroot: .
  php: '5.6'
```

I think that Simpletest causes Drupal to do some HTTP requests to itself, and I suspect the problem is that the name/port you're using to access Drupal won't work when the appserver tries to connect to itself from inside the appserver: Inside the appserver, the port will always just be 80 and 443, and I'm not sure if `vanilla.localhost' will resolve to 127.0.0.1 without adding something to `/etc/hosts` inside of appserver.

That's just a guess, though, I haven't dug any deeper.

**Comment by dustinleblanc** [comment] 2018-05-18 13:02
@dsnopek sounds like he is on to something. FWIW, I always recommend using service names whenever running automated tests inside of a docker container's network. The 'browser' here is PHP, which is in the appserver, the site is served via the 'nginx' or 'appserver' host, so when configuring the tests, the host it should be going after is `http://{service_name}`. Relying on the proxy or any other hostname/dns setup of the host machine is brittle and not portable.

I am going to close this for now *assuming* the issue is with the hostname mapping. @cboyden if that turns out to not be the case, let us know.

**Closed by dustinleblanc** 2018-05-18 13:02 UTC

**Comment by dsnopek** [comment] 2018-05-18 13:08
> FWIW, I always recommend using service names whenever running automated tests inside of a docker container's network.

This is sort of special situation because the automated tests are part of Drupal 7 core. :-) I don't know what configuration variables it gives to work around this problem.

**Comment by dustinleblanc** [comment] 2018-05-18 13:12
@dsnopek I was just actually trying to run the tests via `scripts/run-tests.sh` and could not get it to work via either Lando, or my host mac, the thing just exists silently if I try to ask it to run anything. That command does state that it has options for --url and --dburl though. I'd also imagine that setting the base_url in settings.php would work if running via the ui, though that might break other things.

**Comment by cboyden** [comment] 2018-05-18 16:21
@dustinleblanc are you suggesting that I set base_url to http://nginx in settings.php? Would that be for running the tests in the UI, or from the command line? If from the UI, won't that base_url break the site?

**Comment by cboyden** [comment] 2018-05-18 20:27
I've got the simpletests running. In order to do it, I had to 
* skip nginx and go back to Apache
* make sure Lando got port 80 by stopping Mac's built-in httpd and then `lando poweroff` and `lando rebuild` on the app
* add the domain to /etc/hosts on the container

Here's the updated .lando.yml that works:
```yml
name: vanilla
recipe: drupal7
config:
  webroot: .
  php: '5.6'
services:
  appserver:
    run_as_root: 'printf "%s\t%s\n" "127.0.0.1" "$LANDO_APP_NAME.$LANDO_DOMAIN" >> /etc/hosts'
```
This should be generic enough to cover a lot of offline-dev cases. But is there a way to handle things if Lando doesn't get port 80 on the host, or if nginx is in use?

**Comment by dustinleblanc** [comment] 2018-05-21 12:34
@cboyden I think you're just looking at a case of simpletest needing to understand it's path to the site. The commandline version allows you to specify the url of the site, I never run the tests via the UI, so I don't  know what you might need to edit there, but this is a docker issue, not a lando issue. PHP can only know about the network as it appears to docker.

**Comment by cboyden** [comment] 2018-05-21 16:36
Is there a way to set it up so that if you're using nginx, it runs on the same container that apache would have run on?

**Comment by dustinleblanc** [comment] 2018-05-22 12:15
@cboyden Nginx runs in a separate container, where apache/php run together since PHP isn't running in fpm mode (I believe anyway). When using Nginx, its easier to build the services separately, which allows for more flexibility in version matching with fewer maintained images. This means that php will see apache at `http://localhost` while it will see nginx at `http://nginx`.

**Comment by markisatacomputer** [comment] 2019-03-07 00:02
In case it's useful this worked for me (lando v3.0.0-rc.12):

```
lando php scripts/run-tests.sh --verbose --php /usr/local/bin/php --url "http://localhost" "Test Suite Name"
```
