### ISSUE TITLE
Broken HTTPS after last update

### ISSUE THREAD

**Issue by vasikgreif** [lando/lando#1703] opened 2019-07-16 23:26 UTC
After updating to Lando RC17, my https URL's stopped working. Updating to RC18 did not help. I didn't change any configuration.

My config is:
```
name: hyponamiru
recipe: wordpress
excludes:
  - web/wp-content/plugins
  - web/wp-content/uploads
  - web/wp-admin
  - web/wp-includes
  - web/wp-content/themes/astra-child/node_modules
  - web/wp-content/themes/astra-child/.git
  - web/wp-content/themes/astra-child/vendor
config:
  php: 7.2
  via: nginx
  database: mariadb
  webroot: web
  xdebug: true
proxy:
  mailhog:
    - mail.hyponamiru.lndo.site
services:
  mailhog:
      type: mailhog
      hogfrom:
        - appserver
      portforward: true

```

And the result (the https URL's are red):

```
BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME                  hyponamiru                                    
 LOCATION              /Users/vasik/Dev/hyponamiru                   
 SERVICES              appserver_nginx, appserver, database, mailhog 
 APPSERVER_NGINX URLS  https://localhost:32789                       
                       http://localhost:32790                        
                       http://hyponamiru.lndo.site:8000              
                       https://hyponamiru.lndo.site                  
 MAILHOG URLS          http://localhost:32788                        
                       http://mail.hyponamiru.lndo.site:8000         
                       https://mail.hyponamiru.lndo.site         
```

The http URLs with port work fine. I did try rebuilding the app multiple times. Any fix for that?

**Comment by vasikgreif** [comment] 2019-07-31 10:25
Update here - I also tried to uninstall Lando and Docker completely and reinstalling RC18, no luck, the URL's are still red and don't work. 

Any idea how to debug this? The addresses with ports change quite often when rebuilding the app, which means I have to replace the urls in db and wp-config almost after every rebuild...

**Comment by fabianskibr** [comment] 2019-07-31 13:47
same problem here

**Comment by vasikgreif** [comment] 2019-08-05 21:37
Update to RC19 did not help, I went through the same procedure of uninstalling / reinstalling everything, no luck. Please, any chance to debug this somehow?

Thanks

**Comment by vasikgreif** [comment] 2019-09-05 04:46
Same issue after update to RC20... 🤔 I'll be happy to debug this, just don't know how...

**Comment by vasikgreif** [comment] 2019-09-21 09:51
Here's the app log in case this will help. I can see there are some errors accessing the keys, not sure if that has something to do with the issue:

```
appserver_1        | This is a debian container
appserver_1        | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_1        | Lando ENVVARS set at
appserver_1        | LANDO_WEBROOT_USER: www-data
appserver_1        | LANDO_WEBROOT_GROUP: www-data
appserver_1        | LANDO_WEBROOT_UID: 501
appserver_1        | LANDO_WEBROOT_GID: 20
appserver_1        | LANDO_HOST_UID: 501
appserver_1        | LANDO_HOST_GID: 20
appserver_1        | Making sure correct user:group (www-data:www-data) exists...
appserver_1        | Remapping ownership to handle docker volume sharing...
appserver_1        | LANDO_HOST_UID: 501
appserver_1        | LANDO_HOST_GID: 20
appserver_1        | Resetting www-data:www-data from 501:20 to 501:20
appserver_1        | www-data:www-data is now running as uid=501(www-data) gid=20(dialout) groups=20(dialout),33(www-data)!
appserver_1        | And here. we. go.
appserver_1        | Scanning /lando/keys for keys...
appserver_1        | Found keys
appserver_1        | Scanning /user/.ssh for keys...
appserver_1        | Found keys /user/.ssh/known_hosts.old /user/.ssh/id_rsa /user/.ssh/key.pem /user/.ssh/ecobadge
appserver_1        | Ensuring permissions and ownership of /user/.ssh/known_hosts.old...
appserver_1        | chmod: cannot access '/user/.ssh/known_hosts.old.pub': No such file or directory
appserver_1        | Checking whether /user/.ssh/known_hosts.old is a private key...
appserver_1        | Ensuring permissions and ownership of /user/.ssh/id_rsa...
appserver_1        | Checking whether /user/.ssh/id_rsa is a private key...
appserver_1        | Checking whether /user/.ssh/id_rsa is formatted correctly...
appserver_1        | Ensuring permissions and ownership of /user/.ssh/key.pem...
appserver_1        | chmod: cannot access '/user/.ssh/key.pem.pub': No such file or directory
appserver_1        | Checking whether /user/.ssh/key.pem is a private key...
appserver_1        | Checking whether /user/.ssh/key.pem is formatted correctly...
appserver_1        | Ensuring permissions and ownership of /user/.ssh/ecobadge...
appserver_1        | Checking whether /user/.ssh/ecobadge is a private key...
appserver_1        | Checking whether /user/.ssh/ecobadge is formatted correctly...
appserver_1        | Scanning /var/www/.ssh for keys...
appserver_1        | Found keys
appserver_1        | Using the following keys: /user/.ssh/id_rsa /user/.ssh/key.pem /user/.ssh/ecobadge
appserver_1        | Running command docker-php-entrypoint php-fpm
appserver_1        | [21-Sep-2019 09:43:14] NOTICE: fpm is running, pid 101
appserver_1        | [21-Sep-2019 09:43:15] NOTICE: ready to handle connections
appserver_1        | 172.22.0.5 -  21/Sep/2019:09:43:23 +0000 "GET /index.php
```

**Comment by tormi** [comment] 2019-09-23 14:11
Try to define `10.2` as database version. Seems like duplicate of https://github.com/lando/lando/issues/1738.

**Comment by vasikgreif** [comment] 2019-09-23 14:48
@tormi Tried bumping up the mariadb version, did `lando destroy` and `lando start`, no luck. The https url is still in red.

**Comment by tormi** [comment] 2019-11-08 15:18
Could be related to https://github.com/lando/lando/issues/1542

**Comment by vasikgreif** [comment] 2019-12-08 20:09
Just an update to this - since I wasn't able to resolve this, I reinstalled my MacOS completely, installed fresh Lando and things work again normally..:)

**Closed** 2020-01-14 21:31 UTC
Labels: bug, wontfix
