### ISSUE TITLE
ERROR: for proxy Cannot start service proxy network XXX not found

### ISSUE THREAD

**Issue by aaronlsilber** [lando/lando#971] opened 2018-05-17 20:24 UTC
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

- Windows 10 Pro (10.0.16299 Build 16299)
- Lando v3.0.0-beta.45
- Docker version 18.03.1-ce, build 9ee9f40

**Tell us about your `.lando.yml`**

```yml
name: drupal7site-com
recipe: drupal7
config:
  webroot: .
  via: nginx

services:
  node:
    type: node:6.11
    run: 
      - "cd $LANDO_MOUNT && npm install"
      - "cd $LANDO_MOUNT && grunt"
    globals:
      grunt-cli: "latest"
      bower: "latest"
      ruby: "latest"
      sass: "latest"

tooling:
  npm:
    service: node
  node:
    service: node
  bower:
    service: node
  grunt:
    service: node
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```bash
lando start -vvvv
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... errorERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not found
ERROR: for proxy  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not foundERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error
ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not found

ERROR: for proxy  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not foundERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error
ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not found

ERROR: for proxy  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not foundERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error
ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not found

ERROR: for proxy  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not foundERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error
ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not found

ERROR: for proxy  Cannot start service proxy: network d2e7f9d853b379c515a1b14840d5f4d576069e8c06163c5069159c210e641984 not foundERROR: Encountered errors while bringing up the project.
warn: Something is wrong with the proxy! {}warn: Trying to take corrective action...
```

This continues until it stops.

**Tell us generally about your bug**

I updated Lando and received this error message when I tried to start my lando app.

Does this bug prevent you from using lando?
Yes

**Comment by aaronlsilber** [comment] 2018-05-17 20:25
Also, I tried `docker container rm landoproxyhyperion5000gandalfedition_proxy_1` from https://github.com/lando/lando/issues/632 to no avail.

**Comment by aaronlsilber** [comment] 2018-05-17 20:36
This is probably related as well. When I run `lando db-export` I receive;

``` bash
Creating network "mywebsite_default" with the default driver
Creating mywebsite_database_1 ... error
ERROR: for mywebsite_database_1  Cannot start service database: OCI runtime create
failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for database  Cannot start service database: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
Creating network "mywebsite_default" with the default driverStarting mywebsite_database_1 ... error

ERROR: for mywebsite_database_1  Cannot start service database: network 59d63fda271907466abfe349a8a30ec848cbeb3f1bf7dc0827e2b06e5896428c not found

ERROR: for database  Cannot start service database: network 59d63fda271907466abfe349a8a30ec848cbeb3f1bf7dc0827e2b06e5896428c not found
ERROR: Encountered errors while bringing up the project.
Creating network "mywebsite_default" with the default driverStarting mywebsite_database_1 ... error
```

Just repeats over and over.

**Comment by jkswoods** [comment] 2018-05-18 11:29
Also experiencing a very similar issue after updating Lando to the latest v3.0.0-beta.45.

- macOS Sierra 10.12
- Docker 18.03.1-ce-mac65 (24312

Output from ``lando start``:
```
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (3668fc04b07e4404b281afe32c2faa8169dfa45ff158361c8c36f35f9af1709a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (3668fc04b07e4404b281afe32c2faa8169dfa45ff158361c8c36f35f9af1709a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
warn: Something is wrong with the proxy! {}
warn: Trying to take corrective action...
```

**Comment by dustinleblanc** [comment] 2018-05-18 12:14
@aaronlsilber @jkswoods What versions did y'all upgrade from? were they pre-beta41? If so, nuking ~/.lando and doing the uninstall/reinstall dance might be needed.

**Comment by jkswoods** [comment] 2018-05-18 12:18
@dustinleblanc I upgraded from beta41 - will try your suggestion and report back with results.

**Comment by jkswoods** [comment] 2018-05-18 12:37
Same issue unfortunately. Removed ~/.lando, uninstalled beta45 then installed beta45.

Output from `lando start`:
```
Creating network "landocasetupkenobi38ahsoka02c2e96fd69e29236fff31783632e677b2baa43a_default" with the default driver
Creating landocasetupkenobi38ahsoka02c2e96fd69e29236fff31783632e677b2baa43a_ca_1 ... done
Looks like you do not have a Lando CA yet! Let's set one up!
Trying to setup root CA with...
LANDO_CA_CERT: lando.pem
LANDO_CA_KEY: lando.key
CA_CERT: /certs/lando.pem
CA_KEY: /certs/lando.key
/certs/lando.pem not found... generating one
Generating RSA private key, 2048 bit long modulus
...............................................................................................+++
...........+++
e is 65537 (0x10001)
/certs/lando.pem not found... generating one
CA generated at /certs/lando.pem
Killing landocasetupkenobi38ahsoka02c2e96fd69e29236fff31783632e677b2baa43a_ca_1 ... done
Removing landocasetupkenobi38ahsoka02c2e96fd69e29236fff31783632e677b2baa43a_ca_1 ... done
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (3668fc04b07e4404b281afe32c2faa8169dfa45ff158361c8c36f35f9af1709a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (3668fc04b07e4404b281afe32c2faa8169dfa45ff158361c8c36f35f9af1709a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found

ERROR: for proxy  Cannot start service proxy: network 38f1f13ef052f5dffe1844a8ba45d925a971f4e166091e5e5d30cd386ed68535 not found
ERROR: Encountered errors while bringing up the project.
warn: Something is wrong with the proxy! {}
warn: Trying to take corrective action...
```

**Comment by dustinleblanc** [comment] 2018-05-18 13:03
`driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (3668fc04b07e4404b281afe32c2faa8169dfa45ff158361c8c36f35f9af1709a): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)`

Looks like something is bound on port 80, might want to check and see what that is.

**Comment by aaronlsilber** [comment] 2018-05-18 13:05
@dustinleblanc I believe I was upgrading from v3.0.0-beta.43 or 44.

Updates have usually fixed something for me, so I try to keep up-to-date.

**Comment by jkswoods** [comment] 2018-05-18 13:10
@dustinleblanc That did it! httpd was running on port 80 - stopping it with `sudo apachectl stop` and then removing the old proxy container with
`docker rm landoproxyhyperion5000gandalfedition_proxy_1` did the trick and now everything is working. Thanks!

**Comment by dustinleblanc** [comment] 2018-05-18 13:13
Sweet! @aaronlsilber, see if you have any nasties hogging your ports too!

**Comment by aaronlsilber** [comment] 2018-05-18 13:48
@dustinleblanc no dice. I've tried everything suggested.

**Comment by aaronlsilber** [comment] 2018-05-18 15:29
@dustinleblanc I'm confused as to why this was closed. @jkswoods has/had a different issue.

**Comment by dustinleblanc** [comment] 2018-05-21 12:51
My mistake! Didn't look at who filed the original issue. You might get better output @aaronlsilber if you go into verbose mode using `lando start -- -vvv`. WIthout the ` -- ` seperator, those verbose flags won't get passed to Lando. 

I see you are on Windows 10, I wonder if this is related to #878 🤔

**Comment by dustinleblanc** [comment] 2018-05-22 12:29
@aaronlsilber That is encouraging and puzzling simultaneously 😆 

So at this point, we know one machine is cursed, but don't know why. Have you tried the nukefromorbit and reinstall approach on the occursed machine?

**Comment by aaronlsilber** [comment] 2018-05-22 13:01
@dustinleblanc I was saving DEFCON 1 as a last resort (wanted to keep my data), but it seems that's the only card left in my arsenal. Do you know of a way to pull the database from a container when its "network is not found"?

**Comment by dustinleblanc** [comment] 2018-05-23 12:20
@aaronlsilber hmmm, maybe via vanilla docker? `docker exec CONTAINERID /usr/bin/mysqldump -u someuser --password the password DATABASE_NAME > backup.sql`

I adapted this from https://gist.github.com/spalladino/6d981f7b33f6e0afe6bb

**Comment by pirog** [comment] 2018-05-23 15:16
@aaronlsilber havent been able to reproduce this but @dustinleblanc has ran into it and was able to workaround it with `lando rebuild`. Definitely keen to figure out the problem here :/

**Comment by aaronlsilber** [comment] 2018-05-23 20:43
Lando can't start any kind of recipe at this point. If I initialize a LEMP stack and try to start it I get;

```bash
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"Removing landoproxyhyperion5000gandalfedition_proxy_1
Recreating 9bf989cf9971_landoproxyhyperion5000gandalfedition_proxy_1 ... error
ERROR: for 9bf989cf9971_landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/lando-entrypoint.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"Removing landoproxyhyperion5000gandalfedition_proxy_1Recreating 9bf989cf9971_landoproxyhyperion5000gandalfedition_proxy_1 ... error
```
(times a billion)

I'm not much of a devops guy, so Docker isn't my modus operandi. There's something about that `permission denied: unknown` statement that's awfully gross. 

I _should have_ known better than to update without exporting the DB first. Good thing I exported most of my features beforehand. I'll nuke this setup this weekend and see if I can't jump-start the whole shebang.

**Comment by osopolar** [comment] 2018-05-23 21:06
FWIW: I updated from v3.0.0-beta.39 to v3.0.0-beta.45 on macOS (deleting `~/.lando` and running `brew cask reinstall lando`, without explicitly uninstalling docker as pointed out in the [first step of release v3.0.0-beta.41 ](https://github.com/lando/lando/releases/tag/v3.0.0-beta.41)) and experienced similar problems:

```bash
lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "xxxxxxxxxxxxx_default" with the default driver
Starting xxxxxxxxxxxxx_database_1  ... error
Starting xxxxxxxxxxxxx_appserver_1 ...

Starting xxxxxxxxxxxxx_appserver_1 ... error

ERROR: for xxxxxxxxxxxxx_appserver_1  Cannot start service appserver: network d9b8e48e0a6ec1c8f3fad0b0707931be13b860cda08849b231b80710129566be not found

ERROR: for database  Cannot start service database: network d9b8e48e0a6ec1c8f3fad0b0707931be13b860cda08849b231b80710129566be not found

ERROR: for appserver  Cannot start service appserver: network d9b8e48e0a6ec1c8f3fad0b0707931be13b860cda08849b231b80710129566be not found
ERROR: Encountered errors while bringing up the project.
```

It seems that `lando rebuild` worked for me too.

**Comment by aaronlsilber** [comment] 2018-05-24 13:58
Okay. So I nuked Docker and Lando installs (uninstalled through Windows Add/Remove Program). Ran `lando start` with a Drupal7 recipe yml file.

Ran into issue #878 but it seemed to work through the issue on its own.

**Comment by dustinleblanc** [comment] 2018-05-25 12:57
@aaronlsilber @osopolar I think we've finally narrowed down the cause of this, it's related to network pruning and docker-compose getting angry about us deleting it's networks. See #990 
The typical fix for this seems to be `lando rebuild` for now, so if you end up in [the bad place](https://www.nbc.com/the-good-place) again, you probably don't need Elenor and Chidi, just a `lando rebuild` 😆 

Going to close this in favor of #990

**Closed by dustinleblanc** 2018-05-25 12:57 UTC

**Comment by ElijahLynn** [comment] 2019-01-04 01:14
Confirmed a `lando rebuild` fixed this error for me. In my case I was getting this same error after I manually ran a `docker-compose network rm` on all the networks, to start fresh with something else I was doing with compose.

**Comment by kevinquillen** [comment] 2019-01-11 16:20
I just ran into this as well and can confirm that `docker network prune` caused it for me. I needed to do this command because my bip/fixed-cidr settings were not being respected, and my application couldn't talk to an internal web service here on Drupal 7.

I got the same error and let it run; after 5 failed attempts it gave up and recreated the proxy container, now everything is cool.

**Comment by aaronlsilber** [comment] 2019-05-08 15:41
This issue is super old but I just experienced it again running Lando 3.0.0-rc.14 and think I discovered my issue — and likely the issue some other Windows users are having.

My company requires password changes every 90 days and I just changed mine a day ago. Unbeknownst to me, Docker stores the credentials for accessing shared drives. I went into my Docker settings, clicked 'Reset credentials', reselected the drives I want shared, and all my issues went away.

Hopefully this helps someone else.

**Comment by milkovsky** [comment] 2019-06-14 12:44
For Mac users: try stoing the httpd service.

**Comment by Niyabi** [comment] 2019-08-30 07:22
Got the same error for Lando v3.0.0-rc.19. Updating lando to Lando v3.0.0-rc.20 solved the issue.

**Comment by eleftrik** [comment] 2019-09-03 13:08
Same problem here with with Lando v3.0.0-rc.20 on Windows 10 Pro build 18362.
Apparently, this error occurs randomly.
I tried `lando rebuild`, Docker credentials reset and Docker restart, but it didn't work.

**Comment by kenneth-bolivar-castro** [comment] 2019-10-08 17:11
@kevinquillen thx 4 your comment here https://github.com/lando/lando/issues/971#issuecomment-453571527. 

To summary, I was facing the following error:
`ERROR: 2 matches found based on name: network landoproxyhyperion5000gandalfedition_edge is ambiguous`

After I ran `docker network prune` then I shows me there were two containers/networks with same name, reason why it said it was ambiguous.

What on earth did I do to have two networks? - well, on fresh installation I tried to start two project at once, then they created each network instance, since at time I executed none exists.
Then I ended up myself struggling with this such exception.

Anyway it works now. yay! 🎉

**Comment by edlington** [comment] 2019-11-30 23:29
On Ubuntu 16.04 after running the docker network prune command I attempted to run lando rebuild, lando restart. All resulted in  "ERROR: for 35646d6113fb_landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network xxxxxxxxxxxxxxxxxxxx not found."  The fix for me was running sudo apt-get remove lando. Seems I had two versions installed on my machine. The apt-get remove command reported  "Removing lando (3.0.0-rc.16)." After removal the lando version command reported "v3.0.0-rc.1" Running lando rebuild then worked. Thank you people above who noted that fix!!!

**Comment by Christopher-Hayes** [comment] 2021-08-19 19:43
`docker rm landoproxyhyperion5000gandalfedition_proxy_1`
followed by
`lando rebuild`
fixed the issue for me! Thanks 🚀

**Comment by Farnoosh63** [comment] 2021-09-10 16:25
I run to stop and remove all my running containers. `docker stop $(docker ps -q -a)` and `docker rm $(docker ps -q -a)` and it worked.
