### ISSUE TITLE
Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known.

### ISSUE THREAD

**Issue by JuanGongora** [lando/lando#925] opened 2018-04-29 15:03 UTC
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? 

Lando version v3.0.0-beta.40
Ubuntu 16.04 LTS
Drupal 7.59

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: git-version
recipe: drupal7
config:
  webroot: .
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Lando info:**

```yml
{
  "appserver": {
    "type": "php",
    "version": "7.0",
    "hostnames": [
      "appserver",
      "appserver.gitversion.internal"
    ],
    "via": "apache",
    "webroot": ".",
    "config": {
      "conf": "/home/juan/.lando/services/config/drupal7/php.ini"
    },
    "urls": [
      "https://localhost:32769",
      "http://localhost:32770",
      "http://gitversion.lndo.site:8000",
      "https://gitversion.lndo.site"
    ]
  },
  "database": {
    "type": "mysql",
    "version": "latest",
    "hostnames": [
      "database",
      "database.gitversion.internal"
    ],
    "creds": {
      "user": "drupal7",
      "password": "drupal7",
      "database": "drupal7"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "/home/juan/.lando/services/config/drupal7/mysql"
    },
    "urls": []
  }
}
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
$lando init
? What recipe do you want to use? drupal7
? Where is your webroot relative to the init destination? .
? What do you want to call this app? git-version
$lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

Link to gist of full output is [here](https://gist.github.com/JuanGongora/9f47f901e9d313962418a90abf3c3d0b).

```bash
$lando start

Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "gitversion_default" with the default driver
Creating volume "gitversion_data" with default driver
Creating volume "gitversion_appserver" with default driver
Creating volume "gitversion_data_database" with default driver
Creating gitversion_appserver_1 ... done
Creating gitversion_database_1  ... done
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
warn: Service database is unhealthy
warn: Run "lando logs -s database"
Changed current directory to /var/www/.composer
Using version ^0.3.7 for hirak/prestissimo
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing hirak/prestissimo (0.3.7): Downloading (100%)         
Writing lock file
Generating autoload files
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   2762      0 --:--:-- --:--:-- --:--:--  2773
100 4482k  100 4482k    0     0  1206k      0  0:00:03  0:00:03 --:--:-- 1461k
 PHP configuration      :                  
 PHP OS                 :  Linux           
 Drush script           :  /tmp/drush.phar 
 Drush version          :  8.1.16          
 Drush temp directory   :  /tmp            
 Drush configuration    :                  
 Drush alias files      :                  


BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            gitversion                              
 LOCATION        /home/juan/sites/Drupal/git_version_dev 
 SERVICES        appserver, database                     
 APPSERVER URLS  https://localhost:32774                 
                 http://localhost:32775                  
                 http://gitversion.lndo.site:8000        
                 https://gitversion.lndo.site 
```

```bash
$lando logs -s database

Attaching to gitversion_database_1
database_1   | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
database_1   | Lando ENVVARS set at
database_1   | LANDO_WEBROOT_USER: www-data
database_1   | LANDO_WEBROOT_GROUP: www-data
database_1   | LANDO_WEBROOT_UID: 33
database_1   | LANDO_WEBROOT_GID: 33
database_1   | Making sure correct user:group (www-data:www-data) exists...
database_1   | 33
database_1   | 33
database_1   | Remapping ownership to handle Linux docker volume sharing...
database_1   | LANDO_HOST_UID: 1000
database_1   | LANDO_HOST_GID: 1000
database_1   | Resetting www-data:www-data from 33:33 to 1000:1000
database_1   | www-data:www-data is now running as uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)!
database_1   | And here. we. go.
database_1   | Cert creation kicking off
database_1   | LANDO_CA_CERT: lando.pem
database_1   | LANDO_CA_KEY: lando.key
database_1   | CA_CERT_HOST: /lando/certs/lando.pem
database_1   | CA_DIR: /usr/share/ca-certificates
database_1   | CA_CERT_CONTAINER: /usr/share/ca-certificates/lando.pem
database_1   | Generating certs...
database_1   | Generating RSA private key, 2048 bit long modulus
database_1   | ....+++
database_1   | ............................................+++
database_1   | e is 65537 (0x010001)
database_1   | Signature ok
database_1   | subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin, CN = *.lndo.site
database_1   | Getting CA Private Key
database_1   | /usr/share/ca-certificates/lando.pem not found... copying /lando/certs/lando.pem over
database_1   | Installing update-ca-certificates...
database_1   | Scanning /user/.ssh for keys...
database_1   | Scanning /lando/keys for keys...
database_1   | Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
database_1   | Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
database_1   | Using the following keys: /lando/keys/pantheon.lando.id_rsa
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | Get:1 http://repo.mysql.com/apt/debian stretch InRelease [19.2 kB]
database_1   | Get:2 http://security.debian.org stretch/updates InRelease [94.3 kB]
database_1   | Ign:3 http://cdn-fastly.deb.debian.org/debian stretch InRelease
database_1   | Initializing database
database_1   | 2018-04-29T14:08:28.755213Z 0 [Warning] [MY-010139] [Server] Changed limits: max_open_files: 4096 (requested 5000)
database_1   | 2018-04-29T14:08:28.755459Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
database_1   | 2018-04-29T14:08:28.755489Z 0 [Warning] [MY-011068] [Server] The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead.
database_1   | 2018-04-29T14:08:28.793427Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.11) initializing of server in progress as process 174
database_1   | Get:4 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
database_1   | Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
database_1   |  100
database_1   | Get:7 http://security.debian.org stretch/updates/main amd64 Packages [469 kB]
database_1   | Get:8 http://repo.mysql.com/apt/debian stretch/mysql-8.0 amd64 Packages [7145 B]
database_1   |  100
database_1   | Get:9 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
database_1   | Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
database_1   | 2018-04-29T14:08:33.418485Z 0 [ERROR] [MY-011071] [Server] unknown variable 'query_cache_limit=1M'
database_1   | 2018-04-29T14:08:33.418501Z 0 [Warning] [MY-010952] [Server] The privilege system failed to initialize correctly. If you have upgraded your server, make sure you're executing mysql_upgrade to correct the issue.
database_1   | 2018-04-29T14:08:33.418507Z 0 [ERROR] [MY-010119] [Server] Aborting
database_1   | 2018-04-29T14:08:35.750163Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
database_1   | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
database_1   | Lando ENVVARS set at
database_1   | LANDO_WEBROOT_USER: www-data
database_1   | LANDO_WEBROOT_GROUP: www-data
database_1   | LANDO_WEBROOT_UID: 33
database_1   | LANDO_WEBROOT_GID: 33
database_1   | Making sure correct user:group (www-data:www-data) exists...
database_1   | 1000
database_1   | 1000
database_1   | Remapping ownership to handle Linux docker volume sharing...
database_1   | LANDO_HOST_UID: 1000
database_1   | LANDO_HOST_GID: 1000
database_1   | Resetting www-data:www-data from 33:33 to 1000:1000
database_1   | usermod: no changes
database_1   | www-data:www-data is now running as uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)!
database_1   | And here. we. go.
database_1   | Cert creation kicking off
database_1   | LANDO_CA_CERT: lando.pem
database_1   | LANDO_CA_KEY: lando.key
database_1   | CA_CERT_HOST: /lando/certs/lando.pem
database_1   | CA_DIR: /usr/share/ca-certificates
database_1   | CA_CERT_CONTAINER: /usr/share/ca-certificates/lando.pem
database_1   | /certs/cert.pem: OK
database_1   | Installing update-ca-certificates...
database_1   | Scanning /user/.ssh for keys...
database_1   | Scanning /lando/keys for keys...
database_1   | Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
database_1   | Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
database_1   | Using the following keys: /lando/keys/pantheon.lando.id_rsa
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | Get:1 http://repo.mysql.com/apt/debian stretch InRelease [19.2 kB]
database_1   | Get:4 http://repo.mysql.com/apt/debian stretch/mysql-8.0 amd64 Packages [7145 B]
database_1   | 2018-04-29T14:26:46.640239Z 0 [Warning] [MY-010139] [Server] Changed limits: max_open_files: 4096 (requested 5000)
database_1   | 2018-04-29T14:26:46.878860Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
database_1   | 2018-04-29T14:26:46.878927Z 0 [Warning] [MY-011068] [Server] The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead.
database_1   | 2018-04-29T14:26:46.879039Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 100
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | Get:3 http://security.debian.org stretch/updates InRelease [94.3 kB]
database_1   | Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
database_1   | Get:5 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
database_1   | mysqld: Table 'mysql.plugin' doesn't exist
database_1   | 2018-04-29T14:26:47.296182Z 0 [ERROR] [MY-010735] [Server] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
database_1   | 2018-04-29T14:26:47.412901Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
database_1   | 2018-04-29T14:26:47.421267Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
database_1   | 2018-04-29T14:26:47.429548Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database_1   | 2018-04-29T14:26:47.430062Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
database_1   | 2018-04-29T14:26:47.430264Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
database_1   | 2018-04-29T14:26:47.430284Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
database_1   | 2018-04-29T14:26:47.430466Z 0 [ERROR] [MY-011071] [Server] unknown variable 'query_cache_limit=1M'
database_1   | 2018-04-29T14:26:47.430478Z 0 [Warning] [MY-010952] [Server] The privilege system failed to initialize correctly. If you have upgraded your server, make sure you're executing mysql_upgrade to correct the issue.
database_1   | 2018-04-29T14:26:47.430618Z 0 [ERROR] [MY-010119] [Server] Aborting
database_1   | Get:7 http://security.debian.org stretch/updates/main amd64 Packages [469 kB]
database_1   | Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
database_1   | Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
database_1   | Get:9 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
database_1   | Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
database_1   | 2018-04-29T14:26:49.170162Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
database_1   | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
database_1   | Lando ENVVARS set at
database_1   | LANDO_WEBROOT_USER: www-data
database_1   | LANDO_WEBROOT_GROUP: www-data
database_1   | LANDO_WEBROOT_UID: 33
database_1   | LANDO_WEBROOT_GID: 33
database_1   | Making sure correct user:group (www-data:www-data) exists...
database_1   | 1000
database_1   | 1000
database_1   | Remapping ownership to handle Linux docker volume sharing...
database_1   | LANDO_HOST_UID: 1000
database_1   | LANDO_HOST_GID: 1000
database_1   | Resetting www-data:www-data from 33:33 to 1000:1000
database_1   | usermod: no changes
database_1   | www-data:www-data is now running as uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)!
database_1   | And here. we. go.
database_1   | Cert creation kicking off
database_1   | LANDO_CA_CERT: lando.pem
database_1   | LANDO_CA_KEY: lando.key
database_1   | CA_CERT_HOST: /lando/certs/lando.pem
database_1   | CA_DIR: /usr/share/ca-certificates
database_1   | CA_CERT_CONTAINER: /usr/share/ca-certificates/lando.pem
database_1   | /certs/cert.pem: OK
database_1   | Installing update-ca-certificates...
database_1   | Scanning /user/.ssh for keys...
database_1   | Scanning /lando/keys for keys...
database_1   | Checking whether /lando/keys/pantheon.lando.id_rsa is a private key...
database_1   | Ensuring permissions for /lando/keys/pantheon.lando.id_rsa...
database_1   | Using the following keys: /lando/keys/pantheon.lando.id_rsa
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | Get:1 http://repo.mysql.com/apt/debian stretch InRelease [19.2 kB]
database_1   | Get:2 http://repo.mysql.com/apt/debian stretch/mysql-8.0 amd64 Packages [7145 B]
database_1   | 2018-04-29T14:28:41.470765Z 0 [Warning] [MY-010139] [Server] Changed limits: max_open_files: 4096 (requested 5000)
database_1   | 2018-04-29T14:28:41.702719Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
database_1   | 2018-04-29T14:28:41.702757Z 0 [Warning] [MY-011068] [Server] The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead.
database_1   | 2018-04-29T14:28:41.702839Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 100
database_1   | Get:3 http://security.debian.org stretch/updates InRelease [94.3 kB]
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | mbind: Operation not permitted
database_1   | Ign:4 http://cdn-fastly.deb.debian.org/debian stretch InRelease
database_1   | Get:5 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
database_1   | Get:6 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]
database_1   | Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
database_1   | Get:8 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [12.1 kB]
database_1   | Get:9 http://security.debian.org stretch/updates/main amd64 Packages [469 kB]
database_1   | mysqld: Table 'mysql.plugin' doesn't exist
database_1   | 2018-04-29T14:28:42.122948Z 0 [ERROR] [MY-010735] [Server] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
database_1   | 2018-04-29T14:28:42.227316Z 0 [Warning] [MY-010015] [Repl] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
database_1   | 2018-04-29T14:28:42.235314Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
database_1   | Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [9530 kB]
database_1   | 2018-04-29T14:28:42.243700Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database_1   | 2018-04-29T14:28:42.244218Z 0 [Warning] [MY-010441] [Server] Failed to open optimizer cost constant tables
database_1   | 2018-04-29T14:28:42.244407Z 0 [ERROR] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-001146 - Table 'mysql.component' doesn't exist
database_1   | 2018-04-29T14:28:42.244425Z 0 [Warning] [MY-013129] [Server] A message intended for a client cannot be sent there as no client-session is attached. Therefore, we're sending the information to the error-log instead: MY-003543 - The mysql.component table is missing or has an incorrect definition.
database_1   | 2018-04-29T14:28:42.244562Z 0 [ERROR] [MY-011071] [Server] unknown variable 'query_cache_limit=1M'
database_1   | 2018-04-29T14:28:42.244573Z 0 [Warning] [MY-010952] [Server] The privilege system failed to initialize correctly. If you have upgraded your server, make sure you're executing mysql_upgrade to correct the issue.
database_1   | 2018-04-29T14:28:42.244684Z 0 [ERROR] [MY-010119] [Server] Aborting
database_1   | 2018-04-29T14:28:44.000091Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.11)  MySQL Community Server - GPL.
```

**Tell us generally about your bug**

I started up the generic Drupal 7 recipe of Lando on a vanilla Drupal site directory for the recommended version of 7 at drupal.org. I would receive a warning at lando start:

```
warn: Service database is unhealthy
warn: Run "lando logs -s database"
```

After I open the link to the newly started lando site, while setting up the Database configuration for Drupal 7, using the information from the command lando info I would get the following error:

```
Resolve all issues below to continue the installation. For help configuring your database server, see the installation handbook, or contact your hosting provider.

Failed to connect to your database server. The server reports the following message: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known.

    Is the database server running?
    Does the database exist, and have you entered the correct database name?
    Have you entered the correct username and password?
    Have you entered the correct database hostname?
```

I tried manually setting the database parameters in settings.php file, but that also did not work.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
1. Download Drupal 7 Recommended Release: https://www.drupal.org/project/drupal/releases/7.59 
2. Extract Drupal and go to its root directory
3. Open command line to that directory and lando init
4. select drupal 7 recipe, rest is at default options
5. lando start
6. input database settings from lando info into the drupal install walktrhough at 'Set up database' stage

```

**Tell us more**

Does this bug prevent you from using lando?

It does not allow me to use Drupal 7 with the lamp, and drupal 7 recipes.

**Comment by pirog** [comment] 2018-04-30 04:14
@JuanGongora duplicate of #908

**Closed by pirog** 2018-04-30 04:14 UTC
