### ISSUE TITLE
lando start fails for pantheon recipe

### ISSUE THREAD

**Issue by paul94010** [lando/lando#668] opened 2018-01-25 00:31 UTC
Consistent with my past experience, I seem to be able to make even the simplest install fail.   I hope the mistake is not too stupid.

Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.35 running on MacOS 10.13.1

**Tell us about your `.lando.yml`**

name: nativecommerce
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: nativecommerce
  id: f9978f7f-24e6-40f9-8c5e-77602c72c5c5

pantheon.yaml

api_version: 1
php_version: 7.0

**Tell us about the command you were running**

lando init pantheon
lando start -vvv

**Tell us about the error you got**

Macintosh-2:commerce paul$ lando init pantheon
? Choose a Pantheon account basscleff94010@gmail.com
? Which site? nativecommerce
error: Directory /Users/paul/Sites/Commerce must be empty to Pantheon init.
Macintosh-2:commerce paul$ lando version
v3.0.0-beta.35
Macintosh-2:commerce paul$ ls
Macintosh-2:commerce paul$ cd ..
Macintosh-2:Sites paul$ ls
Backup			IschiaWordPressRepo	custom drupal modules	images			myimpressario8		scripts
Commerce		SFCSWordPressRepo	devdesktop2		lightening		post-receive		wordpress
Macintosh-2:Sites paul$ cd Commerce
Macintosh-2:Commerce paul$ lando init pantheon
? Choose a Pantheon account basscleff94010@gmail.com
? Which site? nativecommerce
Creating landoinitnativecommerce_util_1 ... 
Creating landoinitnativecommerce_util_1 ... done
Scanning /user/.ssh for keys...
Scanning /user/.lando/keys for keys...
Checking whether /user/.ssh/known_hosts.old is a private key...
Checking whether /user/.ssh/id_rsa is a private key...
Checking whether /user/.ssh/id_rsa is formatted correctly...
Checking whether /user/.ssh/id_dsa is a private key...
Checking whether /user/.ssh/id_dsa is formatted correctly...
Checking whether /user/.lando/keys/pantheon.lando.id_rsa is a private key...
Checking whether /user/.lando/keys/pantheon.lando.id_rsa is formatted correctly...
Checking whether /user/.lando/keys/github.lando.id_rsa is a private key...
Checking whether /user/.lando/keys/github.lando.id_rsa is formatted correctly...
Ensuring permissions for /user/.ssh/id_rsa...
Ensuring permissions for /user/.ssh/id_dsa...
Ensuring permissions for /user/.lando/keys/pantheon.lando.id_rsa...
Ensuring permissions for /user/.lando/keys/github.lando.id_rsa...
Using the following keys: /user/.ssh/id_rsa /user/.ssh/id_dsa /user/.lando/keys/pantheon.lando.id_rsa /user/.lando/keys/github.lando.id_rsa
landoinitnativecommerce_util_1 is up-to-date
Cloning into '.'...
remote: Counting objects: 75029, done.
remote: Compressing objects: 100% (30310/30310), done.
remote: Total 75029 (delta 39898), reused 75023 (delta 39896)
Receiving objects: 100% (75029/75029), 39.97 MiB | 826.00 KiB/s, done.
Resolving deltas: 100% (39898/39898), done.
Checking connectivity... done.
Checking out files: 100% (13645/13645), done.
Stopping landoinitnativecommerce_util_1 ... done
Removing landoinitnativecommerce_util_1 ... done

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run
`lando start` to get rolling.

Check the LOCATION printed below if you are unsure where to go.

Here are some vitals:

 NAME      nativecommerce                                       
 LOCATION  /Users/paul/Sites/Commerce                           
 RECIPE    pantheon                                             
 DOCS      https://docs.devwithlando.io/tutorials/pantheon.html 
 METHOD    pantheon                                             

Macintosh-2:Commerce paul$ lando start -vvv

**++++++at this point terminal hangs with no more output++++++**

**Tell us more**

This is such a basic, simple problem that there must be something I am SERIOUSLY missing.

**Does this bug prevent you from using lando?

Yes

**Comment by ccjjmartin** [comment] 2018-01-26 22:27
@paul94010 Your log shows:
error: Directory /Users/paul/Sites/Commerce must be empty to Pantheon init.

It is likely your laptop / desktop doesn't have an empty directory at that location.  If this command works you should have a .lando.yml file in that location.

**Comment by vernontnh** [comment] 2018-02-16 16:01
I do not get an empty directory. According to the installer it's supposed to be installed, but when I try to get started by entering lando start in terminal, it says warn: Could not find app in this dir

**Comment by vernontnh** [comment] 2018-02-16 16:17
nope. I thought the first command was supposed to be lando start.
Hmmm...Thanks, now it's asking me what recipe I want to use, but I want to
use Pantheon and it's not listed.



Vernon Thornblad
vthornblad@antioch.edu
cell: 617-823-9624 *TRY FIRST*
office: 603-283-2380

**Comment by vernontnh** [comment] 2018-02-16 16:22
The instructions I'm seeing here:
https://docs.google.com/presentation/d/1IUS3uTo8hFiqndGcOZ3ZGxcW6KNaXl11a1ZZpA9OJkc/edit#slide=id.g2b8f115aec_0_11
from Pantheon seem to suggest I need to start with "lando start" and then
move to "$mkdir mysite && cd mysite" etc...



Vernon Thornblad
vthornblad@antioch.edu
cell: 617-823-9624 *TRY FIRST*
office: 603-283-2380

**Comment by ccjjmartin** [comment] 2018-02-16 16:25
@vernontnh `lando init` creates a .lando.yml file.  If you don't have one then you will need to create one.  I am surprised that Pantheon isn't a recipe for you.  Did you try these docs: https://docs.devwithlando.io/tutorials/pantheon.html

**Comment by vernontnh** [comment] 2018-02-16 16:37
So can I pate the following into terminal to get the whole thing started
(from this page: https://docs.devwithlando.io/cli/init.html#pantheon):

lando init github --recipe=pantheon


Vernon Thornblad
vthornblad@antioch.edu
cell: 617-823-9624 *TRY FIRST*
office: 603-283-2380

**Comment by ccjjmartin** [comment] 2018-02-16 17:21
@vernontnh It looks like there is a difference between if you are pulling code from Pantheon or if you are working with an existing local repo.  It sounds like you have an existing local repo so I believe this is the version of the command you are looking for: `lando init --recipe pantheon`

If you were working with a fresh directory and were willing to pull the code from Pantheon then it looks like this should work: `lando init pantheon`

**Comment by vernontnh** [comment] 2018-02-16 17:51
OK...so to be clear, I have pulled nothing from Pantheon and wish to pull a
dev branch from there to local. So... lando init pantheon?

Is it really that simple?

Vernon Thornblad
vthornblad@antioch.edu
cell: 617-823-9624 *TRY FIRST*
office: 603-283-2380

**Comment by vernontnh** [comment] 2018-02-16 19:23
Here's where I am (please note the warning at the bottom) :

I've searched both on github. Looks like lando is not able to deal with
WordPress multisites without a lot of editing.
https://github.com/lando/lando/issues/157

Shall I give up?

Last login: Fri Feb 16 11:12:09 on ttys002

imac27in:~ vernonthornblad1$ lando init pantheon

? Choose a Pantheon account vthornblad@antioch.edu

? Which site? antioch

error: Directory /Users/vernonthornblad1 must be empty to Pantheon init.

imac27in:~ vernonthornblad1$ lando init pantheon

? Choose a Pantheon account vthornblad@antioch.edu

? Which site? antioch

error: Directory /Users/vernonthornblad1 must be empty to Pantheon init.

imac27in:~ vernonthornblad1$ lando init --recipe pantheon

? Choose a Pantheon account vthornblad@antioch.edu

? Which site? antioch


NOW WE'RE COOKING WITH FIRE!!!

Your app has been initialized!


Go to the directory where your app was initialized and run

`lando start` to get rolling.


Check the LOCATION printed below if you are unsure where to go.


Here are some vitals:


 NAME      antioch

 LOCATION  /Users/vernonthornblad1

 RECIPE    pantheon

 DOCS      https://docs.devwithlando.io/tutorials/pantheon.html


imac27in:~ vernonthornblad1$ lando start

warn: wordpress_network is not a supported recipe.

error:  TypeError: Cannot read property 'filemount' of undefined


Vernon Thornblad
vthornblad@antioch.edu
cell: 617-823-9624 *TRY FIRST*
office: 603-283-2380

**Comment by serundeputy** [comment] 2018-02-22 23:27
thanks for reporting @paul94010 and the troubleshooting from @ccjjmartin and @vernontnh !

Here is what did in trying to come up with the steps to reproduce (STR) this problem:

* Spin up a WordPress site (`wp-ms`) on Pantheon
* On my computer `mkdir wp-ms`
* `cd wp-ms`
* `lando init pantheon`
  * select my email
  * select my site `wp-ms`
Here is the resulting `.lando.yml` file:

```yaml
name: wp-ms
recipe: pantheon
config:
  framework: wordpress
  site: wp-ms
  id: 5d50dcce-a167-49fe-a42e-2a7fa443f8b6

```

* `lando start`
* `lando pull`

At this point I have a site that I can visit and use. Looks to me that the main issue here was trying to use `lando init pantheon` from a directory that already had some files in it.

I followed the same steps for a Drupal 8 site started on Pantheon; same result.

I'm going to close this issue out as there is no action item for the Lando software itself. If anyone can provide the STR or and action item for Lanod feel free to reopen the issue with the STR.

**Closed by serundeputy** 2018-02-22 23:27 UTC
