### ISSUE TITLE
setting .lando.yml to use drush 9.5.2 that was set in composer

### ISSUE THREAD

**Issue by shaal** [lando/lando#1317] opened 2018-11-28 16:53 UTC
Documentation Issue
================

**Tell us about your setup**
Lando v3.0.0-rc.1, Ubuntu 18.10, docker-ce 18.09.0

**Tell us about your `.lando.yml`**
```
name: spiewak
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: spiewak
  id: c1f2d565-ac04-47ad-b2ee-d19bf281e8dc
  drush: composer
```

according to the documentation - https://docs.devwithlando.io/tutorials/drupal8.html#recipe
the above .lando.yml with `drush:composer` should be the correct way to use the drush I set in composer.

I setup drush in composer.json - `"drush/drush": "^9.5"`
after `lando rebuild -y`, running `lando drush cr`, I get this error -
```/usr/bin/env: php: No such file or directory```

(I can run successfully `lando ssh`, and in there `../vendor/bin/drush cr`)

changing `.lando.yml` to 
```
name: spiewak
recipe: pantheon
config:
  framework: drupal8
  xdebug: true
  env: dev
  site: spiewak
  id: c1f2d565-ac04-47ad-b2ee-d19bf281e8dc
tooling:
  drush:
    cmd:
      - /app/vendor/bin/drush
```
now running `lando rebuild -y`, solves the problem.
`lando drush cr` works perfect, it's using drush 9.5.2

**Comment by pirog** [comment] 2018-11-28 17:10
@shaal the documentation you are referencing is for the `drupal8` recipe. your .`lando.yml` indicates you have a `pantheon` recipe. The config between these two recipes is not swappable.

**Comment by ccharlton** [comment] 2018-11-29 22:05
A fellow developer mentioned changing her config to include `drush: global:8.1.16` helped.

**Comment by jwbabc** [comment] 2018-12-03 20:13
@shaal I just want to thank you for posting your fix. I encountered this same error and being new to lando had no idea which environment variables to begin to look at. Your fix worked perfectly.

**Comment by aangelinsf** [comment] 2018-12-10 22:20
Following the guidance from https://github.com/lando/lando/issues/1315, I can report that upgrading to Drush 9 and using the following worked for me:
```
tooling:
  drush:
    cmd: /app/vendor/bin/drush
```

**Comment by pirog** [comment] 2019-01-13 02:00
This is caused by the same underlying issue as #1315 so closing as a dupe

**Closed by pirog** 2019-01-13 02:00 UTC
