### ISSUE TITLE
lando drush uli results in a "OCI run time exec failed" state

### ISSUE THREAD

**Issue by alphex** [lando/lando#1542] opened 2019-03-20 15:08 UTC
**Tell us about your setup**

OSX 10.14.3 (18D109)
Lando v3.0.0-rc.14

**Tell us about your `.lando.yml`**

`.lando.yml`
```
name: foobar-pcah
recipe: pantheon
config:
  framework: drupal
  site: foobar-pcah
  id: xxx-xxx-xxx-xxx-xxx
```

**Tell us about the command you were running**

`lando drush uli`

**Tell us about the error you got**

```
OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown
```

I then ran `lando restart` to see if that cleaned things up.

Still received the same error.

I restarted docker, restarted lando via `lando restart` , and am still getting the same error.

I'm about to attempt a `lando destroy`,  but I hope that's not the solution if this is chronic?

... verified

lando destroy solved the problem.

not sure if there's anything that can be done with this, but something broke :)

**Comment by pirog** [comment] 2019-03-20 15:31
@alphex in the post rc2 world you'll want to do `lando rebuild` instead of `lando restart` in these kinds of scenarios. 

If you interrupted a build process at any point or inadvertently changed the state of the containers it could explain not finding `drush`. `lando rebuild` will set you back on the righteous path.

**Comment by tormi** [comment] 2019-04-17 08:54
@alphex, any chance you're using `bash` in your Lando scipts? If yes, then switch over to `sh`, because Alpine images Lando is using doesn't have `bash` installed.

Ref: https://github.com/docker/for-linux/issues/246#issuecomment-451938690

**Comment by tormi** [comment] 2019-04-17 09:04
Or are you using pure pantheon recipe? Then it might be somewhere _behind the scenes_ ..

**Comment by tormi** [comment] 2019-04-17 10:45
@floretan said that `drush` assumes `bash` is installed. `sh` is not supported and some stuff will not work. @weitzman, can you confirm it?

cc: @pirog

**Comment by weitzman** [comment] 2019-04-17 10:51
confirmed.

**Comment by tormi** [comment] 2019-04-17 11:00
Then we have a problem ..

**Comment by pirog** [comment] 2019-04-17 11:34
FWIW all our php runtime containers are Debian based unless you’ve
explicitly swapped them out.

We use alpine in a few instances but it’s doubtful you would ever be
running drush in them

**Comment by alphex** [comment] 2019-04-17 12:11
@tormi these are unmodified, “stock” lando setups.  I have not customized any scripts or anything else in lando.   

Thank you.

**Comment by tormi** [comment] 2019-04-17 12:25
@pirog, my containers by services:

- appserver: **debian**

<img width="448" alt="Screenshot 2019-04-17 at 15 19 36" src="https://user-images.githubusercontent.com/146800/56287378-d57d8200-6124-11e9-9c6f-0bb9590d9937.png">

- database: **bitnami**

<img width="448" alt="Screenshot 2019-04-17 at 15 21 39" src="https://user-images.githubusercontent.com/146800/56287399-e3330780-6124-11e9-9369-3a5eac1ac368.png">

**Comment by tormi** [comment] 2019-04-17 12:27
Correct:

<img width="448" alt="Screenshot 2019-04-17 at 15 19 36" src="https://user-images.githubusercontent.com/146800/56287533-4755cb80-6125-11e9-9327-0a582c58bf10.png">

**Comment by ccharlton** [comment] 2019-07-02 17:51
FWIW, a `lando rebuild` resolved this for me. It appeared "out of nowhere" (literally just didn't touch my laptop for 2 days).

**Comment by ptmkenny** [comment] 2019-10-28 13:37
I found a way to reproduce this on MacOS Mojave.

1. Switch the user default shell to zsh. (I did this to prep for Catalina.)
2. Pull a D8 site from Pantheon.
3. The site builds correctly, but when you try to run drush, you get the error.

Switching the shell: Go to System Preferences, Accounts, right-click on the user name, advanced options, and then change the shell.

Switching the user's default shell back to bash, restarting the system, and then running `lando rebuild` will allow lando to work again... but you can't switch shells then.

**Comment by grantkruger** [comment] 2019-12-19 18:40
Just a comment that I use zsh on Mac and had this working fine on different versions of Lando, unlike the comment by @ptmkenny. Instead my experience is much the same as @ccharlton in that I hadn't used my local in a couple of days and came back to do a security update, only to find drush had stopped working. A rebuild fixed it for me too.

**Comment by arcataroger** [comment] 2019-12-30 16:17
Same thing here, seemingly stopped working overnight, though I can't be sure. (Run the same Lando profile on several machines, some of which are OSX with zsh while others are Ubuntu). `lando rebuild` fixed it.

**Comment by freshyill** [comment] 2020-01-17 17:35
I randomly experienced this happening for no reason literally overnight. `lando rebuild` fixes it, but it's still annoying.

**Comment by pirog** [comment] 2020-03-25 02:29
closing in favor of #2079

**Closed by pirog** 2020-03-25 02:29 UTC
Labels: bug

**Comment by systemovich** [comment] 2020-04-24 21:30
I have been getting this error immediately after a PHP error, on Windows 10, e.g. if a require_once cannot find a file, or ir file permissions could not be set.

**Comment by glantucan** [comment] 2020-04-27 12:42
This is happening to me also randomly, apparently. I'll check what @systemovich said and update this as soon as I can.

**Comment by grantkruger** [comment] 2020-10-06 23:46
This just happened to me again where I do have an incident that caused it. I was working in my Lando environment without issue when something crashed and rebooted my entire Macbook (Docker crushes Macs). After rebooting I got this error. The usual `lando rebuild` fixed it.

**Comment by dorianwinterfeld** [comment] 2020-12-22 14:58
I am having the same error running lando v3.0.23 on a Mac/Catalina.  I am using zsh.  Is there a fix or do I have to switch to bash?

**Comment by grantkruger** [comment] 2020-12-23 17:15
> I am having the same error running lando v3.0.23 on a Mac/Catalina. I am using zsh. Is there a fix or do I have to switch to bash?

@dorianwinterfeld I use zsh on Mojave and a `lando rebuild` still works to fix this for me whenever the error occasionally happens.

**Comment by dorianwinterfeld** [comment] 2020-12-24 13:07
I tried rebuild.  I also tried switching my shell to bash but I still get the same error:

AIP-DWINTERFELD-MAC:drupal9lando dorianwinterfeld$ lando drush status
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "drush": executable file not found in $PATH: unknown

This is the $PATH variable in the container:

AIP-DWINTERFELD-MAC:drupal9lando dorianwinterfeld$ lando ssh
www-data@aeb50863e783:/app$ echo $PATH
/app/vendor/bin:/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin:/helpers

Am I missing something?

**Comment by doostinharrell** [comment] 2020-12-28 16:08
I'm also experiencing this issue this morning.  Last week everything was working as expected, `lando rebuid -y` isn't solving this  issue for me either. 

`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown`

---

```
www-data@583ec1a50d56:/app/vendor/bin$ echo $PATH
/app/vendor/bin:/app/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/.composer/vendor/bin:/helpers
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /app/vendor/bin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /app/bin | grep drush
ls: cannot access '/app/bin': No such file or directory
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /usr/local/sbin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /usr/local/bin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /usr/sbin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /usr/bin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /sbin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /bin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /var/www/.composer/vendor/bin | grep drush
www-data@583ec1a50d56:/app/vendor/bin$ ls -la /helpers | grep drush
www-data@583ec1a50d56:/app/vendor/bin$
```

**Comment by doostinharrell** [comment] 2020-12-28 16:15
I manually required `drush` in my project composer file to bandaid the issue as `/app/vendor/bin` is included in the `$PATH` var. 

`composer require drush/drush` should be a good short term solution for anyone running into this issue for Drupal 8 or Drupal 9 projects running composer.

**Comment by jorge-brizio** [comment] 2021-01-12 16:35
Thanks @doostinharrell! Your solution worked for me.

**Comment by RightsandWrongsgit** [comment] 2021-03-23 19:39
I just had this same error message thrown after doing a new Lando update installation on 3_23_2021 and a lando rebuild afterward.  But when I did @doostinharrell's solution it worked fine.

**Comment by dens0ne** [comment] 2021-12-15 00:32
For anybody else like me that lands here using the Drupal 9 recipe and expect `drush` to be available out-of-the-box, I missed this part of the documentation: https://docs.lando.dev/config/drupal9.html#using-drush. After running `lando composer require drush/drush` I got this issue resolved.

**Comment by janrain-rest** [comment] 2022-02-21 23:24
> For anybody else like me that lands here using the Drupal 9 recipe and expect drush to be available out-of-the-box, I missed this part of the documentation: https://docs.lando.dev/config/drupal9.html#using-drush. After running lando composer require drush/drush I got this issue resolved.

The same here. Solved with `composer require drush/drush `

**Comment by axroth** [comment] 2022-05-19 08:42
fyi: if you require drush ^8 in docroot, it fixes that issue as well for drupal 7.

**Comment by suparnad** [comment] 2022-06-30 11:12
@doostinharrell 's solution composer require drush/drush works for me for my lando drupal 9 site.

**Comment by eeyorr** [comment] 2022-11-29 21:43
What fixed it for me was deleting my vendor directory and doing a fresh composer install.

**Comment by shwetaoti** [comment] 2023-05-30 12:57
Thanks @doostinharrell 
This works for me.

**Comment by dimitridarras** [comment] 2023-07-24 02:37
To state the 'obvious', I have a local composer install but the following needs to run as  `lando composer require drush/drush`

**Comment by puzurgh** [comment] 2023-08-15 07:57
In my case `chmod -R 777 vendor/` helped

**Comment by khiemnguyen-ffw** [comment] 2023-11-25 14:29
I installed drush by composer require. It's solved.

**Comment by oscarnovasf** [comment] 2024-01-31 15:46
remove vendor folder and run lando composer update works for me
