### ISSUE TITLE
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign 

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#274] opened 2017-08-11 15:23 UTC
version: `v3.0.0-beta.8`

lando commit: `fa3552d`
version: 

today I got this error:
```bash
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
error:  Error: Error: 1
    at /Users/geoff/code/lando.dev/lib/promise.js:56:17
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at rec (/Users/geoff/code/lando.dev/lib/promise.js:42:13)
    at /Users/geoff/code/lando.dev/lib/promise.js:50:20
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
From previous event:
    at /Users/geoff/code/lando.dev/lib/promise.js:49:12
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

on trying to start any new lando d8 or pantheon apps, but I suspect it would’ve been any new app.

doing:

```
docker network prune
```

solved the issue

I don’t understand a lot of the things in this issue: https://github.com/reduardo7 but maybe you guys do; don’t know if there is anything we can do about it on the `lando` side, but most people prolly wont have 30+ `lando` appss
GitHub
reduardo7 (Eduardo Cuomo)
reduardo7 has 77 repositories available. Follow their code on GitHub.

**Comment by shaal** [comment] 2017-08-11 16:05
I received the same error, and that docker command fixed it

**Comment by labboy0276** [comment] 2017-09-25 14:54
I got this as well, but looks like it may be fixed in rc1.  Running ```docker network prune``` does fix this.

**Comment by pirog** [comment] 2017-10-01 07:59
@serundeputy @shaal @labboy0276 

It might be nice to get this into the docs as a known issue?

**Comment by serundeputy** [comment] 2017-10-13 18:38
@pirog PR to add to Known Issues: https://github.com/lando/lando/pull/408

**Closed** 2017-10-13 21:13 UTC
Labels: documentation

**Comment by ivanm11** [comment] 2017-12-05 15:45
You can try 
$sudo service network-manager restart
should help

**Comment by shaal** [comment] 2017-12-25 17:13
Is this issue got resolved already?
I am using Lando v3.0.0-beta.31

After getting the same error again, I tried the last command recommended above
`sudo service network-manager restart`
but `lando start` resulted in the same error.

So I went back to the good ol' 
`docker network prune`

```
WARNING! This will remove all networks not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Networks:

mucchaetululutuvutycumpusul_default
landounutshumulkb_default
uluctlunul_default
phpclu_default
cupu_default
much7_default
landounut3pucus_default
lusunbulg_default
landounutlulutuvutyuvuntmunugumunt_default
landounutfldcd8_default
lulutuvutyuvuntmunugumunt_default
pucus_default
myfldcumpusul_default
landounutmyfldcumpusul_default
landounutlusunbulg_default
spaewuk_default
landounutmucchaetululutuvutycumpusul_default
shumulkb_default
landounutull_default
landounutshlumku_default
landounutskysup_default
utustu_default
landounututustu_default
myfluntundupp_default
shlumku_default
landounutcupu_default
mucchaetuvulbusu_default
lulutuvutyfuluvuntmunugumunt_default
landounutspaewuk_default
```

...and now `lando start` works like a charm

**Comment by paigeadelethompson** [comment] 2019-03-15 07:44
In my case this was due to lingering elastic network interfaces (ENIs) from a docker crash that just never got cleaned up by the daemon, a simple fix for me however admittedly very misleading: 

```
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:37:32 on master ✹)──>  docker-compose up -d                                                                                                                                                                              ──(Fri,Mar15)─┘
WARNING: Some networks were defined but are not used by any service: nginx_to_jenkins, sshbastion_to_ansibletower
Creating network "netcravedocker_nginx_to_yacy" with the default driver
Creating network "netcravedocker_nginx_to_paigeat" with the default driver
Creating network "netcravedocker_powerdnsrecursor_to_powerdns" with the default driver
Creating network "netcravedocker_nginx_to_powerdns" with the default driver
Creating network "netcravedocker_anope_to_inspircd" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:40:21 on master ✹)──>  ip route                                                                                                                                                                                          ──(Fri,Mar15)─┘
default via 10.242.0.253 dev msft proto static 
10.1.0.0/24 dev br-6d32d5ad60db proto kernel scope link src 10.1.0.1 linkdown 
10.1.0.0/24 dev br-724b0e404767 proto kernel scope link src 10.1.0.1 linkdown 
10.2.0.0/24 dev br-c5b1288dc989 proto kernel scope link src 10.2.0.1 linkdown 
10.2.0.0/24 dev br-574473f199f6 proto kernel scope link src 10.2.0.1 linkdown 
10.3.0.0/24 dev br-cc8ad7d66b91 proto kernel scope link src 10.3.0.1 linkdown 
10.3.0.0/24 dev br-73886160631c proto kernel scope link src 10.3.0.1 linkdown 
10.4.0.0/24 dev br-fe65508e4005 proto kernel scope link src 10.4.0.1 linkdown 
10.4.0.0/24 dev br-ee0ff32e72e3 proto kernel scope link src 10.4.0.1 linkdown 
10.5.0.0/24 dev br-554c47027091 proto kernel scope link src 10.5.0.1 linkdown 
10.5.0.0/24 dev br-4addd60ce3ff proto kernel scope link src 10.5.0.1 linkdown 
10.6.0.0/24 dev br-74c9486cdfb9 proto kernel scope link src 10.6.0.1 linkdown 
10.6.0.0/24 dev br-0cda7bd3acc5 proto kernel scope link src 10.6.0.1 linkdown 
10.7.0.0/24 dev br-799cdcef0418 proto kernel scope link src 10.7.0.1 linkdown 
10.7.0.0/24 dev br-14010cf12bc1 proto kernel scope link src 10.7.0.1 linkdown 
10.8.0.0/24 dev br-08e60c04f2dd proto kernel scope link src 10.8.0.1 linkdown 
10.8.0.0/24 dev br-b6855091fd56 proto kernel scope link src 10.8.0.1 linkdown 
10.9.0.0/24 dev br-d766a2e7efab proto kernel scope link src 10.9.0.1 linkdown 
10.9.0.0/24 dev br-924e07b8327f proto kernel scope link src 10.9.0.1 linkdown 
10.10.0.0/24 dev br-c74deac092b7 proto kernel scope link src 10.10.0.1 linkdown 
10.10.0.0/24 dev br-19c3266b3584 proto kernel scope link src 10.10.0.1 linkdown 
10.11.0.0/24 dev br-da3fa7922ea0 proto kernel scope link src 10.11.0.1 linkdown 
10.11.0.0/24 dev br-8baf528248e6 proto kernel scope link src 10.11.0.1 linkdown 
10.242.0.0/24 dev msft proto kernel scope link src 10.242.0.254 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
172.18.0.0/16 dev br-4716cd548558 proto kernel scope link src 172.18.0.1 linkdown 
172.19.0.0/16 dev br-22fb28a463db proto kernel scope link src 172.19.0.1 linkdown 
172.20.0.0/16 dev br-68976a40b13e proto kernel scope link src 172.20.0.1 linkdown 
172.21.0.0/16 dev br-b691801bae2d proto kernel scope link src 172.21.0.1 linkdown 
172.22.0.0/16 dev br-903ff810cfb6 proto kernel scope link src 172.22.0.1 linkdown 
172.23.0.0/16 dev br-194f2ab08b4f proto kernel scope link src 172.23.0.1 linkdown 
172.24.0.0/16 dev br-8b0022310f8d proto kernel scope link src 172.24.0.1 linkdown 
172.25.0.0/16 dev br-b2bad4265911 proto kernel scope link src 172.25.0.1 linkdown 
172.26.0.0/16 dev br-b5aa90c69517 proto kernel scope link src 172.26.0.1 linkdown 
172.27.0.0/16 dev br-bbc89730d40a proto kernel scope link src 172.27.0.1 linkdown 
172.28.0.0/16 dev br-1abc58dd7cbd proto kernel scope link src 172.28.0.1 linkdown 
172.29.0.0/16 dev br-89b426498acb proto kernel scope link src 172.29.0.1 linkdown 
172.30.0.0/16 dev br-a9e77b9f2c83 proto kernel scope link src 172.30.0.1 linkdown 
172.31.0.0/16 dev br-0fb1c24d70e2 proto kernel scope link src 172.31.0.1 linkdown 
192.168.1.0/24 dev ether-0 proto kernel scope link src 192.168.1.248 
192.168.16.0/20 dev br-29925f2609f4 proto kernel scope link src 192.168.16.1 linkdown 
192.168.32.0/20 dev br-8760d3d3666b proto kernel scope link src 192.168.32.1 linkdown 
192.168.48.0/20 dev br-2f0cf7fe7bfc proto kernel scope link src 192.168.48.1 linkdown 
192.168.64.0/20 dev br-0371165c14b6 proto kernel scope link src 192.168.64.1 linkdown 
192.168.80.0/20 dev br-0a63824d35be proto kernel scope link src 192.168.80.1 linkdown 
192.168.96.0/20 dev br-ca37c7e0916d proto kernel scope link src 192.168.96.1 linkdown 
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1 linkdown 
192.168.128.0/20 dev br-a461d0cd9d58 proto kernel scope link src 192.168.128.1 linkdown 
192.168.144.0/20 dev br-6b3ff82aab0b proto kernel scope link src 192.168.144.1 linkdown 
192.168.160.0/20 dev br-7d97680388dd proto kernel scope link src 192.168.160.1 linkdown 
192.168.176.0/20 dev br-1e243b28e5f4 proto kernel scope link src 192.168.176.1 linkdown 
192.168.192.0/20 dev br-91d612b9408d proto kernel scope link src 192.168.192.1 linkdown 
192.168.208.0/20 dev br-0dd07cdac815 proto kernel scope link src 192.168.208.1 linkdown 
192.168.224.0/20 dev br-dc531fe4a4f8 proto kernel scope link src 192.168.224.1 linkdown 
192.168.240.0/20 dev br-34a481dc61de proto kernel scope link src 192.168.240.1 linkdown 
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:40:32 on master ✹)──>  ip route  awk '{print $3}'                                                                                                                                                                        ──(Fri,Mar15)─┘
Command "awk" is unknown, try "ip route help".
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:40:46 on master ✹)──>  ip route  | awk '{print $3}'                                                                                                                                                                255 ↵ ──(Fri,Mar15)─┘
10.242.0.253
br-6d32d5ad60db
br-724b0e404767
br-c5b1288dc989
br-574473f199f6
br-cc8ad7d66b91
br-73886160631c
br-fe65508e4005
br-ee0ff32e72e3
br-554c47027091
br-4addd60ce3ff
br-74c9486cdfb9
br-0cda7bd3acc5
br-799cdcef0418
br-14010cf12bc1
br-08e60c04f2dd
br-b6855091fd56
br-d766a2e7efab
br-924e07b8327f
br-c74deac092b7
br-19c3266b3584
br-da3fa7922ea0
br-8baf528248e6
msft
docker0
br-4716cd548558
br-22fb28a463db
br-68976a40b13e
br-b691801bae2d
br-903ff810cfb6
br-194f2ab08b4f
br-8b0022310f8d
br-b2bad4265911
br-b5aa90c69517
br-bbc89730d40a
br-1abc58dd7cbd
br-89b426498acb
br-a9e77b9f2c83
br-0fb1c24d70e2
ether-0
br-29925f2609f4
br-8760d3d3666b
br-2f0cf7fe7bfc
br-0371165c14b6
br-0a63824d35be
br-ca37c7e0916d
virbr0
br-a461d0cd9d58
br-6b3ff82aab0b
br-7d97680388dd
br-1e243b28e5f4
br-91d612b9408d
br-0dd07cdac815
br-dc531fe4a4f8
br-34a481dc61de
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:40:50 on master ✹)──>  ip route  | awk '{print $3}' | grep "br-"                                                                                                                                                         ──(Fri,Mar15)─┘
br-6d32d5ad60db
br-724b0e404767
br-c5b1288dc989
br-574473f199f6
br-cc8ad7d66b91
br-73886160631c
br-fe65508e4005
br-ee0ff32e72e3
br-554c47027091
br-4addd60ce3ff
br-74c9486cdfb9
br-0cda7bd3acc5
br-799cdcef0418
br-14010cf12bc1
br-08e60c04f2dd
br-b6855091fd56
br-d766a2e7efab
br-924e07b8327f
br-c74deac092b7
br-19c3266b3584
br-da3fa7922ea0
br-8baf528248e6
br-4716cd548558
br-22fb28a463db
br-68976a40b13e
br-b691801bae2d
br-903ff810cfb6
br-194f2ab08b4f
br-8b0022310f8d
br-b2bad4265911
br-b5aa90c69517
br-bbc89730d40a
br-1abc58dd7cbd
br-89b426498acb
br-a9e77b9f2c83
br-0fb1c24d70e2
br-29925f2609f4
br-8760d3d3666b
br-2f0cf7fe7bfc
br-0371165c14b6
br-0a63824d35be
br-ca37c7e0916d
br-a461d0cd9d58
br-6b3ff82aab0b
br-7d97680388dd
br-1e243b28e5f4
br-91d612b9408d
br-0dd07cdac815
br-dc531fe4a4f8
br-34a481dc61de
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:40:59 on master ✹)──>  ip route  | awk '{print $3}' | grep "br-"  xargs -i -t ip link del {}                                                                                                                             ──(Fri,Mar15)─┘
grep: invalid option -- 't'
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:41:15 on master ✹)──>  ip route  | awk '{print $3}' | grep "br-"  | xargs -i -t ip link del {}                                                                                                                       2 ↵ ──(Fri,Mar15)─┘
ip link del br-6d32d5ad60db 
ip link del br-724b0e404767 
ip link del br-c5b1288dc989 
ip link del br-574473f199f6 
ip link del br-cc8ad7d66b91 
ip link del br-73886160631c 
ip link del br-fe65508e4005 
ip link del br-ee0ff32e72e3 
ip link del br-554c47027091 
ip link del br-4addd60ce3ff 
ip link del br-74c9486cdfb9 
ip link del br-0cda7bd3acc5 
ip link del br-799cdcef0418 
ip link del br-14010cf12bc1 
ip link del br-08e60c04f2dd 
ip link del br-b6855091fd56 
ip link del br-d766a2e7efab 
ip link del br-924e07b8327f 
ip link del br-c74deac092b7 
ip link del br-19c3266b3584 
ip link del br-da3fa7922ea0 
ip link del br-8baf528248e6 
ip link del br-4716cd548558 
ip link del br-22fb28a463db 
ip link del br-68976a40b13e 
ip link del br-b691801bae2d 
ip link del br-903ff810cfb6 
ip link del br-194f2ab08b4f 
ip link del br-8b0022310f8d 
ip link del br-b2bad4265911 
ip link del br-b5aa90c69517 
ip link del br-bbc89730d40a 
ip link del br-1abc58dd7cbd 
ip link del br-89b426498acb 
ip link del br-a9e77b9f2c83 
ip link del br-0fb1c24d70e2 
ip link del br-29925f2609f4 
ip link del br-8760d3d3666b 
ip link del br-2f0cf7fe7bfc 
ip link del br-0371165c14b6 
ip link del br-0a63824d35be 
ip link del br-ca37c7e0916d 
ip link del br-a461d0cd9d58 
ip link del br-6b3ff82aab0b 
ip link del br-7d97680388dd 
ip link del br-1e243b28e5f4 
ip link del br-91d612b9408d 
ip link del br-0dd07cdac815 
ip link del br-dc531fe4a4f8 
ip link del br-34a481dc61de 
┌─(/mnt/export/netcrave_docker)system: ruby 2.5.0p0───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@molly:pts/0)─┐
└─(00:41:27 on master ✹)──>  docker-compose up -d                                                                                                                                                                              ──(Fri,Mar15)─┘
WARNING: Some networks were defined but are not used by any service: nginx_to_jenkins, sshbastion_to_ansibletower
Creating network "netcravedocker_anope_to_inspircd" with the default driver
Creating network "netcravedocker_nginx_to_video" with the default driver
Creating network "netcravedocker_tor_to_sshbastion" with the default driver
Creating network "netcravedocker_nginx_to_mediawiki" with the default driver
Creating network "netcravedocker_nginx_to_oxpki" with the default driver
Creating network "netcravedocker_nginx_to_powerdnsadmin" with the default driver
Creating network "netcravedocker_tor_to_nginx" with the default driver
Creating network "netcravedocker_powerdnsadmin_to_powerdns" with the default driver
Creating network "netcravedocker_nginx_to_phpmyadmin" with the default driver
Creating network "netcravedocker_nginx_to_hapstat" with the default driver
Creating network "netcravedocker_nginx_to_rsyslog" with the default driver
Creating network "netcravedocker_default" with the default driver
Creating network "netcravedocker_nginx_to_mattermost" with the default driver
Creating network "netcravedocker_nginx_to_music" with the default driver
Creating network "netcravedocker_eggdrop_to_inspircd" with the default driver
Creating volume "netcravedocker_powerdns-admin-assets2" with default driver
Creating volume "netcravedocker_powerdns-mysql-data" with default driver
Creating volume "netcravedocker_powerdns-admin-mysql-data" with default driver
Creating volume "netcravedocker_powerdns-admin-assets3" with default driver
Creating volume "netcravedocker_powerdns-admin-assets" with default driver
Building powerdns
Step 1/5 : from debian:latest
latest: Pulling from library/debian
22dbe790f715: Pull complete

```

**Comment by salimdawod1996** [comment] 2019-05-30 13:01
i fixed this issue by steps :
1- turn off your network (wireless or wired...).
2- reboot your system.
3-before turn on your network on pc, execute command docker-compose up , it going to create new network.
4-then you can turn network on and go on ...

**Comment by chris-aeviator** [comment] 2020-10-09 15:49
`docker network create yournetwork --subnet 10.0.1.0/24`

**Comment by f1rf1n** [comment] 2021-01-30 12:09
I was using the windscribe vpn client. For me `windscribe disconnect` solves the problem (reproducably). Once lando has started up all the containers I can `windscribe connect` and all remains in working order. It just seems to be in the way while starting up lando.
Might be connected to the openvpn comment above.
