### ISSUE TITLE
xDebug is not being enabled/working.

### ISSUE THREAD

**Issue by NathanHealea** [lando/lando#3719] opened 2024-06-11 18:15 UTC
Configuring xDebug in the `.lando.yml` file is not working. 

When viewing the `admin/reports/status/php`, xdebug does not show up. 

I've been following these walkthrough: https://docs.lando.dev/guides/lando-with-vscode.html

Here is `.lando.yml` file with sensitive information have been replaced with (...).

```yml
name: ...
recipe: pantheon
config:
  framework: drupal8
  site: ...
  id: ...
  xdebug: true

services:
  appserver:
    webroot: web
    xdebug: true
```

Im not sure if the docs are wrong, as this walkthrough was working prior to updates at the beginning my June, 2024.

**Comment by reynoldsalec** [comment] 2024-06-13 19:35
Going to close this out as a duplicate of https://github.com/lando/docs/issues/279, seems like starting in `lando/docs` makes sense.

**Closed by reynoldsalec** 2024-06-13 19:35 UTC
Labels: bug

**Comment by NathanHealea** [comment] 2024-06-17 14:45
Additionally, when looking at the `/admin/reports/status/php`.

There is no information about the xdebug configs. They should show up between Tokenizer and xml. 

![image](https://github.com/lando/lando/assets/6578985/e45fa0ab-8dd5-41da-9bad-52659ae62407)
