### ISSUE TITLE
Cannot post Solr schema to Lando with Pantheon D8 recipe

### ISSUE THREAD

**Issue by dalin-** [lando/lando#656] opened 2018-01-18 19:00 UTC
**Tell us about your setup**

What is your lando version and operating system? 

v3.0.0-beta.35 
OSX 10.13 
Docker 17.09.1-ce-mac42 (the version packaged with Lando)

**Tell us about your `.lando.yml`**

standard Pantheon recipe:

```yml
name: my-site
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: my-site
  id: f8959ca9-1f8f-46bc-8539-8ffcf95e2123
```

**Tell us about the command you were running**

0. Have a functioning Pantheon lando site, with functioning Solr. 
1. Pull a fresh DB.
2. Visit `/admin/config/search/search-api/server/[server-machine-name]/edit`
3. Submit the form.  This should then submit the schema to Solr, and on the next page you should see a real value for _Configured Solr Version_.  

**Tell us about the error you got**
Sometimes it works, sometimes it doesn't.  If it doesn't, you see `example` for  _Schema_, but should see something like `drupal-4.5-solr-4.x`.  

If you get into this state, then the only way to solve the problem is to `lando rebuild`.  

The following things **don't** work:

1. `lando restart`
2. `lando stop`, stop docker, `lando start`
3. `lando stop`,  `docker rm [solr container uuid]`, `lando start`
4. restart laptop

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

I don't think it happens _every_ time I pull a new DB, but it has happened for several people on our team, on several different sites.

**Does this bug prevent you from using lando?**

Yes.  Can't work on solr features/bugs without solr.

**Comment by mndonx** [comment] 2018-01-22 14:22
I'm having this issue too. It clears only on a `lando rebuild`.

**Comment by dalin-** [comment] 2018-02-07 15:58
@dustinleblanc 
Can you reproduce this one?  This is driving our team nuts on several sites, which leads me to believe that it's an issue with the Pantheon recipe and not anything specific to just one app.

**Comment by dustinleblanc** [comment] 2018-02-07 20:22
@dalin- I haven't tried. Solr is the most confusing part of any site I've ever built so I don't touch it much. If I have time some evening I will definitely try to reproduce though.

**Comment by glassdimly** [comment] 2018-02-08 18:21
I can confirm this bug, and that `lando rebuild` fixes the problem. Weird. I do hope you get a chance to look at this @dustinleblanc, it's been a bit of a time suck when dealing with different branches.

**Comment by dustinleblanc** [comment] 2018-02-23 18:35
I'll put this in our backlog. I definitely suck at Solr, but I know we have a few bugs related to it.

**Comment by dustinleblanc** [comment] 2018-04-04 13:04
@dalin- @mndonx @glassdimly Are you able to reproduce this on Beta 39? So far I am unable to do so

**Comment by dustinleblanc** [comment] 2018-04-06 19:01
Closing this for now as I can't reproduce.

**Closed by dustinleblanc** 2018-04-06 19:01 UTC
Labels: bug, can not replicate, pantheon, solr

**Comment by aaron-capellic** [comment] 2018-06-13 15:06
This happens to me on beta-47, but only once after turning on the computer in the morning. Rebuild gets it working.

**Comment by dalin-** [comment] 2019-11-12 22:20
This problem might only manifest when you `lando start` on a codebase that is has a `.lando` file, but you don't yet have containers in Docker for it.  This could happen in a number of scenarios:
* You had a bunch of working sites, but then reset Docker
* You did a `git checkout` to start the site locally, rather than `lando init`

Could be related to #1836.

**Comment by dalin-** [comment] 2019-11-25 18:45
You can get around this by rebuilding _just_ the `appserver` (you might expect that it's`index` that is busted):

```
lando rebuild -s appserver -y
```

**Comment by sdubois** [comment] 2021-07-30 22:07
For what it's worth, I was experiencing this same issue today. I tried rebuilding, restarting, etc. multiple times.

Turns out what I needed to do was set the schema file to 4.0 and rebuild in the index. This should have been set already, not sure why it wasn't.

![image](https://user-images.githubusercontent.com/479460/127716199-36ed30a1-39c4-41b1-a20c-b3b318a0c092.png)
