### ISSUE TITLE
Platform.sh recipe SSL connection between containers

### ISSUE THREAD

**Issue by simonkey** [lando/lando#2926] opened 2021-03-24 10:42 UTC
I've a multi app setup with the platform.sh recipe. Everything works fine, except it is not possible to make a curl request from one service to another.

Setup (simplified):
Service: api -> api.test.lndo.site
Service: app -> www.test.lndo.site
Both services have an own `.platform.app.yaml`
Lando Version: v3.0.26

Two upstreams in the `routes.yaml`

```yaml
"https://www.{default}/": &upstreamApp
    type: upstream
    upstream: "app:http"

"https://api.{default}/": &upstreamApi
    type: upstream
    upstream: "api:http"
```

`.lando.yml`

```yml
name: test
recipe: platformsh
config:
  id: xxxx
  via: nginx
  xdebug: true
```

Both services are accessable via the browser via https://api.test.lndo.site and https://www.test.lndo.site, so the proxies does work. But if I try the following:
* Access to one of the services (e.g. the api service): `lando ssh`
* Make a curl request: `curl https://www.test.lndo.site/`
* The curl request results in `curl: (7) Failed to connect to api.mayspeedguide.lndo.site port 443: Connection refused`
* A non https-request works without problems

I've tried the symfony recipe and here the communication between the services works fine.

**Comment by pirog** [comment] 2021-03-24 12:56
@simonkey the platform.sh images do not encrypt at the service level but at the edge. Lando's container to container routing is entirely internal eg service to service so as of right now this is not possible. 

I don't think platform.sh intends to modify the images to support this however at some point we might be able to send these requests outside of Docker so they can hit our proxy before reentering. This would give the same results internally as one currently gets when hitting the same in the browser. Currently we do not do this because we do not have a reliable way to do so across all platforms.

**Comment by simonkey** [comment] 2021-03-25 07:50
@pirog Ok, thank you for your explaination. 
So for my understanding we have to use http only or the internal hostnames. This might be no problem for our custom code, but quite a problem for external packages and extensions.

**Comment by pirog** [comment] 2021-03-25 11:41
Not sure how that would impact external packages and extensions. Can you
elaborate?

**Comment by simonkey** [comment] 2021-03-29 13:28
There is an extension for TYPO3 called https://github.com/TYPO3-Solr/ext-solr. This extension can be used to index the pages of the CMS. Their approach for the page indexing is a GET-Request via guzzle which uses curl under the hood. In this case this indexing won't work, if I've defined the Base-Url with https. 
Another example would be the static routes feature from TYPO3 itself (https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/StaticRoutes.html#typo3-url-t3). It uses the base url defined in a site configuration (https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/SiteHandling/Basics.html#the-configuration-file) to fetch the content of a page. 
Since the environment should be as identical as the target system, we use for local developent always https and want to avoid special code only for local/lando development.

Another configuratio where https doesn't work is, when I use two lando projects. So for example project A (https://www.project-a.lndo.site/) calls a page from project B (https://www.procjet-b.lndo.site), there is still no https connection possible. As you mentioned before, this should be a edge to edge communicaton not a service to service communication.

**Comment by pirog** [comment] 2021-03-30 13:10
@simonkey ahh ok, i understand what you are saying now. we definitely prefer it work that way as well but right now i think we are limited by the capabilities of our own edge layer. that said, we will investigate and see if that has changed lately.

**Comment by pirog** [comment] 2021-03-30 18:27
@simonkey, @dustinleblanc came up with a pretty cool way to get this to work. The problem is that it's going to be a breaking change so we are debating how best to achieve that. Since the `platformsh` integration is still `beta` we are ok to introduce a breaking change there but we need to figure out how the rest of lando should handle it.

**Comment by pirog** [comment] 2021-04-06 12:32
This should be resolved in https://github.com/lando/lando/releases/tag/v3.0.29. You should now expect the same behavior when connecting to proxy addresses regardless of whether its from the host or from inside a container

**Closed by pirog** 2021-04-06 12:32 UTC
Labels: bug, platformsh
