### ISSUE TITLE
Custom SSL Cert

### ISSUE THREAD

**Issue by davideprevosto** [lando/lando#1476] opened 2019-02-20 07:53 UTC
Hi there,

Lando version: v3.0.0-rc.10

I am using `.test` domain, instead of `.lando.site` domain and I would like to trust the CA for any `example.test` domain. I was not able to make it works, I did follow: https://docs.devwithlando.io/config/security.html

Anyone could help?

Thank you

**Comment by pirog** [comment] 2019-02-20 13:56
@davideprevosto what command are you actually running to whitelist the cert and what does your `~/.lando/certs` directory look like?

**Comment by davideprevosto** [comment] 2019-02-20 15:24
@pirog I did run:

sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/.lando/certs/test.pem

The actual situation is:

- website runs without any alert on SSL
- padlock is RED (https://snag.gy/m7wcDM.jpg)
- certificates is valid (https://snag.gy/dCut3H.jpg) o_O

I did empty all browser cache... I don't understand.

Padlock is RED and Certificates seems valid.

**Comment by pirog** [comment] 2019-02-20 15:29
If you are getting reports that the certificate is valid eg https://snag.gy/dCut3H.jpg then this is almost for sure not an issue with something in Lando and likely an issue elsewhere. 

That said, no idea where elsewhere is ;)

**Comment by pirog** [comment] 2019-02-20 21:32
@davideprevosto so i did a bit of research here and i think the issue is that you arent allowed to have a wildcard ca cert for a top level domain. Further, `test` is a restricted top level namespace so its probably better to try something else.

When i chance the lando `domain` to `test` i get no dice, but `test.me` is fine so i think the restriction here is you cant use a tld with landos `domain` setting and expect the CAs to work correctly. I'm going to update the docs to indicate this and then close this out

**Comment by pirog** [comment] 2019-02-20 21:53
Relevant and updates docs
https://docs.devwithlando.io/config/proxy.html#configuration
https://docs.devwithlando.io/config/security.html#trusting-the-ca

**Closed by pirog** 2019-02-20 21:53 UTC
Labels: task
