### ISSUE TITLE
Investigate Mutagen option 

### ISSUE THREAD

**Issue by pirog** [lando/lando#2354] opened 2020-06-08 13:08 UTC
Docker Desktop Edge has a new Mutagen file sharing mechanism:
https://docs.docker.com/docker-for-mac/mutagen-caching/

Anyone assigned this issue (or anyone else for that matter) should try it out if interested and provide their feedback. In particular it would be good to know:

1. How did you get it working?
2. What were the performance improvements eg `lando drush cr` took 23 seconds without it and 3 seconds with it?
3. How could/should this be implemented in Lando when the time comes

When all feedback is in it would also be great to spin up a blog post and/or guide so other people can benefit before we get it baked into Lando itself

**Comment by pirog** [comment] 2020-06-27 20:05
I was able to play around with this a bit, it's very very similar to our kalabox/syncthing integration from wayyy back. Relevant notes are:

1. Definitely _feels_ more stable than `syncthing` however:
2. Expectedly there are delays between when a file shows up on the other side. This is most pronounced when adding many files eg `npm install` or when moving a large file eg after `lando db-export`. This likely will cause _many_ race conditions in Lando
3. As of right now anything `:delegated` gets synced via mutagen, so other mounts you dont want to sync probably need to be moved to `:cached`
4. I felt like i was going a lot of docker restarts and lando rebuilds before things were in a good state. Felt like things were hanging a bunch, presumably while things were syncing.
5. Definitely very very fast when its working

**Comment by tylersatre** [comment] 2020-06-28 21:22
I've been using Docker Edge 2.3.1.0 since shortly after it was released with no issues.  It has definitely been much faster, the most noticeable improve has been with a Laravel app.

I attempted to upgrade to Docker Edge 2.3.2.0 but ran into issues getting started with that.  When I attempted to do a `lando rebuild` it ran into some issues during the process.  Here's a sample error:

`ERROR: for lelocal_node_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for node  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Creating lelocal_appserver_1 ... 
Creating lelocal_database_1  ... 
Creating lelocal_node_1      ... 
Creating lelocal_appserver_nginx_1 ... 
Creating lelocal_cache_1           ... 

ERROR: for lelocal_appserver_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lelocal_database_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lelocal_cache_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lelocal_appserver_nginx_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lelocal_node_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for database  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for cache  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appserver_nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for node  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
    at /snapshot/lando/build/cli/lib/engine.js
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.start (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:
`

I tried with Laravel and Wordpress and ran into the issue in both places.  I've yet to dive a little deeper on it, had to just roll back docker versions so I could get the work done, but plan to investigate it a bit more.

**Comment by pirog** [comment] 2020-06-29 11:53
@tylersatre try out the `3.0.7` release. I was able to get that to work _decently_ out of the box with `2.3.2.0` (looks like they pulled that release?) 

The biggest problem i ran into was anything that required Lando wait for a sync to complete eg exporting a database and then immediately importing it ended up being a problem either in experience or in lando erroring because it expected something that wasnt there. There is an ongoing discussion about this specific concern over at the end of https://github.com/docker/for-mac/issues/1592

**Comment by tylersatre** [comment] 2020-06-29 14:55
@pirog It looks like `2.3.2.0` is back up, I had checked first thing this morning and saw it was down but as of about an hour ago it was there again.  Things are working great with the lando `3.0.7` release, thanks for the tip!

I read through (part of) [docker/for-mac#1592](https://github.com/docker/for-mac/issues/1592) about potential syncing issues.  I just went through downloading a large DB file (1500 MB) and it took about a minute till the sync status went back to `Ready` (2019 Macbook Pro with SSD).

Until it's decided how it's going to be handled on the docker side of things, it seems like it will be a bit till a stable implementation can be done in lando.  I'm assuming that there will be a programmatic way to check sync status and that will need to be added between steps.

**Comment by pirog** [comment] 2020-06-29 19:25
@tylersatre yah i saw that too. so i just updated `master` based on the current activity in the docker issues queue about this. `master` and going forward the default behavior of lando is to NOT use mutagen by default until we deem its stable enough to use as a default. However, you can tell lando to use it on a per-service basis with the following lando config:

```yaml
services:
  appserver|orotherservice:
    app_mount: delegated
```

and then i _think_ a `lando rebuild` will be needed.

**Comment by mikemilano** [comment] 2020-07-01 19:33
I've experienced 2 issues with this on OSX:

## Unable to build the first time after installation of 2.3.2.0

The first build after installing edge fails. Subsequent builds work.

**Steps to reproduce:**
- Start on the stable version of Docker
- Install the edge version
- Assure `app_mount: delegated`  is set in `.lando.yml`
- `lando rebuild -y`

**Result:**
- Notification warning during build (OSX style in upper right) `Waiting for file synchronization`
- `Read timed out` error when building the `projectname_appserver_1`

**Resolution:**
- A subsequent `lando rebuild -y` worked successfully
- I thought it might be triggered the first time you add `app_mount: delegated`, but I did not see the error again after commenting that out, rebuilding, then un-commenting and rebuilding again, so it only appears on the first build after installing edge.

## Syncing fails after some use

About an hour into heavy development syncing seemed to stop. It would not work again even after a rebuild.

**Steps to reproduce:**
- Assure `app_mount: delegated`  is set in `.lando.yml`
- `lando rebuild -y`

**Result:**
- Syncing works for a short while but then it seems to stop
- Browser reloads for the PHP app I was working with became slow (5+ seconds more than normal) 
- Pages viewed in the browser did not reflect the changes I made in code

**Troubleshooting:**
- `lando rebuild -y` did not resolve this. The files were in sync after the rebuild but subsequent changes did not appear in the browser. I ruled out caching by `lando ssh -s appserver` and viewing the files directly. Ssh to the service was also slow.
- exiting the ssh session was also very slow

**Resolution:**
- I had to disable by commenting out `app_mount: delegated` and `lando rebuild -y`

**Comment by pirog** [comment] 2020-07-01 19:36
Ahhh interesting @mikemilano, i think `docker-compose `has basically a 60 second timeout, so if you have a lot of files to sync on that first launch i think it hits that limit. If docker is not going to handle that somehow we could consider bumping the limit in Lando directly: 
https://docs.docker.com/compose/reference/envvars/#compose_http_timeout

**Comment by pirog** [comment] 2020-07-14 14:53
For people following this who are interested in living on the wild side, the forthcoming `3.0.8` will have some mutagen handling if you want to also run the Docker Desktop Edge release which we dont officially support so YMMV
https://docs.lando.dev/config/performance.html

**Comment by hkirsman** [comment] 2020-07-15 08:24
Yes pls add the default timeout. I'm also getting timeouts sometimes with Mutagen.

**Comment by hkirsman** [comment] 2020-07-15 10:11
The main Drupal 8 site I was working every day didn't have any problem but another started complaining. I first upped the value 2x to 120, then 180 and finally 200 when it didn't time out anymore. One hypothesis could be that timeout increases with the amount of mounts or Landos started.

**Comment by pirog** [comment] 2020-07-15 10:51
In 3.0.8 we bumped the default to 300 seconds

**Closed** 2020-07-31 12:59 UTC

**Comment by pirog** [comment] 2020-09-24 14:12
Sadly docker has removed mutagen support for now, so we are also removing for now

**Comment by tylersatre** [comment] 2020-09-24 14:48
> Sadly docker has removed mutagen support for now, so we are also removing for now

I was sad to see it go... in looking through some alternative options to speed up IO I dug around a bit in the lando docs and a little in the code but couldn't figure this out.  Is there any way to add `volumes` to my `.lando.yml` that would result in a top level `volumes` in the `docker-compose.yml` that gets created?

I want to test out NFS, but from what I've looked at it seems that the volume needs to be specified in the top level `volumes` with config options then the name set there is used in the service level `volumes`.  I know the latter can be done using `overrides`, but not sure if it is even possible to create the volume config.
