### ISSUE TITLE
Secure HTTPS URL redirects to HTTP when trailing slash is missing

### ISSUE THREAD

**Issue by wturnerharris** [lando/lando#423] opened 2017-10-19 22:49 UTC
Bug Report
==========

**System Setup**
What is your lando version and operating system?
v3.0.0-beta.17 on Mac OS X: 10.12.6

*Lando Config*

```yml
name: barrel-base-theme
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: barrel-base-theme
  id: 55e6ab01-ecf0-4b68-ad70-7238f9af2320
```

**Tell us about the command you were running**
1. Run `lando start` on any lando project running WordPress
2. Visit the secure HTTPS URL provided after starting lando.
3. Go to /wp-admin on the same URL
4. Get redirected to HTTP

In some cases, if a random port was chosen for HTTP, assuming something like apache or node is already occupying that port, then the site reflects a 500 error because instead of redirecting to HTTP's mapped port, it redirects to the HTTP URL without the port.

I've found that adding a trailing slash to the request fixes this issue, but in some cases this is unavoidable such as submitting a form with gravity forms, or logging in.

**Comment by pirog** [comment] 2017-11-16 05:50
@wturnerharris i can confirm that this happens on `beta.24`. What's weird is if you visit `wp-login.php` then the protocol stays as HTTPS so i'm wondering if there is some logic in the `wp-admin` handler that trips this. 

I'm not a WP expert but going to research and see if i can find something here.

**Comment by pirog** [comment] 2017-11-16 05:56
@wturnerharris it looks like pantheon sets the schema this way by default 

```php
    /** A couple extra tweaks to help things run well on Pantheon. **/
    if (isset($_SERVER['HTTP_HOST'])) {
        // HTTP is still the default scheme for now. 
        $scheme = 'http';
        // If we have detected that the end use is HTTPS, make sure we pass that
        // through here, so <img> tags and the like don't generate mixed-mode
        // content warnings.
        if (isset($_SERVER['HTTP_USER_AGENT_HTTPS']) && $_SERVER['HTTP_USER_AGENT_HTTPS'] == 'ON') {
            $scheme = 'https';
        }
        define('WP_HOME', $scheme . '://' . $_SERVER['HTTP_HOST']);
        define('WP_SITEURL', $scheme . '://' . $_SERVER['HTTP_HOST']);
    }
```

Lando sets `HTTPS` but it looks like maybe we should set `HTTP_USER_AGENT_HTTPS` as well

**Comment by pirog** [comment] 2017-11-16 06:14
@wturnerharris ok yup. that is exactly the issue. this should be fixed in the next release!

**Closed** 2017-11-16 06:21 UTC
Labels: bug
