### ISSUE TITLE
Hangs forever on `lando start` after update

### ISSUE THREAD

**Issue by Shelob9** [lando/lando#502] opened 2017-11-15 18:24 UTC
Bug Report
==========

*steps to reproduce*
* Upgrade from beta 22 to beta 24
* `lando start`

**Tell us about your setup**

What is your lando version and operating system?

Example: v3.0.0-beta24 on Ubuntu 16.04 LTS*

```yml
name: calderaformscom
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: calderaformscom
  id: aeda3c02-2d1e-4216-941a-e36821dffa17
  xdebug: true
  redis: true

```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

I  ran `lando poweroff` then I installed beta 24 using Ubuntu's software installer.

Console output when running `lando start`

```bash

landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting calderaformscom_database_1 ... 
Starting calderaformscom_index_1 ... 
Starting calderaformscom_database_1
Starting calderaformscom_index_1
Starting calderaformscom_cache_1 ... 
Starting calderaformscom_index_1 ... done
Recreating calderaformscom_appserver_1 ... 
Recreating calderaformscom_appserver_1 ... done
Recreating calderaformscom_nginx_1 ... 
Recreating calderaformscom_nginx_1 ... done
Recreating calderaformscom_edge_1 ... 
Recreating calderaformscom_edge_1 ... done
Recreating calderaformscom_edge_ssl_1 ... 
Recreating calderaformscom_edge_ssl_1 ... done
Pantheon pre-run scripting
Whitelisting /user/.lando/keys/pantheon/calderaformscom/index.crt
Clearing symlinks in /etc/ssl/certs...done.
Updating certificates in /etc/ssl/certs... 175 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
Replacing debian:ACCVRAIZ1.pem
Replacing debian:ACEDICOM_Root.pem
Replacing debian:AC_Raíz_Certicámara_S.A..pem
Replacing debian:Actalis_Authentication_Root_CA.pem
Replacing debian:AddTrust_External_Root.pem
Replacing debian:AddTrust_Low-Value_Services_Root.pem
Replacing debian:AddTrust_Public_Services_Root.pem
Replacing debian:AddTrust_Qualified_Certificates_Root.pem
Replacing debian:AffirmTrust_Commercial.pem
Replacing debian:AffirmTrust_Networking.pem
Replacing debian:AffirmTrust_Premium.pem
Replacing debian:AffirmTrust_Premium_ECC.pem
Replacing debian:ApplicationCA_-_Japanese_Government.pem
Replacing debian:Atos_TrustedRoot_2011.pem
Replacing debian:Autoridad_de_Certificacion_Firmaprofesional_CIF_A62634068.pem
Replacing debian:Baltimore_CyberTrust_Root.pem
Replacing debian:Buypass_Class_2_CA_1.pem
Replacing debian:Buypass_Class_2_Root_CA.pem
Replacing debian:Buypass_Class_3_Root_CA.pem
Replacing debian:CA_Disig_Root_R1.pem
Replacing debian:CA_Disig_Root_R2.pem
Replacing debian:CA_WoSign_ECC_Root.pem
Replacing debian:CFCA_EV_ROOT.pem
Replacing debian:CNNIC_ROOT.pem
Replacing debian:COMODO_Certification_Authority.pem
Replacing debian:COMODO_ECC_Certification_Authority.pem
Replacing debian:COMODO_RSA_Certification_Authority.pem
Replacing debian:Camerfirma_Chambers_of_Commerce_Root.pem
Replacing debian:Camerfirma_Global_Chambersign_Root.pem
Replacing debian:Certification_Authority_of_WoSign_G2.pem
Replacing debian:Certigna.pem
Replacing debian:Certinomis_-_Autorité_Racine.pem
Replacing debian:Certinomis_-_Root_CA.pem
Replacing debian:Certplus_Class_2_Primary_CA.pem
Replacing debian:Certplus_Root_CA_G1.pem
Replacing debian:Certplus_Root_CA_G2.pem
Replacing debian:Certum_Root_CA.pem
Replacing debian:Certum_Trusted_Network_CA.pem
Replacing debian:Certum_Trusted_Network_CA_2.pem
Replacing debian:Chambers_of_Commerce_Root_-_2008.pem
Replacing debian:China_Internet_Network_Information_Center_EV_Certificates_Root.pem
Replacing debian:ComSign_CA.pem
Replacing debian:Comodo_AAA_Services_root.pem
Replacing debian:Comodo_Secure_Services_root.pem
Replacing debian:Comodo_Trusted_Services_root.pem
Replacing debian:Cybertrust_Global_Root.pem
Replacing debian:D-TRUST_Root_Class_3_CA_2_2009.pem
Replacing debian:D-TRUST_Root_Class_3_CA_2_EV_2009.pem
Replacing debian:DST_ACES_CA_X6.pem
Replacing debian:DST_Root_CA_X3.pem
Replacing debian:Deutsche_Telekom_Root_CA_2.pem
Replacing debian:DigiCert_Assured_ID_Root_CA.pem
Replacing debian:DigiCert_Assured_ID_Root_G2.pem
Replacing debian:DigiCert_Assured_ID_Root_G3.pem
Replacing debian:DigiCert_Global_Root_CA.pem
Replacing debian:DigiCert_Global_Root_G2.pem
Replacing debian:DigiCert_Global_Root_G3.pem
Replacing debian:DigiCert_High_Assurance_EV_Root_CA.pem
Replacing debian:DigiCert_Trusted_Root_G4.pem
Replacing debian:E-Tugra_Certification_Authority.pem
Replacing debian:EBG_Elektronik_Sertifika_Hizmet_Sağlayıcısı.pem
Replacing debian:EC-ACC.pem
Replacing debian:EE_Certification_Centre_Root_CA.pem
Replacing debian:Entrust.net_Premium_2048_Secure_Server_CA.pem
Replacing debian:Entrust_Root_Certification_Authority.pem
Replacing debian:Entrust_Root_Certification_Authority_-_EC1.pem
Replacing debian:Entrust_Root_Certification_Authority_-_G2.pem
Replacing debian:Equifax_Secure_CA.pem
Replacing debian:Equifax_Secure_Global_eBusiness_CA.pem
Replacing debian:Equifax_Secure_eBusiness_CA_1.pem
Replacing debian:GeoTrust_Global_CA.pem
Replacing debian:GeoTrust_Global_CA_2.pem
Replacing debian:GeoTrust_Primary_Certification_Authority.pem
Replacing debian:GeoTrust_Primary_Certification_Authority_-_G2.pem
Replacing debian:GeoTrust_Primary_Certification_Authority_-_G3.pem
Replacing debian:GeoTrust_Universal_CA.pem
Replacing debian:GeoTrust_Universal_CA_2.pem
Replacing debian:GlobalSign_ECC_Root_CA_-_R4.pem
Replacing debian:GlobalSign_ECC_Root_CA_-_R5.pem
Replacing debian:GlobalSign_Root_CA.pem
Replacing debian:GlobalSign_Root_CA_-_R2.pem
Replacing debian:GlobalSign_Root_CA_-_R3.pem
Replacing debian:Global_Chambersign_Root_-_2008.pem
Replacing debian:Go_Daddy_Class_2_CA.pem
Replacing debian:Go_Daddy_Root_Certificate_Authority_-_G2.pem
Replacing debian:Hellenic_Academic_and_Research_Institutions_ECC_RootCA_2015.pem
Replacing debian:Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem
Replacing debian:Hellenic_Academic_and_Research_Institutions_RootCA_2015.pem
Replacing debian:Hongkong_Post_Root_CA_1.pem
Replacing debian:IGC_A.pem
Replacing debian:ISRG_Root_X1.pem
Replacing debian:IdenTrust_Commercial_Root_CA_1.pem
Replacing debian:IdenTrust_Public_Sector_Root_CA_1.pem
Replacing debian:Izenpe.com.pem
Replacing debian:Juur-SK.pem
Replacing debian:Microsec_e-Szigno_Root_CA.pem
Replacing debian:Microsec_e-Szigno_Root_CA_2009.pem
Replacing debian:NetLock_Arany_=Class_Gold=_Főtanúsítvány.pem
Replacing debian:Network_Solutions_Certificate_Authority.pem
Replacing debian:OISTE_WISeKey_Global_Root_GA_CA.pem
Replacing debian:OISTE_WISeKey_Global_Root_GB_CA.pem
Replacing debian:OpenTrust_Root_CA_G1.pem
Replacing debian:OpenTrust_Root_CA_G2.pem
Replacing debian:OpenTrust_Root_CA_G3.pem
Replacing debian:PSCProcert.pem
Replacing debian:QuoVadis_Root_CA.pem
Replacing debian:QuoVadis_Root_CA_1_G3.pem
Replacing debian:QuoVadis_Root_CA_2.pem
Replacing debian:QuoVadis_Root_CA_2_G3.pem
Replacing debian:QuoVadis_Root_CA_3.pem
Replacing debian:QuoVadis_Root_CA_3_G3.pem
Replacing debian:RSA_Security_2048_v3.pem
Replacing debian:Root_CA_Generalitat_Valenciana.pem
Replacing debian:S-TRUST_Authentication_and_Encryption_Root_CA_2005_PN.pem
Replacing debian:S-TRUST_Universal_Root_CA.pem
Replacing debian:SZAFIR_ROOT_CA2.pem
Replacing debian:SecureSign_RootCA11.pem
Replacing debian:SecureTrust_CA.pem
Replacing debian:Secure_Global_CA.pem
Replacing debian:Security_Communication_EV_RootCA1.pem
Replacing debian:Security_Communication_RootCA2.pem
Replacing debian:Security_Communication_Root_CA.pem
Replacing debian:Sonera_Class_2_Root_CA.pem
Replacing debian:Staat_der_Nederlanden_EV_Root_CA.pem
Replacing debian:Staat_der_Nederlanden_Root_CA_-_G2.pem
Replacing debian:Staat_der_Nederlanden_Root_CA_-_G3.pem
Replacing debian:Starfield_Class_2_CA.pem
Replacing debian:Starfield_Root_Certificate_Authority_-_G2.pem
Replacing debian:Starfield_Services_Root_Certificate_Authority_-_G2.pem
Replacing debian:StartCom_Certification_Authority.pem
Replacing debian:StartCom_Certification_Authority_2.pem
Replacing debian:StartCom_Certification_Authority_G2.pem
Replacing debian:SwissSign_Gold_CA_-_G2.pem
Replacing debian:SwissSign_Platinum_CA_-_G2.pem
Replacing debian:SwissSign_Silver_CA_-_G2.pem
Replacing debian:Swisscom_Root_CA_1.pem
Replacing debian:Swisscom_Root_CA_2.pem
Replacing debian:Swisscom_Root_EV_CA_2.pem
Replacing debian:T-TeleSec_GlobalRoot_Class_2.pem
Replacing debian:T-TeleSec_GlobalRoot_Class_3.pem
Replacing debian:TC_TrustCenter_Class_3_CA_II.pem
Replacing debian:TURKTRUST_Certificate_Services_Provider_Root_2007.pem
Replacing debian:TWCA_Global_Root_CA.pem
Replacing debian:TWCA_Root_Certification_Authority.pem
Replacing debian:Taiwan_GRCA.pem
Replacing debian:TeliaSonera_Root_CA_v1.pem
Replacing debian:Trustis_FPS_Root_CA.pem
Replacing debian:TÜBİTAK_UEKAE_Kök_Sertifika_Hizmet_Sağlayıcısı_-_Sürüm_3.pem
Replacing debian:TÜRKTRUST_Elektronik_Sertifika_Hizmet_Sağlayıcısı_H5.pem
Replacing debian:TÜRKTRUST_Elektronik_Sertifika_Hizmet_Sağlayıcısı_H6.pem
Replacing debian:USERTrust_ECC_Certification_Authority.pem
Replacing debian:USERTrust_RSA_Certification_Authority.pem
Replacing debian:UTN_USERFirst_Email_Root_CA.pem
Replacing debian:UTN_USERFirst_Hardware_Root_CA.pem
Replacing debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G4.pem
Replacing debian:VeriSign_Class_3_Public_Primary_Certification_Authority_-_G5.pem
Replacing debian:VeriSign_Universal_Root_Certification_Authority.pem
Replacing debian:Verisign_Class_1_Public_Primary_Certification_Authority.pem
Replacing debian:Verisign_Class_1_Public_Primary_Certification_Authority_-_G3.pem
Replacing debian:Verisign_Class_2_Public_Primary_Certification_Authority_-_G2.pem
Replacing debian:Verisign_Class_2_Public_Primary_Certification_Authority_-_G3.pem
Replacing debian:Verisign_Class_3_Public_Primary_Certification_Authority.pem
Replacing debian:Verisign_Class_3_Public_Primary_Certification_Authority_-_G3.pem
Replacing debian:Visa_eCommerce_Root.pem
Replacing debian:WellsSecure_Public_Root_Certificate_Authority.pem
Replacing debian:WoSign.pem
Replacing debian:WoSign_China.pem
Replacing debian:XRamp_Global_CA_Root.pem
Replacing debian:certSIGN_ROOT_CA.pem
Replacing debian:ePKI_Root_Certification_Authority.pem
Replacing debian:thawte_Primary_Root_CA.pem
Replacing debian:thawte_Primary_Root_CA_-_G2.pem
Replacing debian:thawte_Primary_Root_CA_-_G3.pem
Replacing debian:spi-cacert-2008.pem
Adding debian:index.pem
done.
done.
Setting up client key /user/.lando/keys/pantheon/calderaformscom/index.pem
```

Then it hangs for ever.

**Tell us generally about your bug**
This happened after updating form beta 22 to beta 24. I never had beta 23, so probably unrelated to #497

**Comment by pirog** [comment] 2017-11-15 20:43
@Shelob9 guessing there are other steps to reproduce this since this seems to work for me and i havent heard anything from anyone else. 

Might be worth trying to recreate the pantheon app.

**Comment by bsnodgrass** [comment] 2017-11-15 22:48
Lando won't start for me after upgrade from beta23 to beta24 MacOS 10.12.6

$ lando start shorr
error:  Error: EISDIR: illegal operation on a directory, open '/Users/bobsnodgrass/.lando/services/config/nginx/fastcgi_params'

$ ls -la /Users/bobsnodgrass/.lando/services/config/nginx/fastcgi_params
total 0
drwxr-xr-x@ 2 bobsnodgrass  staff   68 Nov 15 10:27 .
drwxr-xr-x@ 6 bobsnodgrass  staff  204 Nov 15 10:27 ..
Bobs-MBP-2:~ bobsnodgrass$ ls -la /Users/bobsnodgrass/.lando/services/config/nginx/
total 24
drwxr-xr-x@  6 bobsnodgrass  staff   204 Nov 15 10:27 .
drwxr-xr-x@ 13 bobsnodgrass  staff   442 Nov  9 19:57 ..
-rw-r--r--@  1 bobsnodgrass  staff  1197 Nov 15 16:16 default-ssl.conf
-rw-r--r--@  1 bobsnodgrass  staff  1086 Nov 15 16:16 default.conf
drwxr-xr-x@  2 bobsnodgrass  staff    68 Nov 15 10:27 fastcgi_params
-rw-r--r--@  1 bobsnodgrass  staff   729 Nov 15 16:16 nginx.conf

**Comment by pirog** [comment] 2017-11-15 22:55
@bsnodgrass
https://github.com/lando/lando/issues/497

**Comment by Shelob9** [comment] 2017-11-15 23:35
Recreating the app worked. Feel free to close.

**Comment by pirog** [comment] 2017-11-16 02:38
@Shelob9 will do. Wish i had a better idea why this happened so we could take action if applicable but i think its probably more efficient to close this and wait for someone else to report it.

**Closed by pirog** 2017-11-16 02:38 UTC
