### ISSUE TITLE
Memory issues on composer require or update

### ISSUE THREAD

**Issue by chrisarcherhydrant** [lando/lando#732] opened 2018-02-28 20:16 UTC
Hi,

I'm using the latest version of Lando with a Drupal 8 project when ever I try and run `lando composer update` I keep getting:

`PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 100

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 100

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.zend_mm_heap corrupted`

My `.lando.yml` file is:

`name: custom-drupal8
recipe: drupal8
config:
  webroot: web
  php: '5.6'
`

**Comment by nicrodgers** [comment] 2018-03-06 08:53
Hi Chris.

You need to increase the size of the PHP memory limit. You can do that by providing a php.ini within your project that sets the override (and any others you might want), then pointing the lando config at it.

For example, create the file php.ini in your app root, and put in it:
`memory_limit = -1`

Then add this to your .lando.yml:
```
config:
  conf:
    php: php.ini
```

Then a **lando rebuild** should pick up the changes.

**Comment by pirog** [comment] 2018-03-15 07:47
@dustinleblanc similar situation to #704. Is this something we should consider setting higher so that it "just works" for people?

**Comment by akalata** [comment] 2018-03-15 20:06
@nicrodgers your instructions didn't seem to work for me. I'm still getting the memory errors from Composer, and the result of `lando php -r "echo ini_get('memory_limit').PHP_EOL;"` hasn't changed from 512M.

**Comment by dustinleblanc** [comment] 2018-03-15 23:04
@pirog so we have people who hit their container's memory limit all the time on the platform, even if they don't exceed the memory limit for a PHP process. 

For Lando being a dev solution, I am usually +1 on ripping out all the stops to make development more fun. For Pantheon recipes, we do tend to tout the 'production mirror' thing which makes me want to clamp down on the memory limit.

Can we maybe find a way to set no limit to memory on CLI ops and keep a strict limit for php-fpm while its running a web process? We set some params different for CLI ops on the platform so I imagine this has to be possible...

The other thing is that Docker I think does like 2gb of ram by default for your entire docker VM, so folks may start throwing SIGKILL errors no matter what they do unless they up that limit in docker's config

**Comment by pirog** [comment] 2018-03-15 23:10
@dustinleblanc yeah im def on board with `-1` for CLI ops and i'm guessing we could easily just build our composer command behind the scenes to set that eg something like `php -d memory_limit=-1 composer`

**Comment by pirog** [comment] 2018-03-20 08:27
@dustinleblanc so reopening this because we probably want to figure out the best way to set this on the `php` level so all cli tools eg `drush`, `composer`, `artisan` all have INFINITE MEMORY!

**Comment by com2** [comment] 2018-08-08 09:03
OK, this is still unfixed in v3.0.0-beta.47, right? So what is the present work around to have drush, drupal (console) and composer run with infinite memory?

**Comment by alphex** [comment] 2018-08-10 02:31
following

**Comment by dustinleblanc** [comment] 2018-08-17 14:41
So I was looking at this today, trying to get some ideas on how to get ALLTHEMEMORY for Composer, interestingly according to https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors Composer already defaults to 1.5G. I did however find that its not super hard to just give us ALLTHEMEMORY for CLI activities a la https://serverfault.com/questions/807763/how-can-i-create-separate-configuration-files-for-php-cli-and-php-fpm-on-an-ar

Testing it out, might be able to get this into our next release

**Comment by wturrell** [comment] 2018-08-27 11:56
A couple of people (@akalata, @com2) have said @nicrodgers method of raising PHP's `memory_limit` isn't work.  Right now it does seem to work in the browser and CLI for me (lando v3.0.0-beta.47).

**However:** note I'm yet to run into the original problem with composer running out of memory.

Make sure you have this exact syntax (your `webroot`, server (`via`) and `php` version may of course vary):

```
config:
  webroot: web
  via: nginx
  php: '7.1'
  conf:
    php: php.ini
```

i.e. it needs to be nested with the rest of your .lando.yml config and you need a 'php' key.

> www-data@f0b3d1f9ac96:/app$ php -i | grep 'memory'
> memory_limit => -1 => -1

**Comment by hkirsman** [comment] 2018-09-14 07:38
I fixed it by adding alternative command. I hope it's fixed in Lando someday:

    services:
      appserver:
        overrides:
          services:
            volumes:
              - $LANDO_APP_ROOT_BIND/.lando/composer.sh:/helpers/composer.sh

    tooling:
      # Fix memory limit issues for composer by using composer2 command instead.
      # I wasn't able to use composer here to override the original command.
      composer2:
        service: appserver
        description: Run composer commands
        cmd: /helpers/composer.sh

**Comment by dustinleblanc** [comment] 2018-09-14 13:19
@hkirsman it should be someday, I ran into a little bit of an issue with my fix but it should be possible to fix permanently. The way we load ini files doesn't immediately allow us to load a separate cli ini file, but that is the goal

**Comment by anacona16** [comment] 2018-09-19 16:15
@hkirsman what is the content of _helpers/composer.sh_?

**Comment by tanc** [comment] 2018-09-20 11:36
Having a separate cli ini would also solve #1140

**Comment by com2** [comment] 2018-09-22 08:05
I use lando v3.0.0-beta.47 and docker 18.06.1-ce (linux/amd64) and I can confirm that what @wturrell  did works here too. 

I noticed however that you have to do "lando stop" and "lando start" to make it work. Changes in .lando.yml are picked up with "lando start" only , but for changes in php.ini you need "lando stop". This behaviour might have influenced our evaluation.

**Comment by dustinleblanc** [comment] 2018-09-24 13:11
@tanc even more reason to go that route, I think it's a good idea overall, @pirog @serundeputy what do you dudes think?

**Comment by serundeputy** [comment] 2018-09-24 14:06
re: 1140 I can understand that (and in general am for that), but we've also had issues posted in the lando queue asking how to allow xdebug on drush commands, so we don't want to break things for those users (https://github.com/lando/lando/issues/874) 

so like many things it is not necessarily simple to implement this

that doesn't mean we can't or shouldn't think about it; just need to consider multiple use cases.

**Comment by dustinleblanc** [comment] 2018-09-24 14:43
I am all for getting separate ini files going as soon as we can and I agree simply cloning the existing file is a quicker win. I started working on this and it just turns out how we handle ini files in the code wasn't what I expected. We do some renaming/appending magic to make overrides work intuitively which somewhat interferes with the often default PHP system in some distros of having the two files. I'd love to get us there, its just more code changes than I anticipated. I am also not sure if it would impact the easy overridability and I definitely don't want to mess that up

**Comment by tanc** [comment] 2018-10-03 17:33
I just hit the composer memory limit issue and can confirm the solution wturrell posted worked for me

**Comment by lhridley** [comment] 2018-10-03 19:55
Running Lando version 3.0.0-rc.1, trying to install a project using a Pantheon recipe, with the following .lando.yml file:
```
name: example-app
recipe: pantheon
config:
  framework: drupal
  site: example-app
  id: 0
  php: '7.2'
  conf:
    php: php.ini
  webroot: web
  via: nginx
```

php.ini file (which is in my project root where the .lando.yml file is located):
```
memory_limit = -1
```

The php.ini file is being ignored, and composer is hitting a memory limit of 1610612736 consistently.

Docker is configured to use 4 CPUs and 8G ram on a MacBook Pro 15" with 16G and a quad core processor running Sierra 10.12.6

This is my first attempt to use Lando, trying to help a client troubleshoot a local dev environment, so far not having any success.

**Comment by anacona16** [comment] 2018-10-04 02:18
I solved using this config:

```yml
tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - php -dmemory_limit=-1 /usr/local/bin/composer
```

**Comment by pirog** [comment] 2018-10-04 09:21
chiming in here @tanc @serundeputy @dustinleblanc  

i think the fundamental thing that makes this harder than it should be is that there is no "easy" way, at least that i know of, to define a separate php.ini that loads *just* for cli ops in the underlying docker images that we are using. 

At first i thought we might be able to do something like @anacona16 has done in comment above (and maybe that isnt a bad stop gap measure) but ideally we find something that "just works" for all php cli ops. 

Another possible alternative we could explore is thinking about this from the other direction, eg set the default php config to be for the cli and then have apache and fpm set up so the load in needed "server" overrides eg a more restrictive memory limit, xdebug config, etc

**Comment by pirog** [comment] 2018-10-04 19:57
I don’t think anyone is debating that

**Comment by rjbain** [comment] 2018-11-02 18:37
@pirog @dustinleblanc Is there any workaround while using the pantheon recipe? None of the solutions on this page seem to be working for me. This is what my `.lando.yml` looks like now:

```
name: XXXXXX
recipe: pantheon
config:
  webroot: .
  via: nginx
  php: '7.0'
  conf:
    php: conf/php.ini
  framework: drupal
  site: XXXXXX
  id: XXXXXX

tooling:
  composer:
    service: appserver
    description: Run composer commands
    cmd:
      - php -dmemory_limit=-1 /usr/local/bin/composer
```
This is for a D7 site and using drush for features is causing `Error: Allowed memory size of 536870912 bytes exhausted`. Thanks!

**Comment by rjbain** [comment] 2018-11-02 19:39
Thanks, to @dustinleblanc I was able to get drush working by changing this section:

```
tooling:
  drush:
    service: appserver
    description: Run composer commands
    cmd: php -d memory_limit=-1 /usr/local/bin/drush
```

**Comment by pirog** [comment] 2018-11-03 02:50
@dustinleblanc @serundeputy i dont think there has been much evolution in thought on this since https://github.com/lando/lando/issues/732#issuecomment-426947161 so i think it might be worth just hardcoding our php tools like the workarounds here eg with `php -d memory_limit=-1 /path/to/my/thing` for now until we have a more "complete" solution.

We could either do this directly with each internal php tool or we could provide some sort of internal tooling key like `_php_tool: true` which would know to prepend the `php -d memory_limit=-1` to the command

**Comment by gitressa** [comment] 2018-12-03 17:31
I just got hit by this while exporting huge text-files, and @nicrodgers [tip](https://github.com/lando/lando/issues/732#issuecomment-370708535) followed by `lando rebuild` worked perfectly. But having a general `memory_limit=-1` would be even better.

**Comment by bob-hinrichs** [comment] 2019-01-18 17:08
Tried everything in this thread, thank you.  Running lando v3.0.0-rc.1 cli and web server both run out of memory and are always 512.  I am attempting D8 migration tasks and am getting nowhere.  Thanks for the work on this.

**Comment by dustinleblanc** [comment] 2019-01-19 16:01
@pirog I went ahead and tried to implement the `cmd: 'php -d memory_limit=-1 COMMAND'` pattern and we have an issue where php can't infer the input script by passing the command name. I tried doing `php -d memory_limit=-1 $(which COMMAND)` which doesn't work either, still investigating how I can pass the fully qualified script path. I also noticed here: http://php.net/manual/en/configuration.file.php That we can load the memory limit into an env variable, so perhaps it would be another method to do like: `PHP_MEMORY_LIMIT=-1 drush` or something like that...

**Comment by dustinleblanc** [comment] 2019-01-22 14:05
@Mar2zz makes sense, 7.x uses _significantly_ less memory to accomplish the same tasks.

**Closed** 2019-01-30 23:53 UTC
Labels: improvement

**Comment by dcorb** [comment] 2019-02-11 23:30
`lando php -d memory_limit=-1 /usr/local/bin/composer require drupal/simplesamlphp_auth` worked for me

**Comment by ccharlton** [comment] 2019-03-20 23:18
https://github.com/lando/lando/issues/732#issuecomment-462538322 helped. Thanks!

**Comment by grantkruger** [comment] 2019-04-25 20:50
Thanks dcorb. Helped it to work on Lando. It then worked on Pantheon even though in theory they have the same memory limit as the one that failed.

**Comment by ccharlton** [comment] 2019-05-03 22:50
This global composer addon has helped quite a bit: https://github.com/hirak/prestissimo

Quick install: `lando composer global require hirak/prestissimo`

**Comment by dustinleblanc** [comment] 2019-05-06 13:02
At some point we were installing this automatically @ccharlton but I think something might have gone funky with it :thinking:

**Comment by ccharlton** [comment] 2019-05-09 22:58
@grantkruger some example CI scripts have memory for Composer/PHP set to `memory_limit=-1`, which makes sense.

**Comment by grantkruger** [comment] 2019-07-01 17:57
@ccharlton hirak/prestissimo does not solve it. Also my CI script does not have memory limit settings for composer, so behaviors are different. Still having to use the approach at [comment 732](https://github.com/lando/lando/issues/732#issuecomment-462538322).

**Comment by ccharlton** [comment] 2019-07-02 17:55
@all, please note 'prestissimo' is not _the_ solution; it is an addon that helps cut down a lot of Composer processing time.

**Comment by Mugane** [comment] 2022-05-18 15:10
For us, the solution was to set the memory limit in the command line. Other methods did not take.
`COMPOSER_MEMORY_LIMIT=-1 composer update mirrors`
or in Dockerfile:
`RUN COMPOSER_MEMORY_LIMIT=-1 composer update mirrors`
