### ISSUE TITLE
Localhost is not working, but lndo.site is working.

### ISSUE THREAD

**Issue by idpokute** [lando/lando#695] opened 2018-02-09 22:08 UTC
Bug Report
==========

**Tell us about your setup**
v3.0.0-beta.36 on Ubuntu 16.04

**Tell us about your `.lando.yml`**
# WordPress recipe
name: wordpress

# Start with the default WordPress recipe
recipe: wordpress

# Configure the WordPress recipe
config:

  # See: https://wordpress.org/about/requirements/

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by WordPress.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in WordPress so YMMV.
  #
  # See: https://wordpress.org/about/requirements/
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.0'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://wordpress.org/about/requirements/
  #
  via: nginx

  # Optionally specify the location of the webroot relative to your approot.
  #
  # If ommitted this will be your approot itself.
  #
  webroot: web

  # Optionally specify the database type, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #
  # If ommitted this will default to the latest mysql. You can additionally provide
  # a version with `type:version` but you will need to consult the documentation
  # for the correct DB service to see what versions are available
  #
  # see: https://wordpress.org/about/requirements/
  #
  database: mysql

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use "sane defaults" for your recipe type
  conf:

    # For more information on setting these files check out the documentation
    # and examples
    #
    # Docs: https://docs.devwithlando.io/services/php.html
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
    server: wordpress2.conf
    # php: config/php.ini

    # For more information on setting these files check out the documentation
    # and examples for the relevant services:
    #
    # MySQL: https://docs.devwithlando.io/services/mysql.html
    # MariaDB: https://docs.devwithlando.io/services/mariadb.html
    # PostGres: https://docs.devwithlando.io/services/postgres.html
    #
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
# database: config/mysql

wordpress2.conf
# WordPress single site rules.
# Designed to be included in any server {} block.

# Upstream to abstract backend connection(s) for php
upstream php {
  server fpm:9000;
}

server {

  listen 80 default_server;
  listen 443 ssl;

  server_name appserver;

  ssl_certificate           /certs/cert.crt;
  ssl_certificate_key       /certs/cert.key;
  ssl_verify_client         off;

  port_in_redirect off;
  client_max_body_size 100M;

  ## Your only path reference.
  root ${LANDO_WEBROOT};

  ## This should be in your http block and if it is, it's not needed here.
  index index.php;

  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }

  location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
  }

  location / {
    # This is cool because no php is touched for static content.
    # include the "?$args" part so non-default permalinks doesn't break when using query string
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_TRANSLATED $document_root$fastcgi_script_name;
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_pass php;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
    expires max;
    log_not_found off;
  }
}

**Tell us about the error you got**
localhost returns 404 page not found

**Tell us generally about your bug**
I run the following commands

lando.dev init 
select wordpress
lando.dev start

Above the command gives me 4 urls; but only two http & https://wordpress.lndo.site are working.
any url related to localhost are not working. it shows '404 page not found'

 NAME        wordpress                              
 LOCATION    /home/sehui/project/lando/wpblacksmith 
 SERVICES    appserver, nginx, database             
 NGINX URLS  https://localhost:32780                
             http://localhost:32781                 
             http://wordpress.lndo.site             
             https://wordpress.lndo.site

**Comment by dustinleblanc** [comment] 2018-02-22 03:35
@idpokute I am having a hard time reading this bug report. I do see that at the top of the report you have beta 36 which is a release we pulled because of issues. I am going to go ahead and close this now, if you could cleanup the issue report above to more succinctly represent the issue and reproduce it in beta 35 we'll definitely consider adding to to this sprint if we can reproduce. Thanks!

**Closed by dustinleblanc** 2018-02-22 03:35 UTC
