### ISSUE TITLE
Has the memcached setup changed in recent versions of Lando or the Lando Docker image?

### ISSUE THREAD

**Issue by tylerssn** [lando/lando#686] opened 2018-02-05 01:40 UTC
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? ** v3.0.0-beta.35 on MacOS 10.13.2

**Service Override (Referenced in Lando YML below):** `mage-app/lando-magento1-php:7.0`

```ini
auto_prepend_file="/app/magentoPhpPrepend.php"

; Magento specific
realpath_cache_size = 32k
realpath_cache_ttl = 7200
max_execution_time = 18000
max_input_time = 90
memory_limit = 1024M
default_socket_timeout = 90
pdo_mysql.cache_size = 2000
output_buffering = 4096

; Dev Cache
opcache.enable=0

; Allow $_ENV to be populated - not recommended for production use
variables_ordser = "EGPCS"

error_reporting = E_ALL & ~E_NOTICE

sendmail_path = '/usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"'
```

```
FROM devwithlando/php:7.0-fpm

RUN apt-get update && apt-get -yqq install zlib1g-dev libicu-dev g++
RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-enable intl

RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini
```

**Lando YML:**

```yml
  name: mag-app-1
  proxy:
    nginx:
      - mage.lndo.site
      - cdn.mage.lndo.site
      - media.mage.lndo.site
    mailhog:
      - mail.mage.lndo.site
    solr:
      - solr.lndo.site:8983
  services:
    appserver:
      type: php:7.0
      overrides:
        services:
          image: mage-app/lando-magento1-php:7.0
      via: nginx
      ssl: true
      webroot: web
      #xdebug conflicts with blackfire
      xdebug: false
      config:
        server: dev/lando/config/nginx/default.conf
        conf: dev/lando/config/php/php.ini
      composer:
        overtrue/phplint: '*'
      build:
        - "cd $LANDO_MOUNT && composer install || true"
        - "bash $LANDO_MOUNT/dev/lando/deploy/init.sh"
      extras:
        - "apt-get -yqq update"
        - "apt-get -yqq install pv"
    magento-db:
      type: mysql:5.6
      portforward: true
      creds:
        user: ${LANDO_MAGENTO_DB_USER}
        password: ${LANDO_MAGENTO_DB_PASS}
        database: ${LANDO_MAGENTO_DB_NAME}
    wordpress-db:
      type: mysql:5.6
      portforward: true
      creds:
        user: ${LANDO_WORDPRESS_DB_USER}
        password: ${LANDO_WORDPRESS_DB_PASS}
        database: ${LANDO_WORDPRESS_DB_NAME}
    redis-cache:
      type: redis
      portforward: true
    redis-session:
      type: redis
      portforward: true
    solr:
      type: solr:3.6
      portforward: true
      config:
        # It's important to note that Platform.sh uses a slightly different
        # config found in .platform/solr/conf-magento
        conf: lib/Apache/Solr/conf
    mailhog:
      type: mailhog
      hogfrom:
        - appserver
      portforward: 1026
  tooling:
    phplint:
      service: appserver
    magerun:
      service: appserver
      user: www-data
      cmd:
        - magerun
    composer:
      service: appserver
      description: Run composer commands
      cmd:
        - composer
        - --ansi
    php:
      service: appserver
    mysql:
      user: root
      service: database
      description: Drop into a MySQL shell
    'magento:init':
      service: appserver
      user: root
      needs:
        - wordpress-db
        - magento-db
      description: Get current platformy branch db dump and import into local DB
      cmd:
        - ./dev/lando/deploy/init.sh
```
 

**About the Issue:**

I've noticed in the last week across multiple projects the PHP is hesitent to reflect file changes within the application. I could see the file changes within the container but the updates would not reflect within the application until a `lando restart` or until I changed the filename case (using a Mac, so case isn't critical). 

After executing `pecl uninstall memcached` within my Lando container the issue went away. 

Has the Memcached setup changed in recent versions of the Lando Docker image? Is there a new Lando config default that sets memcached to enabled by default? This has never been an issue before and our Lando config has not changed recently.

**Comment by pirog** [comment] 2018-02-05 16:07
@tylerssn lando hasnt changed re: memcache. not sure about the docker image but im guessing not. they usually just ship with defaults by design.

also, it doesn't look like you even have a memcache container so id surprised if memcache was the issue. does look like you are using redis though which could explain what you are seeing. ultimately lando is only gets your code synced into the container, we don't try to configure much of anything beyond that.

**Comment by tylerssn** [comment] 2018-02-05 17:36
@pirog - thanks, as always, for your prompt responses.

You're correct, we aren't _intentionally_ enabling Memcache. Before I submitted this issue, I took a look at the Lando docs to see when and how Memcache services can be implemented and it looks like, by default, Lando does not take any action to enable the services.

The image we are using on the `appserver` container extends Lando's PHP 7.0-FPM image. As a precaution, I disabled that override and rebuilt the container. Once it was built, `lando ssh -c"php -i | grep memcache"` showed that Memcache had been enabled.

As far as redis is concerned, I've executed `flush db` on both instances for safe measure but it does not refresh the content. 

It could be a coincidence (?) but **the application only acknowledges file changes after uninstalling Memcache**.

I am using the following to do so:

```YML
  extras:
    ...
      - rm /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini
      - pecl uninstall memcached
```

**Comment by tylerssn** [comment] 2018-02-05 17:49
Just an update so nobody spends too much time pondering Memcache. I had a co-worker, who is using the same Lando setup and whose PHP app is updating files as they are changed, test to see if Memcache was enabled and _*it is *_. 

Though uninstalling Memcache resolves the issue for me, Memcache does not create an issue for him.

I'm going to assume that though the files are updated within the container whatever triggers Memcache to refresh content (file timestamp?) is not  doing so.

**Comment by pirog** [comment] 2018-02-05 17:53
@tylerssn AFAIK there is a big difference between enabling the memcached php extension (which is what we are actually talking about here) and implementing it eg actually getting your php application to use memcached, which would require an actual memcached service being spun up somewhere.

AFAIK the memached php extension just gives you access to the Memcached class (http://php.net/manual/en/book.memcached.php) so having it enabled shouldn't in and of itself do anything unless your application is using it in someway.

**Comment by pirog** [comment] 2018-02-05 17:58
Also worth pointing out that ALL of our php images have the memcached extension enabled by default so if that was the root cause im guessing we'd be hearing more about it by now.

**Comment by dustinleblanc** [comment] 2018-02-06 23:20
@tylerssn I am going to go ahead and close this for now. To actually use Memcache you need to spin up a Memcache service. Let us know if you have further questions, thanks!

**Closed by dustinleblanc** 2018-02-06 23:20 UTC
Labels: can not replicate
