### ISSUE TITLE
Lando rebuild <database> is not awesome on drupal 7

### ISSUE THREAD

**Issue by jraviotta** [lando/lando#843] opened 2018-03-30 20:07 UTC
When configuring/debugging .lando.yml for a drupal 7 site, `lando rebuild` doesn't yield consistent results.

issues:

1. `<root>/sites/default/settings.php` is persistent and not updated with subsequent installs, nor mentioned in docs.
1.1 deletion of `settings.php` should be documented or handled by lando perhaps as a `settings.lando.php` 
2. `lando rebuild` is wonky when db credentials are updated in `.lando.yml`
2.1 Not sure what the problem is

<details>
<summary>lando config</summary><p>

```
{
  "servicesConfigDir": "C:\\Users\\jraviotta\\.lando\\services\\config",
  "servicesHelpersDir": "C:\\Users\\jraviotta\\.lando\\services\\helpers",
  "loadPassphraseProtectedKeys": false,
  "proxy": "ON",
  "proxyDomain": "lndo.site",
  "proxyDash": "58086",
  "proxyHttpPort": "80",
  "proxyHttpsPort": "443",
  "proxyHttpFallbacks": [
    "8000",
    "8080",
    "8888",
    "8008"
  ],
  "proxyHttpsFallbacks": [
    "444",
    "4433",
    "4444",
    "4443"
  ],
  "composeBin": "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe",
  "composeVersion": "3.2",
  "containerGlobalEnv": {
    "COLUMNS": 256,
    "LANDO": "ON",
    "LANDO_CONFIG_DIR": "C:\\Users\\jraviotta\\.lando",
    "LANDO_APP_NAME": "MySite",
    "LANDO_APP_ROOT": "C:\\Users\\jraviotta\\Documents\\Repos\\Drupal\\4pillars",
    "LANDO_APP_ROOT_BIND": "C:\\Users\\jraviotta\\Documents\\Repos\\Drupal\\4pillars",
    "LANDO_HOST_OS": "win32",
    "LANDO_HOST_UID": "1000",
    "LANDO_HOST_GID": "1000",
    "LANDO_HOST_IP": "host.docker.internal",
    "LANDO_WEBROOT_USER": "www-data",
    "LANDO_WEBROOT_GROUP": "www-data",
    "LANDO_WEBROOT_UID": "33",
    "LANDO_WEBROOT_GID": "33"
  },
  "dockerBin": "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.exe",
  "dockerBinDir": "C:\\Program Files\\Docker\\Docker\\resources\\bin",
  "engineConfig": {
    "host": "127.0.0.1",
    "socketPath": "//./pipe/docker_engine"
  },
  "engineHost": "127.0.0.1",
  "engineId": "1000",
  "engineGid": "1000",
  "engineScriptsDir": "C:\\Users\\jraviotta\\.lando\\engine\\scripts",
  "appConfigFilename": ".lando.yml",
  "appsRoot": "C:\\Users\\jraviotta\\Lando",
  "appRegistry": "registry",
  "configFilename": "config.yml",
  "configSources": [
    "C:\\snapshot\\lando\\build\\cli\\config.yml",
    "C:\\Users\\jraviotta\\.lando\\config.yml"
  ],
  "env": {
    "ACLOCAL_PATH": "C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal",
    "ADSK_CLM_WPAD_PROXY_CHECK": "FALSE",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\jraviotta\\AppData\\Roaming",
    "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
    "COMPOSE_CONVERT_WINDOWS_PATHS": "1",
    "COMPUTERNAME": "CAVEBEAST",
    "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
    "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
    "ChocolateyLastPathUpdate": "Mon Mar 12 09:04:33 2018",
    "ChocolateyToolsLocation": "C:\\tools",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "DISPLAY": "needs-to-be-defined",
    "EXEPATH": "C:\\Program Files\\Git\\bin",
    "FLEXLM_TIMEOUT": "1500000",
    "HISTCONTROL": "ignoredups",
    "HISTIGNORE": "[ \t]*:&:[fb]g:exit:ls",
    "HOME": "C:\\Users\\jraviotta",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\jraviotta",
    "HOSTNAME": "CaveBeast",
    "INFOPATH": "C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info",
    "JAVA_HOME": "C:\\Program Files (x86)\\Java\\jdk1.8.0_144",
    "LANDO": "ON",
    "LANDO_APP_NAME": "MySite",
    "LANDO_APP_ROOT": "C:\\Users\\jraviotta\\Documents\\Repos\\Drupal\\4pillars",
    "LANDO_APP_ROOT_BIND": "C:\\Users\\jraviotta\\Documents\\Repos\\Drupal\\4pillars",
    "LANDO_CONFIG_DIR": "C:\\Users\\jraviotta\\.lando",
    "LANDO_ENGINE_CONF": "C:\\Users\\jraviotta\\.lando",
    "LANDO_ENGINE_GID": "1000",
    "LANDO_ENGINE_HOME": "C:\\Users\\jraviotta",
    "LANDO_ENGINE_ID": "1000",
    "LANDO_ENGINE_IP": "tcp://127.0.0.1",
    "LANDO_ENGINE_REMOTE_IP": "host.docker.internal",
    "LANDO_ENGINE_SCRIPTS_DIR": "C:\\Users\\jraviotta\\.lando\\engine\\scripts",
    "LANDO_HOST_GID": "1000",
    "LANDO_HOST_IP": "host.docker.internal",
    "LANDO_HOST_OS": "win32",
    "LANDO_HOST_UID": "1000",
    "LANDO_INSTALL_PATH": "C:\\Program Files\\Lando",
    "LANDO_WEBROOT_GID": "33",
    "LANDO_WEBROOT_GROUP": "www-data",
    "LANDO_WEBROOT_UID": "33",
    "LANDO_WEBROOT_USER": "www-data",
    "LANG": "en_US.UTF-8",
    "LOCALAPPDATA": "C:\\Users\\jraviotta\\AppData\\Local",
    "LOGONSERVER": "\\\\CAVEBEAST",
    "MANPATH": "C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man",
    "MSYSTEM": "MINGW64",
    "NUMBER_OF_PROCESSORS": "8",
    "OMP_NUM_THREADS": "8",
    "OS": "Windows_NT",
    "OneDrive": "C:\\Users\\jraviotta\\OneDrive",
    "PATH": "C:\\Users\\jraviotta\\.composer\\vendor\\bin;C:\\Users\\jraviotta\\bin\\;C:\\Users\\jraviotta\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Pr
ogram Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\jraviotta\\bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\tools\\ruby25\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\W
bem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\HashiCorp\\Vagrant\\bin;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\OpenSSH-Win64;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\
Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\ProgramData\\chocoportable\\bin;C:\\Program Files\\nodejs;C:\\tools\\php72;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\jraviotta\\Anaconda3;C:\\Users\\jraviotta\\Anaconda3\\L
ibrary\\mingw-w64\\bin;C:\\Users\\jraviotta\\Anaconda3\\Library\\usr\\bin;C:\\Users\\jraviotta\\Anaconda3\\Library\\bin;C:\\Users\\jraviotta\\Anaconda3\\Scripts;C:\\Users\\jraviotta\\AppData\\Local\\Box\\Box Edit;C:\\Users\\jraviotta\\AppData\\Local\\Microsoft\
\WindowsApps;C:\\Users\\jraviotta\\AppData\\Roaming\\npm;C:\\Users\\jraviotta\\AppData\\Roaming\\Composer\\vendor\\bin;C:\\Program Files\\Lando\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW",
    "PKG_CONFIG_PATH": "C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig",
    "PLINK_PROTOCOL": "ssh",
    "PRINTER": "Brother MFC-9130CW Printer",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 45 Stepping 7, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "2d07",
    "PROGRAMFILES": "C:\\Program Files",
    "PS1": "\\[\\e[0;32m\\]\\t \\[\\e[0;33m\\]\\w\\[\\033[m\\]\\[\\e[0;31m\\]$(__git_ps1)\\[\\e[0;37m\\]\\012$ ",
    "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PUBLIC": "C:\\Users\\Public",
    "PWD": "C:/Users/jraviotta/Documents/Repos/Drupal/4pillars",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "SESSIONNAME": "Console",
    "SHELL": "C:\\Program Files\\Git\\usr\\bin\\bash",
    "SHLVL": "1",
    "SSH_ASKPASS": "C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass",
    "SYSTEMDRIVE": "C:",
    "SYSTEMROOT": "C:\\WINDOWS",
    "TEMP": "C:\\Users\\JRAVIO~1\\AppData\\Local\\Temp",
    "TERM": "cygwin",
    "TMP": "C:\\Users\\JRAVIO~1\\AppData\\Local\\Temp",
    "TMPDIR": "C:\\Users\\JRAVIO~1\\AppData\\Local\\Temp",
    "USERDOMAIN": "CAVEBEAST",
    "USERDOMAIN_ROAMINGPROFILE": "CAVEBEAST",
    "USERNAME": "jraviotta",
    "USERPROFILE": "C:\\Users\\jraviotta",
    "WINDIR": "C:\\WINDOWS",
    "_": "C:/Program Files/Lando/bin/lando"
  },
  "home": "C:\\Users\\jraviotta",
  "logLevel": "debug",
  "logLevelConsole": "warn",
  "node": "v8.9.0",
  "os": {
    "type": "Windows_NT",
    "platform": "win32",
    "release": "10.0.16299",
    "arch": "x64"
  },
  "pluginDirs": [
    "C:\\snapshot\\lando\\build\\cli",
    "C:\\Users\\jraviotta\\.lando"
  ],
  "product": "lando",
  "process": "node",
  "srcRoot": "C:\\snapshot\\lando\\build\\cli",
  "userConfRoot": "C:\\Users\\jraviotta\\.lando",
  "envPrefix": "LANDO",
  "logDir": "C:\\Users\\jraviotta\\.lando\\logs",
  "mode": "cli",
  "version": "3.0.0-beta.39",
  "plugins": [
    "lando-app",
    "lando-core",
    "lando-engine",
    "lando-events",
    "lando-init",
    "lando-networking",
    "lando-proxy",
    "lando-recipes",
    "lando-services",
    "lando-tooling"
  ],
  "stats": [
    {
      "report": true,
      "url": "https://metrics.devwithlando.io"
    }
  ],
  "installPath": "C:\\Program Files\\Lando",
  "id": "0b5d4ad731753856d445cf733f5ad813d8e569ee",
  "proxyHttpPorts": [
    "80",
    "8000",
    "8080",
    "8888",
    "8008"
  ],
  "proxyHttpsPorts": [
    "443",
    "444",
    "4433",
    "4444",
    "4443"
  ]
}
```
</p></details>

# 1st install
Drupal core + `.lando.yml`
```
name: MySite
recipe: drupal7
config:
  webroot: .
  via: nginx
```

`lando start` yields 

<details><summary> `lando info` </summary><p>

```
lando info
{
  "appserver": {
    "urls": [],
    "type": "php",
    "version": "7.0",
    "hostnames": [
      "appserver",
      "appserver.MySite.internal"
    ],
    "via": "nginx",
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "nginx": {
    "urls": [],
    "type": "nginx",
    "version": "latest",
    "hostnames": [
      "nginx",
      "nginx.MySite.internal"
    ],
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "database": {
    "urls": [],
    "type": "mysql",
    "version": "latest",
    "hostnames": [
      "database",
      "database.MySite.internal"
    ],
    "creds": {
      "user": "drupal7",
      "password": "drupal7",
      "database": "drupal7"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\mysql"
    }
  }
}
```

</details></p>

Install drupal with `lando drush site-install --y --db-url=mysql://drupal7:drupal7@database:3306/drupal7` and get

<details><summary>a settings.php with</summary><p>

```
$ sed -n 247,261p sites/default/settings.php
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'drupal7',
      'username' => 'drupal7',
      'password' => 'drupal7',
      'host' => 'database',
      'port' => '3306',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```
</details></p>

Now I want to tinker with the defaults
# 2nd install
Drupal core + new `.lando.yml` + `setting.php` 'cause I didn't think to delete it
```
name: MySite
recipe: drupal7
config:
  webroot: .
  via: nginx

services:
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
```

<details><summary> `lando rebuild` yields (as expected)</summary><p>

```
$ lando info
{
  "appserver": {
    "urls": [],
    "type": "php",
    "version": "7.0",
    "hostnames": [
      "appserver",
      "appserver.MySite.internal"
    ],
    "via": "nginx",
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "nginx": {
    "urls": [],
    "type": "nginx",
    "version": "latest",
    "hostnames": [
      "nginx",
      "nginx.MySite.internal"
    ],
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "database": {
    "urls": [],
    "type": "mysql",
    "version": "latest",
    "hostnames": [
      "database",
      "database.MySite.internal"
    ],
    "creds": {
      "user": "drupal",
      "password": "drupal",
      "database": "drupal"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\mysql"
    }
  }
}
```
</details></p>

<details><summary> but install fails (because settings.php still exists with incorrect database array)</summary><p>

```
lando drush site-install --y --db-url=mysql://drupal:drupal@database:3306/drupal
You are about to CREATE the 'drupal' database. Do you want to continue? (y/n): y
Failed to create database: ERROR 1045 (28000): Access denied for user &#039;drupal&#039;@&#039;mysite_appserver_1.mysite_default&#039; (using password: YES)                                                                                         [error]
15:24:36 ~/Documents/Repos/Drupal/4pillars (lando-win)
$ sed -n 247,261p sites/default/settings.php
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'drupal7',
      'username' => 'drupal7',
      'password' => 'drupal7',
      'host' => 'database',
      'port' => '3306',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);
```
</details></p>

# 3rd install 
 Drupal core + same-new  `.lando.yml` - `settings.php` 'cause I was smart and deleted it
```
name: MySite
recipe: drupal7
config:
  webroot: .
  via: nginx

services:
  database:
    creds:
      user: drupal
      password: drupal
      database: drupal
```

<details><summary> `lando rebuild` yields (as expected)</summary><p>

```
$ lando info
{
  "appserver": {
    "urls": [],
    "type": "php",
    "version": "7.0",
    "hostnames": [
      "appserver",
      "appserver.MySite.internal"
    ],
    "via": "nginx",
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "nginx": {
    "urls": [],
    "type": "nginx",
    "version": "latest",
    "hostnames": [
      "nginx",
      "nginx.MySite.internal"
    ],
    "webroot": ".",
    "config": {
      "server": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\drupal7.conf",
      "conf": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\php.ini"
    }
  },
  "database": {
    "urls": [],
    "type": "mysql",
    "version": "latest",
    "hostnames": [
      "database",
      "database.MySite.internal"
    ],
    "creds": {
      "user": "drupal",
      "password": "drupal",
      "database": "drupal"
    },
    "internal_connection": {
      "host": "database",
      "port": 3306
    },
    "external_connection": {
      "host": "localhost",
      "port": true
    },
    "config": {
      "confd": "C:\\Users\\jraviotta\\.lando\\services\\config\\drupal7\\mysql"
    }
  }
}
```
</details></p>

I would expect `lando drush site-install --y --db-url=mysql://drupal:drupal@database:3306/drupal` to work, 
<details><summary>but instead I get</summary><p>

```
Recreating mysite_database_1  ... done
Recreating mysite_appserver_1 ... done
You are about to create a /app/sites/default/settings.php file and CREATE the 'drupal' database. Do you want to continue? (y/n): y
Failed to create database: ERROR 1045 (28000): Access denied for user &#039;drupal&#039;@&#039;mysite_appserver_1.mysite_default&#039; (using password: YES)
```
</details></p>

and a bonus `settings.php` file with no database array
```
$ sed -n 247,248p sites/default/settings.php
$databases = array();
```

# 4th install
the only correct method to edit the  `.lando.yml` file is to delete `settings.php` and `lando destroy` + `lando start`.

**Comment by RobinHoutevelts** [comment] 2018-04-01 20:48
Well, create a PR and make it <sup>(more)</sup> awesome? ( Beat you to it #854 😎 )

Nowhere in the [docs](https://docs.devwithlando.io/tutorials/drupal7.html#recipe) it says you can change the default database credentials when using a recipe.

It's just something that happens to work, but all `lando *` commands will still use the credentials made by the recipe.

The easiest fix is to add a `.env` file next to your `.lando.yml` file and have it contain your credentials:

```
DB_USER=drupal
DB_PASSWORD=drupal
DB_NAME=drupal
```

Then run `lando restart` so those environment variables are being picked up.

`lando *` commands should then work.

**Comment by pirog** [comment] 2018-04-02 00:21
@jraviotta number 1 here is outside the scope of lando. The purpose of lando is to make it easy to setup the services and tools you need to develop your app. By corollary this means we can often set up a bunch of helpers on our end to help with the application set up itself (eg envvars, utility commands, build steps etc) however lando itself, and by design, is not going to setup, manage or otherwise get involved in your application's code. The exceptions to this are rare cases (eg pantheon) where there are definitive guidelines and expectations in place where we can reliably get the user as far down the road as possible.

Number 2 is definitely something that we need to do better on our end but i am going to close this in favor of @RobinHoutevelts' #853 which has a pretty excellent breakdown of one of the major underlying problems with the way we are currently handling custom db cred settings.

**Closed by pirog** 2018-04-02 00:21 UTC

**Comment by jraviotta** [comment] 2018-04-02 02:04
Thanks @RobinHoutevelts & @pirog. After reading #853 I can see where I got off track. I made the assumption that all configuration changes in .lando.yml would be used. However, the only modifications supported in the Drupal 7 recipe, for example, are:

> You can also manually configure the .lando.yml file to switch php or drush versions, toggle between apache and nginx, activate xdebug, choose a database type and version, set a custom webroot locaton and use your own configuration files.

I am willing to create a PR that is more explicit about how to customize configuration if that is helpful. The suggestion to add a .env file would be useful in the docs.

**Comment by pirog** [comment] 2018-04-02 02:15
@jraviotta i *think* there is already pretty extensive documentation in place that describes how to do this:
https://docs.devwithlando.io/config/lando.html
https://docs.devwithlando.io/tutorials/setup-additional-services.html
https://docs.devwithlando.io/config/services.html

i could see adding some more explicit linkage to those materials but i think they more or less cover the meat of things. What did you have in mind beyond what is already there?

i 100% think we need to document the "must `lando destroy && lando start` to get db creds setup correctly" (eg the action item implied from your point 2) but im going to add that into the scope of #853

**Comment by jraviotta** [comment] 2018-04-02 04:21
I agree that the documentation is extensive. What would have been helpful to me, is some more obvious clarification of what code blocks are examples and what code blocks are a specifications. Having spent hours in the Docker-compose documentation, I have become accustomed to code blocks that are non-exhaustive usage examples of what is available. I was looking at `lando.yml` as a substitute for a docker-compose.yml file. Despite the similarities, this assumption is incorrect and lando does not call out options that are set and ignored. EG the database `creds` block. A recipe is not necessarily extendable by adding details to the `.lando.yml`. I was expecting that whatever services were used in the recipe could be extended by my modifications in `.lando.yml`. 

From https://docs.devwithlando.io/config/lando.html

> The top-level config option customizes specific aspects of a recipe. For example, the Drupal 8 recipe allows specifying the PHP version, the webserver, and even how to install drush:

You might consider adding. "Finer-grained modifications can be made in the services, tooling, proxies and events blocks as described below. 

Then under FINE-GRAINED CONFIGURATION
>Recipes are simply common development use-cases, composed of different combinations of services, tooling, proxies, and events. Each of these is a first-class citizens in Lando, with its own top-level configuration options. They can run alongside recipes or raw compose setups to extend functionality.

Might be amended with, "However, not all options for services, tooling, and proxies used in a recipe can be configured in `lando.yml` Supported options for each recipe can be found by __________. To modify additional options, _____________."

I know the point of the recipe is to obfuscate the complexity, but I personally like having a complete .yml that I can modify as necessary.  The docs refer to examples, but as I found, `lando.yml` doesn't necessarily support everything. 

EG: Assume a drupal 8 recipe:
`lando.yml` gives me
>.file to switch php or drush versions, toggle between apache and nginx, activate xdebug or drupal console, choose a database type and version, set a custom webroot locaton and use your own configuration files.

I also have env variables but no clear path to setting them. (a paragraph on a .env would we useful)

And I have text about the services 
> For more information on setting these files check out the documentation and examples for the relevant services:
     MySQL: https://docs.devwithlando.io/services/mysql.html

Which describes a complete database app rather than the database service block that should be used in `.lando.yml`.

Perhaps my inexperience or demand for customizability is the prime culprit. If these comments are spurious, feel free to ignore. I appreciate that balancing flexibility with simplicity is difficult and Lando is certainly attempting to tackle a very difficult problem. Even the most clear documentation won't change the fact that this stuff is really hard.

**Comment by pirog** [comment] 2018-04-02 04:39
@jraviotta feel free to submit a PR with some more explicit language in the areas you feel most need it. I'm guessing those would be accepted unless they are just inaccurate. 

A couple quick hits for you:

1. There is a complete doc on settings envvars: https://docs.devwithlando.io/config/env.html
2. I hear you on the complete db app vs just the db services block. These blocks are includes directly from our examples folder https://github.com/lando/lando/tree/master/examples (also a good place to learn how things work if you are more hands on) and the primary consideration there is just maintainability eg sharing one lando.yml for both an example and docs is way easier.
3. Everything that you get in a recipe is configurable down to the docker-compose level but not all of those things are available in the "config" block. you get them by doing lower level stuff inside of "services" and then within "overrides" inside of each service. I recognize that you need to do some digging in various parts of the docs and examples to get a sense of how that all works.
