### ISSUE TITLE
lando composer doesn't work

### ISSUE THREAD

**Issue by thasmo** [lando/lando#2076] opened 2020-03-21 20:59 UTC
`lando composer` only prints a message. Actually, any composer command just prints a message and doesn't run the desired action.

**Tell us about your setup**
* Windows 10
* Lando *3.0.0-aft.2*

**Tell us about your `.lando.yml`**
```yml
name: project
recipe: lemp
config:
  webroot: public
  database: mysql
  php: 7.2
  xdebug: true
  config:
    php: php.ini
tooling:
  npm:
    service: node
  node:
    service: node
services:
  node:
    type: node:10
    globals:
      npm: 6
    run:
      - npm ci
```

**Tell us about the command you were running**
```bash
lando destroy -y
lando start
lando composer install
```

**Tell us about the error you got**
```bash
> lando composer install
You must set up the project dependencies using `composer install`
See https://getcomposer.org/download/ for instructions on installing Composer
```

**Tell us generally about your bug**
```bash
1. Updated to AFT 2.
2. Destroyed the lando project.
2. Deleted all Docker images/containers.
3. Restarted Docker for Windows.
4. Ran the commands above.
```

**Comment by pirog** [comment] 2020-03-21 21:25
@thasmo i _think_ this is probably caused by the same thing over on #2052, try out the resolution in this comment https://github.com/docker/for-win/issues/6016#issuecomment-600285551 and let us know if that works. im _guessing_ we may need to roll another release later today that downgrades the windows docker to 2.2.0.3

**Comment by thasmo** [comment] 2020-03-21 23:07
@pirog, thanks! Workarounds and the patched Docker build didn't help, but downgrading to 2.2.0.3 seems to have fixed this issue.

**Comment by pirog** [comment] 2020-03-21 23:15
Awesome! Thanks for the feedback @thasmo, def seems like a reroll with 2.2.0.3 for windows is in order

**Comment by pirog** [comment] 2020-03-23 14:13
@thasmo going to close this out. The latest Lando 3.0.0-rrc.1 ships with Docker 2.2.0.3 so people should update to that and make sure they are on that version of Docker.

**Closed by pirog** 2020-03-23 14:13 UTC
Labels: bug

**Comment by plato1123** [comment] 2020-11-23 02:31
I was having a similar problem, where lando composer commands would seemingly run without error but wouldn't actually do anything.  I'm on Win10/wsl2 with lando 3.0.15 and docker 19.03.13.  I had tried lando rebuild, lando destroy etc but still "lando composer install" or lando composer require drupal/focal_point would return a message acting like they were working but not actually make any changes.  Finally restarted my whole computer, came back, lando rebuild, and everything was working again.  

Weird that lando would fail without any hint of error.

**Comment by Cardozo1w** [comment] 2024-03-07 16:54
Hi @MatthiasBrodelet, have you found the problem? I have the same issue

**Comment by Cardozo1w** [comment] 2024-03-08 17:35
I fixed it installing composer manually, I install php using brew, after that, install composer following the documentation, run `composer install` without lando, execute `lando rebuild -y`, and dependencies will be installed normally

**Comment by BaluErtl** [comment] 2024-03-12 20:52
In case someone also has similar issue: https://github.com/composer/composer/issues/7499#issuecomment-1992552499
