### ISSUE TITLE
Database is not running

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#1486] opened 2019-02-22 06:19 UTC
Hello,
On Lando RC12, after a lando start, I've a message as Database is not ruuning then:
`lando logs -s database` says `database_1   | Welcome to the Bitnami mariadb container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
database_1   | Send us your feedback at containers@bitnami.com
database_1   | 
database_1   | INFO  ==> ** Starting MariaDB setup **
database_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
database_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
database_1   | INFO  ==> Initializing mariadb database...
database_1   | DEBUG ==> Custom configuration detected. Injecting...
database_1   | DEBUG ==> Ensuring expected directories/files exist...
database_1   | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
database_1   | INFO  ==> Stopping mariadb...
`

**Comment by stevep** [comment] 2019-02-22 17:39
I ran into this too after upgrading from rc1 to rc12. 

Found https://github.com/lando/lando/issues/1439

First I specified `mariadb:10.1` but that alone didn't fix it. After I destroyed and rebuilt, the database would start. Sucks to lose the data though.

**Comment by sebastienserre** [comment] 2019-02-22 17:45
Many Thanks @stevep 
So the problem isn't solved :-/
"crazy things" is I've tested the same lando.yml with 3 on 10 projects... 
2 of projects are running fine.... and the third won't.... completely not understable....

I came back to RC1, just to be able to work... I d'ont know what can I do to help solving this probllem. @pirog do you need some info to dig into this mistake ?

**Comment by pirog** [comment] 2019-02-22 17:51
From what I’ve seen so far my best guess is that this is either people not
following the update guide eg having to destroy old pre rc2 databases
before starting post rc2 ones or an upstream issue in the bitnami image.

Happy to be convinced otherwise but until we have steps to replicate it’s
not an actionable ticket or a priority for us

**Comment by markisatacomputer** [comment] 2019-02-25 19:27
I had the same issue after upgrading from rc1 to rc12 and it was caused by running out of disk space in docker.  Commands below did the trick for me but you could also increase your docker disk image size.  Note: I had to pull my db again.

```
docker system prune -y
docker image prune -y
docker volume prune -y
lando restart
lando pull --code=none --files=none
```

**Comment by cboyden** [comment] 2019-02-26 18:08
I am seeing this problem on a very basic drupal7 recipe install.
Environment: Mac OSX 10.13.6; 16GB RAM; non-superuser local account.

Steps:
------
1. Fully uninstall previous version of Lando
2. Fully uninstall Docker for Mac
3. Install Lando RC 12 and its suggested Docker version
4. Adjust Docker settings: Disk image size 128GB; 2 CPUs; 6 GB memory; 2 GB swap. (Also tested with factory settings for Docker and got same results.)
5. Set up offline development using "localhost" domain following [instructions](https://docs.devwithlando.io/guides/offline-dev.html). This is a hard requirement due to single-signon whitelisting only the localhost domain for local dev.
6. Download Drupal 7.64
7. lando init etc, see below.

Results:
-------
```
$ lando init

? From where should we get your app's codebase? current working directory
? What recipe do you want to use? drupal7
? Where is your webroot relative to the init destination? .
? What do you want to call this app? landotest

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run `lando start` to get rolling.
Check the LOCATION printed below if you are unsure where to go.

Oh... and here are some vitals:

 NAME      landotest
 LOCATION  /Users/carolineboyden/Sites/test/landotest
 RECIPE    drupal7
 DOCS      https://docs.devwithlando.io/tutorials/drupal7.html

$ lando start

Let's get this party started! Starting app..
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "landotest_default" with the default driver
Creating volume "landotest_data_appserver" with default driver
Creating volume "landotest_home_appserver" with default driver
Creating volume "landotest_data_database" with default driver
Creating volume "landotest_home_database" with default driver
Creating landotest_appserver_1 ... done
Killing landotest_appserver_1 ... done
Starting landotest_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   1317      0 --:--:-- --:--:-- --:--:--  1316
100 4580k  100 4580k    0     0  3096k      0  0:00:01  0:00:01 --:--:-- 10.8M
 Drush Version   :  8.1.18

Killing landotest_appserver_1 ... done
Starting landotest_appserver_1 ... done
Creating landotest_database_1  ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
warn: Service database is unhealthy
warn: Run "lando logs -s database"
Starting landotest_database_1 ... done
ERROR: Container 963e2fdad89e090c19de944fa57162628e0205482cc74ef22b67c097ccacd4da is not running
error: Looks like database is not running! It should be so this is a problem.
warn: Try running `lando logs -s database` to help locate the problem!

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            landotest
 LOCATION        /Users/carolineboyden/Sites/test/landotest
 SERVICES        appserver, database
 APPSERVER URLS  https://localhost:32780
                 http://localhost:32781
                 http://landotest.localhost
                 https://landotest.localhost

$ lando logs -s database

Attaching to landotest_database_1
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   |
database_1   | Welcome to the Bitnami mysql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
database_1   | Send us your feedback at containers@bitnami.com
database_1   |
database_1   | INFO  ==> ** Starting MySQL setup **
database_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
database_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
database_1   | INFO  ==> Initializing mysql database...
database_1   | DEBUG ==> Custom configuration detected. Injecting...
database_1   | /libmysql.sh: line 662: /opt/bitnami/mysql/conf/bitnami/my_custom.cnf: Permission denied
database_1   | INFO  ==> Stopping mysql...
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   |
database_1   | Welcome to the Bitnami mysql container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mysql
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mysql/issues
database_1   | Send us your feedback at containers@bitnami.com
database_1   |
database_1   | INFO  ==> ** Starting MySQL setup **
database_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
database_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
database_1   | INFO  ==> Initializing mysql database...
database_1   | DEBUG ==> Custom configuration detected. Injecting...
database_1   | /libmysql.sh: line 662: /opt/bitnami/mysql/conf/bitnami/my_custom.cnf: Permission denied
database_1   | INFO  ==> Stopping mysql...
```

**Comment by tormi** [comment] 2019-02-26 19:09
Could you paste your `.lando.yml` here?

**Comment by cboyden** [comment] 2019-02-26 19:13
```
name: landotest
recipe: drupal7
config:
  webroot: .
```

**Comment by cboyden** [comment] 2019-02-26 20:41
I think what may have solved it is deleting my ~/.lando directory (and then replacing the config.yml for offline development). Fingers crossed, this seems to be working now on RC12.

**Comment by pirog** [comment] 2019-02-26 20:46
That’s worth knowing. I’ll make a note to update the update guide to
include this consideration.

**Comment by pirog** [comment] 2019-02-27 21:56
Going to close this out for now but we've updated the update guide to include some help on this
https://docs.devwithlando.io/guides/updating-to-rc2.html#removing-lando

**Closed by pirog** 2019-02-27 21:56 UTC
Labels: bug

**Comment by sebastienserre** [comment] 2019-03-03 11:43
I've delelted `~/.lando` and then `lando destroy` install RC13
And have allways the same error:
`sebastien@sebastien-desktop:/media/projets/thivinfo/thivinfo.com$ lando logs -s database
Attaching to thivinfo_database_1
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami mariadb container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
database_1   | Send us your feedback at containers@bitnami.com
database_1   | 
database_1   | INFO  ==> ** Starting MariaDB setup **
database_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
database_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
database_1   | INFO  ==> Initializing mariadb database...
database_1   | DEBUG ==> Custom configuration detected. Injecting...
database_1   | DEBUG ==> Ensuring expected directories/files exist...
database_1   | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
database_1   | INFO  ==> Stopping mariadb...
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | 
database_1   | Welcome to the Bitnami mariadb container
database_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
database_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
database_1   | Send us your feedback at containers@bitnami.com
database_1   | 
database_1   | INFO  ==> ** Starting MariaDB setup **
database_1   | INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
database_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
database_1   | INFO  ==> Initializing mariadb database...
database_1   | DEBUG ==> Custom configuration detected. Injecting...
database_1   | DEBUG ==> Ensuring expected directories/files exist...
database_1   | mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied
database_1   | INFO  ==> Stopping mariadb...
sebastien@sebastien-desktop:/media/projets/thivinfo/thivinfo.com$ `

**Comment by sebastienserre** [comment] 2019-03-03 11:59
Hello
I allways have problem on RC13
https://gist.github.com/sebastienserre/c75eb40cf0d881aa5ba33afb2568c829

**Comment by akapivo** [comment] 2019-03-04 08:13
> I had the same issue after upgrading from rc1 to rc12 and it was caused by running out of disk space in

This worked for me. Removing the ~/.lando directory didn't (Lando v3.0.0-rc.13).
But instead of the -y flag, I used the -f flag for docker (2.0.0.3 (31259)).

**Comment by sebastienserre** [comment] 2019-03-04 08:52
@akapivo how did you use the docker flag?
I do not understand why lando is working on several projects and not on others

**Comment by akapivo** [comment] 2019-03-04 09:06
@sebastienserre 
docker system prune -f
docker image prune -f
docker volume prune -f
lando rebuild

And as mentioned by @markisatacomputer I had to reimport my database afterwards.

But if Lando is working on your other projects, I think the problem can not be the insufficient disk space on docker? I had to do some restarting before it all worked fine again. Maybe the problem arose for me because I've updated Docker and Lando at the same time?

**Comment by shabananavas** [comment] 2019-03-08 09:32
Yeah, I recently updated Docker to the latest version and today, updated Lando from beta to rc13. I'm getting the same exact issue.

**Comment by pirog** [comment] 2019-03-14 12:36
Worth pointing out... AGAIN... that destroying and recreating your app may be a necessary step and is bullet point numero uno in the update guide
https://docs.devwithlando.io/guides/updating-to-rc2.html#new-images

**Comment by flyke** [comment] 2019-11-18 09:41
I had the same problem after restarting my Windows pc (because windows update).
Waiting until database service is ready...
...
warn: Service database is unhealthy
...
ERROR: Container xxx is not running
error: Looks like database is not running! It should be so this is a problem.

This worked for me:
- right click on the Docker Desktop taskbar icon and choose settings
- Advanced: Increase the Memory (in my case, it was at around 2Gn and I increased it to 3GB)
- apply and wait until docker is fully restarted

Now when I ran:
lando poweroff; lando start
lando, including the database started without problem.
I did loose the database contents themselves by this, so I had to create a db dump from staging and import it using lando db-import db.sql

It's possible that the solution was not the memory increase per se but the restarting of Docker Desktop, not sure, but at least this worked for me.

You could also try just deleting the db image and nothing else and then do lando start so it will rebuild that. See if that works for you.
Side note:
Can be done via terminal (preferred way i guess), but i like the gui of Kitematic for Docker Desktop, so if you are a windows user and you like being able to see things and clicking things instead of doing everything in a terminal, install Kitematic, then right click on the Docker Desktop icon in taskbar -> Kitematic.
You see all your containers and can easily stop, start, restart or in this case delete specific containers.

**Comment by tormi** [comment] 2019-11-18 09:55
@flyke,

> warn: Service database is unhealthy

Usually, there is also a little helper text along with such warning which suggest you to have a look at container logs using `lando logs -s database`. And you probably would have found a more accurate `out of space` error message there ;)

**Comment by flyke** [comment] 2019-11-18 10:06
> @flyke,
> 
> > warn: Service database is unhealthy
> 
> Usually, there is also a little helper text along with such warning which suggest you to have a look at container logs using `lando logs -s database`. And you probably would have found a more accurate `out of space` error message there ;)

Hi Tormi,
Thank you for your helpful advice. In this case: I did not mention it, but I did actually check the container logs. None of them mentioned anything about 'out of space', there were no memory related messages at all in the logs. While I did not see anything useful in those logs to help me, what I could see was when I started the database container manually from within Kitematic (Docker Desktop) I could see errors in the terminal that were not in the lando database logs. These were about ssh being unable to connect or something, and unable to create a file needed for the database (sorry that i cannot be more specific, logs are gone now that the container was deleted an re created). So at first I focused on those errors thinking maybe a permission or owner or maybe windows folder permission issue, but I could not resolve that problem. But increasing memory fixed everything despite of not a single warning or log or error indicating that there was a memory issue.

**Comment by flyke** [comment] 2019-11-19 09:27
Ok, so I had this again today and managed to fix it without loosing my existing database.

This fixed it for me:
```
lando poweroff
lando rebuild -s database
lando start
```
(database being the database service name)

After this, all was working well

Above 3 lines fixed these problems/errors I was having when I started lando in my project:
```
Waiting until database service is ready...
warn: Service database is unhealthy
warn: Run "lando logs -s database"
Starting myproject_database_1 ... done
ERROR: No container found for database_1
error: Looks like database is not running! It should be so this is a problem.
warn: Try running `lando logs -s database` to help locate the problem!
```

This was the content from lando logs -s database:
```
database_1    | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1    | Running command /run.sh
database_1    | Running with exec!
database_1    |  08:35:42.48 INFO  ==> ** Starting MySQL **
database_1    | mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
database_1    | mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
database_1    | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1    | Running command /run.sh
database_1    | Running with exec!
database_1    |  08:37:18.41 INFO  ==> ** Starting MySQL **
database_1    | mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
database_1    | mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
database_1    | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1    | Running command /run.sh
database_1    | Running with exec!
database_1    |  08:38:47.44 INFO  ==> ** Starting MySQL **
database_1    | mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
database_1    | mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
database_1    | Running command /run.sh
database_1    | Running with exec!
database_1    | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1    |  08:40:23.82 INFO  ==> ** Starting MySQL **
database_1    | mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
database_1    | mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

This error I got in the terminal when manually trying to start my database container via Kitematic:
```
Another process with pid 1 is using unix socket file.
```

And these are the errors I got in the terminal when manually restarting the database container:
```
 08:38:47.44 INFO  ==> ** Starting MySQL **
mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
Running command /run.sh
Running with exec!
mkdir: cannot create directory '/etc/ssh': Permission denied
 08:40:23.82 INFO  ==> ** Starting MySQL **
mysqld: [ERROR] Could not open required defaults file: /opt/bitnami/mysql/conf/my.cnf
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

My system:
```
Windows 10 pro
Docker: version 19.03.5 - API version 1.40
Lando: version 3.0.0-rc.22
```

**Comment by faiwiz** [comment] 2020-05-20 11:58
I faced the same issue, after tried all of solutions, error was gone after upgrading the latest version of lando and docker.

**Comment by faiwiz** [comment] 2020-05-20 12:01
I faced same issue, issue was fixed just I upgrade docker and lando to latest version issue

**Comment by zyx954** [comment] 2020-06-09 07:38
> I faced same issue, issue was fixed just I upgrade docker and lando to latest version issue

This works for me. I think maybe before when I update Lando/Docker, I did not follow the correct steps (Shutdown Lando and Turn off Docker)

**Comment by rsaylor73** [comment] 2022-01-27 10:27
I increased docker storage space and that fixed it for me.
