### ISSUE TITLE
lando 3.20 rpm not starting at all

### ISSUE THREAD

**Issue by djassie** [lando/lando#3614] opened 2023-09-29 05:47 UTC
This may be some issue with package or what, 

After updating from `3.18` rpm version, lando instance is not starting. 

`Lando init` and then `lando start` is also crashing

Ways to reproduce:
1. RPM based OS (Rocky Linux)
2. install Docker, Docker as non-root
3. `lando init `
4. `lando start`

**Comment by rockschtar** [comment] 2023-09-29 17:31
I can confirm this, i get this error on every command:

`ERROR ==> Error: spawn /home/sh/.lando/bin/docker-compose-v2.21.0 EACCES `

**Comment by brsowers** [comment] 2023-09-29 19:19
I'm getting this error on a MacBookPro running an apple M1 Pro.

**Comment by kburakozdemir** [comment] 2023-09-30 06:03
> I can confirm this, i get this error on every command:
> 
> `ERROR ==> Error: spawn /home/sh/.lando/bin/docker-compose-v2.21.0 EACCES `

This is exactly what I get.... I am on

```txt
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by brsowers** [comment] 2023-09-30 11:48
Look at https://github.com/lando/core/issues/63. With help from @pirog I was able to sort out my issue.

**Comment by kburakozdemir** [comment] 2023-10-02 06:48
> Look at [lando/core#63](https://github.com/lando/core/issues/63). With help from @pirog I was able to sort out my issue.

After making the file executable and running `/home/burak/.lando/bin/docker-compose-v2.21.0 --version` as recommended, I get this error:

`[1]    34142 segmentation fault  /home/burak/.lando/bin/docker-compose-v2.21.0 --version`

**Comment by kburakozdemir** [comment] 2023-10-02 06:57
Now I tried another workaround. 

1. Install lando
2. Install docker-compose stand-alone version via https://docs.docker.com/compose/install/standalone/ running the commands below:
```bash
curl -SL https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-linux-x86_64 -o /home/username/.lando/bin/docker-compose-v2.21.0

chmod +x /home/username/.lando/bin/docker-compose-v2.21.0

/home/username/.lando/bin/docker-compose-v2.21.0 --version
```

This resolved my issue...

**Comment by pirog** [comment] 2023-10-02 13:48
going to close this in favor of https://github.com/lando/core/issues/63

**Closed by pirog** 2023-10-02 13:48 UTC
Labels: bug

**Comment by cbrody** [comment] 2023-10-09 09:52
This does not seem to have been fully resolved, as I had a similar issue today installing lando v3.20.4 on MacOS 14.0 running on Apple silicon. Running `lando start` appears to show `docker-compose-v2.21.0` being downloaded, but `~/.lando/bin/` remained empty after the command finished. The fix for me was to download https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-darwin-aarch64 to `~/.lando/bin/`, rename the file to `docker-compose-v2.21.0` and make it executable.

**Comment by pirog** [comment] 2023-10-09 11:56
@cbrody if you could re-run with `-vvv` and provide the relevant output that would be helpful otherwise this is not a lot to go one.

**Comment by cbrody** [comment] 2023-10-09 14:49
`% lando start -vvv`
```lando 10:01:48 DEBUG ==> No update available. 
lando 10:01:48 VERBOSE ==> starting bootstrap at level app... 
lando 10:01:48 VERBOSE ==> config bootstrap beginning... 
lando 10:01:48 DEBUG ==> emitting event pre-bootstrap-config 
lando 10:01:48 DEBUG ==> plugin lando-core loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-core/index.js 
lando 10:01:48 DEBUG ==> plugin lando-events loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-events/index.js 
lando 10:01:48 DEBUG ==> plugin lando-healthcheck loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/index.js 
lando 10:01:48 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-networking/index.js 
lando 10:01:48 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-proxy/index.js 
lando 10:01:48 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-recipes/index.js 
lando 10:01:48 DEBUG ==> plugin lando-scanner loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-scanner/index.js 
lando 10:01:48 DEBUG ==> plugin lando-services-v4 loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-services-v4/index.js 
lando 10:01:48 DEBUG ==> plugin lando-services loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-services/index.js 
lando 10:01:48 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-sharing/index.js 
lando 10:01:48 DEBUG ==> plugin lando-test loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-test/index.js 
lando 10:01:48 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-tooling/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/apache loaded from /snapshot/cli/node_modules/@lando/apache/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/backdrop loaded from /snapshot/cli/node_modules/@lando/backdrop/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/compose loaded from /snapshot/cli/node_modules/@lando/compose/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/dotnet loaded from /snapshot/cli/node_modules/@lando/dotnet/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/drupal loaded from /snapshot/cli/node_modules/@lando/drupal/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/elasticsearch loaded from /snapshot/cli/node_modules/@lando/elasticsearch/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/go loaded from /snapshot/cli/node_modules/@lando/go/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/joomla loaded from /snapshot/cli/node_modules/@lando/joomla/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/lamp loaded from /snapshot/cli/node_modules/@lando/lamp/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/laravel loaded from /snapshot/cli/node_modules/@lando/laravel/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/lemp loaded from /snapshot/cli/node_modules/@lando/lemp/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mailhog loaded from /snapshot/cli/node_modules/@lando/mailhog/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mariadb loaded from /snapshot/cli/node_modules/@lando/mariadb/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mean loaded from /snapshot/cli/node_modules/@lando/mean/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/memcached loaded from /snapshot/cli/node_modules/@lando/memcached/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mongo loaded from /snapshot/cli/node_modules/@lando/mongo/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mssql loaded from /snapshot/cli/node_modules/@lando/mssql/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/mysql loaded from /snapshot/cli/node_modules/@lando/mysql/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/nginx loaded from /snapshot/cli/node_modules/@lando/nginx/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/node loaded from /snapshot/cli/node_modules/@lando/node/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/php loaded from /snapshot/cli/node_modules/@lando/php/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/phpmyadmin loaded from /snapshot/cli/node_modules/@lando/phpmyadmin/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/postgres loaded from /snapshot/cli/node_modules/@lando/postgres/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/python loaded from /snapshot/cli/node_modules/@lando/python/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/redis loaded from /snapshot/cli/node_modules/@lando/redis/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/ruby loaded from /snapshot/cli/node_modules/@lando/ruby/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/solr loaded from /snapshot/cli/node_modules/@lando/solr/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/symfony loaded from /snapshot/cli/node_modules/@lando/symfony/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/tomcat loaded from /snapshot/cli/node_modules/@lando/tomcat/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/varnish loaded from /snapshot/cli/node_modules/@lando/varnish/index.js 
lando 10:01:48 DEBUG ==> plugin @lando/wordpress loaded from /snapshot/cli/node_modules/@lando/wordpress/index.js 
lando 10:01:48 DEBUG ==> emitting event post-bootstrap-config 
lando 10:01:48 VERBOSE ==> building proxy config... 
lando 10:01:48 VERBOSE ==> config bootstrap completed. 
lando 10:01:48 VERBOSE ==> tasks bootstrap beginning... 
lando 10:01:48 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 10:01:48 DEBUG ==> autoloaded task config 
lando 10:01:48 DEBUG ==> autoloaded task destroy 
lando 10:01:48 DEBUG ==> autoloaded task info 
lando 10:01:48 DEBUG ==> autoloaded task list 
lando 10:01:48 DEBUG ==> autoloaded task logs 
lando 10:01:48 DEBUG ==> autoloaded task poweroff 
lando 10:01:48 DEBUG ==> autoloaded task rebuild 
lando 10:01:48 DEBUG ==> autoloaded task restart 
lando 10:01:48 DEBUG ==> autoloaded task share 
lando 10:01:48 DEBUG ==> autoloaded task start 
lando 10:01:48 DEBUG ==> autoloaded task stop 
lando 10:01:48 DEBUG ==> autoloaded task version 
lando 10:01:48 DEBUG ==> autoloaded task init 
lando 10:01:48 DEBUG ==> autoloaded task ssh 
lando 10:01:48 DEBUG ==> emitting event post-bootstrap-tasks 
lando 10:01:48 VERBOSE ==> tasks bootstrap completed. 
lando 10:01:48 VERBOSE ==> engine bootstrap beginning... 
lando 10:01:48 DEBUG ==> emitting event pre-bootstrap-engine 
lando 10:01:48 DEBUG ==> could not detect docker-compose v2.21.0! 
lando 10:01:48 DEBUG ==> downloading https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-darwin-aarch64 to /Users/chrisbrody/.lando/bin/docker-compose-v2.21.0...```

The command then terminates.

**Comment by pirog** [comment] 2023-10-09 16:51
Terminates or hangs? The debug output looks like it’s not detecting a TTY,
what terminal are you using?

**Comment by cbrody** [comment] 2023-10-10 14:56
I've tried running `lando rebuild -y -vvv` post installation of v3.20.4 on a personal machine running the same OS (MacBook Air M2, 2022) and had exactly the same issue. Terminal and Docker both have full disk access enabled and no additional security measures are in place above what MacOS provides by default. Output follows:

```
chris@CDLB-MBA iied-main % lando rebuild -y -vvv
lando 15:40:01 DEBUG ==> No update available. 
lando 15:40:01 VERBOSE ==> starting bootstrap at level app... 
lando 15:40:01 VERBOSE ==> config bootstrap beginning... 
lando 15:40:01 DEBUG ==> emitting event pre-bootstrap-config 
lando 15:40:01 DEBUG ==> plugin lando-core loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-core/index.js 
lando 15:40:01 DEBUG ==> plugin lando-events loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-events/index.js 
lando 15:40:01 DEBUG ==> plugin lando-healthcheck loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/index.js 
lando 15:40:01 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-networking/index.js 
lando 15:40:01 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-proxy/index.js 
lando 15:40:01 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-recipes/index.js 
lando 15:40:01 DEBUG ==> plugin lando-scanner loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-scanner/index.js 
lando 15:40:01 DEBUG ==> plugin lando-services-v4 loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-services-v4/index.js 
lando 15:40:01 DEBUG ==> plugin lando-services loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-services/index.js 
lando 15:40:01 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-sharing/index.js 
lando 15:40:01 DEBUG ==> plugin lando-test loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-test/index.js 
lando 15:40:01 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/node_modules/@lando/core/plugins/lando-tooling/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/apache loaded from /snapshot/cli/node_modules/@lando/apache/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/backdrop loaded from /snapshot/cli/node_modules/@lando/backdrop/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/compose loaded from /snapshot/cli/node_modules/@lando/compose/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/dotnet loaded from /snapshot/cli/node_modules/@lando/dotnet/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/drupal loaded from /snapshot/cli/node_modules/@lando/drupal/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/elasticsearch loaded from /snapshot/cli/node_modules/@lando/elasticsearch/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/go loaded from /snapshot/cli/node_modules/@lando/go/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/joomla loaded from /snapshot/cli/node_modules/@lando/joomla/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/lamp loaded from /snapshot/cli/node_modules/@lando/lamp/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/laravel loaded from /snapshot/cli/node_modules/@lando/laravel/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/lemp loaded from /snapshot/cli/node_modules/@lando/lemp/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mailhog loaded from /snapshot/cli/node_modules/@lando/mailhog/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mariadb loaded from /snapshot/cli/node_modules/@lando/mariadb/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mean loaded from /snapshot/cli/node_modules/@lando/mean/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/memcached loaded from /snapshot/cli/node_modules/@lando/memcached/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mongo loaded from /snapshot/cli/node_modules/@lando/mongo/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mssql loaded from /snapshot/cli/node_modules/@lando/mssql/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/mysql loaded from /snapshot/cli/node_modules/@lando/mysql/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/nginx loaded from /snapshot/cli/node_modules/@lando/nginx/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/node loaded from /snapshot/cli/node_modules/@lando/node/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/php loaded from /snapshot/cli/node_modules/@lando/php/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/phpmyadmin loaded from /snapshot/cli/node_modules/@lando/phpmyadmin/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/postgres loaded from /snapshot/cli/node_modules/@lando/postgres/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/python loaded from /snapshot/cli/node_modules/@lando/python/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/redis loaded from /snapshot/cli/node_modules/@lando/redis/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/ruby loaded from /snapshot/cli/node_modules/@lando/ruby/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/solr loaded from /snapshot/cli/node_modules/@lando/solr/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/symfony loaded from /snapshot/cli/node_modules/@lando/symfony/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/tomcat loaded from /snapshot/cli/node_modules/@lando/tomcat/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/varnish loaded from /snapshot/cli/node_modules/@lando/varnish/index.js 
lando 15:40:01 DEBUG ==> plugin @lando/wordpress loaded from /snapshot/cli/node_modules/@lando/wordpress/index.js 
lando 15:40:01 DEBUG ==> emitting event post-bootstrap-config 
lando 15:40:01 VERBOSE ==> building proxy config... 
lando 15:40:01 VERBOSE ==> config bootstrap completed. 
lando 15:40:01 VERBOSE ==> tasks bootstrap beginning... 
lando 15:40:01 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 15:40:01 DEBUG ==> autoloaded task config 
lando 15:40:01 DEBUG ==> autoloaded task destroy 
lando 15:40:01 DEBUG ==> autoloaded task info 
lando 15:40:01 DEBUG ==> autoloaded task list 
lando 15:40:01 DEBUG ==> autoloaded task logs 
lando 15:40:01 DEBUG ==> autoloaded task poweroff 
lando 15:40:01 DEBUG ==> autoloaded task rebuild 
lando 15:40:01 DEBUG ==> autoloaded task restart 
lando 15:40:01 DEBUG ==> autoloaded task share 
lando 15:40:01 DEBUG ==> autoloaded task start 
lando 15:40:01 DEBUG ==> autoloaded task stop 
lando 15:40:01 DEBUG ==> autoloaded task version 
lando 15:40:01 DEBUG ==> autoloaded task init 
lando 15:40:01 DEBUG ==> autoloaded task ssh 
lando 15:40:01 DEBUG ==> emitting event post-bootstrap-tasks 
lando 15:40:01 VERBOSE ==> tasks bootstrap completed. 
lando 15:40:01 VERBOSE ==> engine bootstrap beginning... 
lando 15:40:01 DEBUG ==> emitting event pre-bootstrap-engine 
lando 15:40:01 DEBUG ==> could not detect docker-compose v2.21.0! 
lando 15:40:01 DEBUG ==> downloading https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-darwin-aarch64 to /Users/chris/.lando/bin/docker-compose-v2.21.0... 
chris@CDLB-MBA iied-main %
```

**Comment by cbrody** [comment] 2023-10-10 17:06
Yes, both machines were on the same network. I've just run `lando rebuild` while connected to a different (5G mobile) network and the command succeeded this time, so looks like we're onto something here! As there don't appear to be many others having this issue, it's probably not worth spending much more time on at this stage. Thanks @pirog for your help.
