### ISSUE TITLE
Lando start ... could not create Drush or composer.json ... Permission Denied

### ISSUE THREAD

**Issue by GreenSkunk** [lando/lando#493] opened 2017-11-14 06:57 UTC
Starting Lando app for the first time after initializing drupal8 recipe results in permission denied when creating files. Running the "lando start" command again works fine.
```bash
~/sites/drupal-8$ lando init --recipe drupal8
? Where is your webroot relative to the init destination? web
? What do you want to call this app? drupal-8-migrate

NOW WE'RE COOKING WITH FIRE!!!

Your app has been initialized.
Now try running `lando start` to get rolling.

Here are some vitals:

 NAME    drupal-8-migrate                                    
 RECIPE  drupal8                                             
 DOCS    https://docs.devwithlando.io/tutorials/drupal8.html 
```
What is your lando version and operating system?
v3.0.0-beta.22 on Elementary OS 0.4.1 Loki (Ubuntu 16.04.3 LTS)

**Tell us about your `.lando.yml`**
Drupal8 recipe
*First time running*
```bash
~/sites/drupal-8$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... 
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "drupal8migrate_default" with the default driver
Creating volume "drupal8migrate_appserver" with default driver
Creating volume "drupal8migrate_data" with default driver
Creating volume "drupal8migrate_data_database" with default driver
Pulling appserver (devwithlando/php:7.1-apache)...
Pulling database (mysql:latest)...
Creating drupal8migrate_database_1 ... 
Creating drupal8migrate_appserver_1 ... 
Creating drupal8migrate_appserver_1
Creating drupal8migrate_database_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5988k  100 5988k    0     0  2234k      0  0:00:02  0:00:02 --:--:-- 2234k
 PHP configuration      :  /usr/local/etc/php/php.ini 
 PHP OS                 :  Linux                      
 Drush script           :  /tmp/drush.phar            
 Drush version          :  8.1.13                     
 Drush temp directory   :  /tmp                       
 Drush configuration    :                             
 Drush alias files      :                             

mv: cannot create regular file '/usr/local/bin/drush': Permission denied
Changed current directory to /var/www/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5988k  100 5988k    0     0  2234k      0  0:00:02  0:00:02 --:--:-- 2234k
 PHP configuration      :  /usr/local/etc/php/php.ini 
 PHP OS                 :  Linux                      
 Drush script           :  /tmp/drush.phar            
 Drush version          :  8.1.13                     
 Drush temp directory   :  /tmp                       
 Drush configuration    :                             
 Drush alias files      :                             

mv: cannot create regular file '/usr/local/bin/drush': Permission denied
Changed current directory to /var/www/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

, code=1
```
*Second time ... this time ... verbose*
```bash
lando start -vvvv
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
drupal8migrate_appserver_1 is up-to-date
drupal8migrate_database_1 is up-to-date

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            drupal-8-migrate                   
 LOCATION        /home/jeremy/sites/drupal-8        
 SERVICES        appserver, database                
                                                    
 APPSERVER URLS  https://localhost:32769            
                 http://localhost:32770             
                 http://drupal-8-migrate.lndo.site  
                 https://drupal-8-migrate.lndo.site 
```

**Comment by franciscoDeskmultimedia** [comment] 2017-11-14 17:20
having the same problem in Deepin OS . 
Running lando start for the second time gives me this:

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            drupalgroup                                     
 LOCATION        /home/pancho/Desktop/Proyectos/test/drupalgroup 
 SERVICES        appserver, database                             
                                                                 
 APPSERVER URLS  https://localhost:32778                         
                 http://localhost:32779                          
                 http://drupalgroup.lndo.site                    
                 https://drupalgroup.lndo.site   
But it seem it makes a lamp recipe.

**Comment by franciscoDeskmultimedia** [comment] 2017-11-14 17:22
![deepinscreenshot_select-area_20171114122124](https://user-images.githubusercontent.com/32280492/32794317-797bb40e-c936-11e7-9225-fb34a4616839.png)

**Comment by bmcclure** [comment] 2017-11-14 17:56
I'm having this issue as well. I run into it using the "drupal7" recipe. I usually use the "pantheon" recipe and don't have this issue.

**Comment by franciscoDeskmultimedia** [comment] 2017-11-16 03:12
someone have any work arround for this. ?? i even try to add drush in a lamp recipe but have the same error:

> mv: cannot create regular file '/usr/local/bin/drush': Permission denied
> Changed current directory to /var/www/.composer

**Comment by franciscoDeskmultimedia** [comment] 2017-11-17 14:35
@pirog sorry for asking jaja . is any work arround for the drupal recipe for the drush problem? .
Again Sorry is just tha Lando is present in my day to day work.

**Comment by alexfinnarn** [comment] 2017-11-20 16:26
I can confirm this happened to me on an install of: 

OS: Ubuntu 17.10 
Lando: v3.0.0-beta.25

.lando.yml

```yaml
name: foobar
recipe: drupal7
config:
  webroot: web
```

I might have done `lando start` at some point with another issue I resolved, but I could `lando rebuild` and get the same Drush permission error mentioned above repeatedly. 

I did add myself to the Docker group mentioned in https://docs.devwithlando.io/installation/installing.html as a caveat for Linux, and I could run `docker run hello-world` without sudo or any errors listed.

**Comment by franciscoDeskmultimedia** [comment] 2017-11-21 05:29
Problem persist in new release Lando: v3.0.0-beta.26

**Comment by anavarre** [comment] 2017-11-22 18:37
The issue also happened to me. I tried with 8.3.7 and it worked well. My assumption at this point is things are broken with 8.4.x and Drush since it's now supposed to be installed locally via `composer.json`.

Could you maybe try and confirm there's no error with versions of Drupal prior to 8.4.0?

**Comment by franciscoDeskmultimedia** [comment] 2017-11-22 23:38
Ok @anavarre I am going to try with drupal 8.3.7 and reply the result

**Comment by franciscoDeskmultimedia** [comment] 2017-11-23 00:37
Ok , this is what i try and work some how.

-Drupal 7.56
-my recipe:
`name: drupaltest
recipe: drupal7
config:
  webroot: .
# See: https://www.drupal.org/docs/7/system-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Drupal 7.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Drupal 7 so YMMV.
  #
  # See: https://www.drupal.org/docs/7/system-requirements/php
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '5.6'

  # Optionally specify whether you want to serve drupal via nginx or apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://www.drupal.org/docs/7/system-requirements/web-server
  #
  via: nginx


  # Optionally specify the version of Drush you want for your site
  #
  # If omitted (which is recommended) this will use the stable Drush
  #
  # This will take any version to which there is a corresponding phar over on
  # the drush github release page eg `drush: 8.1.12`
  #
  # see: https://github.com/drush-ops/drush/releasess
  #
  # Alternatively this will also take any supported composer version eg `~7`
  # THIS SHOULD BE USED WITH CAUTION.
  #
  # Obviously, if you have a site-local drush installed via composer that will be
  # used instead of this one.
  #
  # see: http://docs.drush.org/en/master/install/
  #
  drush: 8.1.11
`
so the thing seems to be drush version from 8.1.12+.

so i test:
-drush cc all  ---> works
-drush dl       ---> works
-drush en      --->works

**Comment by pirog** [comment] 2017-11-24 19:05
I think we might have two separate issues happening here. For drush/drupal version related issues i'd move over to #542. For permission related issues i'd stay here. 

My *current best guess* re permissions is there is something specific to the linux OS you are running that we don't handle well

**Comment by alexfinnarn** [comment] 2017-12-08 05:08
After updating Lando and my OS, I no longer have permissions issues, and with `drush: false` I was able to install a Drupal 7 recipe. 

I do still get the same Drush permissions error, but if that is being covered in another issue, then you can close this one.

**Comment by NumerousHats** [comment] 2018-01-09 20:11
I'm seeing similar behavior not only with drush installation in drupal recipes, but **also** with wordpress. In my hands, an attempt at a generic wordpress install with a default .lando.yml generated by `lando init` gives the following result upon running `lando start` for the first time:

landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "worp_default" with the default driver
Creating volume "worp_appserver" with default driver
Creating volume "worp_data" with default driver
Creating volume "worp_data_database" with default driver
Creating worp_database_1 ... 
Creating worp_appserver_1 ... 
Creating worp_database_1
Creating worp_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4306k  100 4306k    0     0  4301k      0  0:00:01  0:00:01 --:--:-- 4302k
PHP binary:	/usr/local/bin/php
PHP version:	7.1.13
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/tmp
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.4.1
mv: cannot create regular file '/usr/local/bin/wp': Permission denied
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4306k  100 4306k    0     0  4301k      0  0:00:01  0:00:01 --:--:-- 4302k
PHP binary:	/usr/local/bin/php
PHP version:	7.1.13
php.ini used:	
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/tmp
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.4.1
mv: cannot create regular file '/usr/local/bin/wp': Permission denied
, code=1

Subsequently running `lando start`, or `lando stop` followed by `lando start` results in no "Permission denied" messages, but wordpress didn't seem to install: I see the same "Index of /" page that @franciscoDeskmultimedia posted earlier.

I am running Ubuntu 17.10 and Docker 17.11.

**Comment by tormi** [comment] 2018-03-13 18:26
> I see the same "Index of /" page 
@NumerousHats, @franciscoDeskmultimedia - did you load the page with https?

**Comment by dustinleblanc** [comment] 2018-03-14 14:05
Hey all, is this still an issue for folks? If so, can you let us know your OS version? @pirog seemed to think this was related to specific linux flavors and its hard to see what is actionable here.

**Comment by NumerousHats** [comment] 2018-03-14 23:14
Don't know if it's still an issue, as I've pretty much given up on lando and gone back to a vagrant-based dev environment... :-(  The OS details are at the bottom of my January 9th comment above.

**Comment by alexfinnarn** [comment] 2018-03-14 23:47
OS: Ubuntu 17.10
Lando: v3.0.0-beta.35

I tried the same .lando.yml file as above...

```yaml
name: foobar
recipe: drupal7
config:
  webroot: web
```

but got way different errors. I think mine may be a Docker issue (not being up?) and not Lando, but I've pasted more info from my terminal output that might help.

```bash
~/S/lando ❯❯❯ uname -a                                                                                                                                                                    
Linux spankypants-Q551LB 4.13.0-36-generic #40-Ubuntu SMP Fri Feb 16 20:07:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

~/S/lando ❯❯❯ lsb_release -a                                                                                                                                                             
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

~/S/lando ❯❯❯ lando version                                                                                                                                                               
v3.0.0-beta.35

~/S/lando ❯❯❯ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "foobar_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "foobar_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "foobar_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
Creating network "foobar_default" with the default driver
ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
error:  Error: Error
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

~/S/lando ❯❯❯  docker container ls -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                      PORTS                                                                 NAMES
177b7efa6494        vim_php                    "docker-php-entrypoi…"   8 weeks ago         Exited (0) 8 weeks ago                                                                            vim_php_1
b4f9a45be929        bd54be942dcb               "/bin/sh -c 'apt-get…"   8 weeks ago         Exited (100) 8 weeks ago                                                                          cranky_lichterman
3ff17fac982c        31338c6d2816               "/bin/sh -c 'pecl in…"   8 weeks ago         Exited (1) 8 weeks ago                                                                            flamboyant_swartz
aceb735433bd        nanobox/mysql:5.6          "/opt/gonano/bin/nan…"   2 months ago        Exited (255) 2 months ago                                                                         nanobox_03d6f74fdf9c1af4d5a56e9e23873fbb_dev_data.db
6523afed5ee3        nanobox/build              "/opt/gonano/bin/nan…"   2 months ago        Exited (137) 2 months ago                                                                         nanobox_03d6f74fdf9c1af4d5a56e9e23873fbb_dev
e18ac16e5ff9        wodby/drupal:8-7.1-3.0.0   "/docker-entrypoint.…"   3 months ago        Exited (255) 3 months ago   9000/tcp                                                              d4d_php_1
92ec727634d8        wodby/mariadb:10.1-2.3.5   "/docker-entrypoint.…"   3 months ago        Exited (255) 3 months ago   3306/tcp                                                              d4d_mariadb_1
ae106bc1ca26        traefik                    "/traefik -c /dev/nu…"   3 months ago        Created                                                                                           d4d_traefik_1
bfe3974b45b1        hello-world                "/hello"                 3 months ago        Exited (0) 3 months ago                                                                           focused_golick
a186931d6143        traefik:1.3-alpine         "/lando-entrypoint.s…"   3 months ago        Up 21 minutes               0.0.0.0:443->443/tcp, 0.0.0.0:8000->80/tcp, 0.0.0.0:58086->8080/tcp   landoproxyhyperion5000gandalfedition_proxy_1

/S/lando ❯❯❯  docker image ls -a                                                                                                                                                        ✘ 1 
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
vim_php               latest              1023858afc80        8 weeks ago         435MB
<none>                <none>              46106ba6d9a0        8 weeks ago         435MB
<none>                <none>              cf17861927d7        8 weeks ago         435MB
<none>                <none>              7acfdadf266c        8 weeks ago         435MB
<none>                <none>              542ca68e3392        8 weeks ago         435MB
<none>                <none>              ac231577ee33        8 weeks ago         435MB
<none>                <none>              26750e78fb6b        8 weeks ago         435MB
<none>                <none>              71a6210e00e2        8 weeks ago         435MB
<none>                <none>              ca8faa057fb3        8 weeks ago         435MB
<none>                <none>              e9fd98722815        8 weeks ago         435MB
<none>                <none>              32779f169a42        8 weeks ago         433MB
<none>                <none>              31338c6d2816        8 weeks ago         416MB
devwithlando/php      7.0-apache          e0856f386612        2 months ago        815MB
php                   7.1-apache          bd54be942dcb        2 months ago        392MB
php                   7.2-apache          f99d319c7004        2 months ago        377MB
devwithlando/php      7.1-apache          4c451b25325c        3 months ago        817MB
mysql                 latest              7d83a47ab2d2        3 months ago        408MB
mysql                 <none>              dd0afb9bc4a9        3 months ago        408MB
devwithlando/php      <none>              a49f68acdd33        3 months ago        817MB
devwithlando/php      <none>              95cf40c95fbf        3 months ago        815MB
nanobox/mysql         5.6                 03be086b31c6        3 months ago        734MB
devwithlando/php      <none>              90ae29b85856        3 months ago        776MB
nanobox/build         latest              e8e129d43f64        3 months ago        624MB
devwithlando/php      <none>              99aca39352e5        3 months ago        774MB
traefik               latest              79f625300972        4 months ago        45.6MB
portainer/portainer   latest              6cafdc66421d        4 months ago        33.1MB
mysql                 <none>              5709795eeffa        4 months ago        408MB
hello-world           latest              725dcfab7d63        4 months ago        1.84kB
wodby/drupal-nginx    8-1.13-3.0.1        aafde4bcfbe2        5 months ago        31.2MB
wodby/drupal          8-7.1-3.0.0         1e6618bc71c9        5 months ago        362MB
traefik               1.3-alpine          6d95023f9ce9        5 months ago        49.7MB
wodby/mariadb         10.1-2.3.5          37582351402a        6 months ago        205MB
mailhog/mailhog       latest              669347153085        11 months ago       19.1MB

```

I've created no less than four starter development kits for my team, one of which uses Lando. We've gravitated toward native solutions, because of Docker for Mac OS file mounting issue. I didn't get too far into the weeds of that issue but what I mean is...

https://github.com/docker/for-mac/issues/1592

I tried some caching flags and stuff but was just hacking around and gave up...

Someone wanted to work on 10 sites at the same time and we use symlinked files to accomplish that and not have to copy the same code. As understand it, the more files you mount, the slower the PHP script is read and executed. So, unknowingly at the time, I kept adding sites to my starter kit project to test and it kept getting slower. I didn't run across any mounting issues until I went ahead and tried my own Docker Compose orchestration.

I've wanted to try and go back to modify Lando via the D7 recipe to only mount the code we are developing and not files like Drupal core. That should drastically reduce number of files mounted. But that's where we got lost...Lando started taking a long time to complete requests, and I said screw it and ran `drush runserver` and also sometimes Laravel's Valet project...but then I don;t know anything about NGINX...always something goes wrong.

I'd be happy to try any other debugging, but since I am not using Lando ATM (and normally use it on MacOS), I'm not going to follow up unless you give me steps to try.

**Comment by alexfinnarn** [comment] 2018-03-14 23:50
nvm, I lied...and I am now following up = no one should trust me.

The IP address issue was actually my VPN service. So, now at least you know how that error looks to a Lando user.

```bash
~/S/lando ❯❯❯ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "foobar_default" with the default driver
Creating volume "foobar_appserver" with default driver
Creating volume "foobar_data" with default driver
Creating volume "foobar_data_database" with default driver
Creating foobar_appserver_1 ... 
Creating foobar_database_1 ... 
Creating foobar_appserver_1
Creating foobar_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    221      0 --:--:--  0:00:02 --:--:--   223
100 5912k  100 5912k    0     0   850k      0  0:00:06  0:00:06 --:--:-- 1418k
 PHP configuration      :                  
 PHP OS                 :  Linux           
 Drush script           :  /tmp/drush.phar 
 Drush version          :  8.1.15          
 Drush temp directory   :  /tmp            
 Drush configuration    :                  
 Drush alias files      :                  

mv: cannot create regular file '/usr/local/bin/drush': Permission denied
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    221      0 --:--:--  0:00:02 --:--:--   223
100 5912k  100 5912k    0     0   850k      0  0:00:06  0:00:06 --:--:-- 1418k
 PHP configuration      :                  
 PHP OS                 :  Linux           
 Drush script           :  /tmp/drush.phar 
 Drush version          :  8.1.15          
 Drush temp directory   :  /tmp            
 Drush configuration    :                  
 Drush alias files      :                  

mv: cannot create regular file '/usr/local/bin/drush': Permission denied
, code=1
```

So, it looks like my issue does persist.

**Comment by quietone1** [comment] 2018-03-21 22:59
I continue to have problems with drush. I always have to `lando composer install drush/drush` and then `lando rebuild` at least once.

```
? Are you sure you want to rebuild? Yes
Stopping dev0_pma_1 ... done
Stopping dev0_appserver_1 ... done
Stopping dev0_database_1 ... done
Removing dev0_pma_1 ... done
Removing dev0_appserver_1 ... done
Removing dev0_database_1 ... done
Pulling appserver (devwithlando/php:7.1-apache)...
Pulling pma (phpmyadmin/phpmyadmin:latest)...
Pulling database (mariadb:10.1)...
appserver uses an image, skipping
pma uses an image, skipping
database uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating dev0_appserver_1 ...
Creating dev0_pma_1 ...
Creating dev0_database_1 ...
Creating dev0_pma_1
Creating dev0_database_1
Creating dev0_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    588      0 --:--:--  0:00:01 --:--:--   588
100  267k  100  267k    0     0  89205      0  0:00:03  0:00:03 --:--:--  242k
Drush Launcher Version: 0.4.3
mv: cannot create regular file '/usr/local/bin/drush': Permission denied   
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    588      0 --:--:--  0:00:01 --:--:--   588
100  267k  100  267k    0     0  89205      0  0:00:03  0:00:03 --:--:--  242k
Drush Launcher Version: 0.4.3
mv: cannot create regular file '/usr/local/bin/drush': Permission denied   
, code=1

```

**Comment by pirog** [comment] 2018-03-30 03:41
I strongly suspect this was caused by https://github.com/lando/lando/issues/795 (which was fixed). I'd update to the latest beta.38 and see if you get the same rebuilding your app. 

If you cannot please reopen this!

**Closed by pirog** 2018-03-30 03:41 UTC
Labels: linux, pantheon

**Comment by gonssal** [comment] 2018-10-11 15:38
This is still happening to me. Ubuntu 18.04, lando v3.0.0-rc.1, drupal7 recipe.

Relevant lines on lando rebuild:

```shell
Creating appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0    616      0 --:--:-- --:--:-- --:--:--   616
100 4482k  100 4482k    0     0   762k      0  0:00:05  0:00:05 --:--:--  953k
 PHP configuration      :                  
 PHP OS                 :  Linux           
 Drush script           :  /tmp/drush.phar 
 Drush version          :  8.1.16          
 Drush temp directory   :  /tmp            
 Drush configuration    :                  
 Drush alias files      :                  

mv: cannot create regular file '/usr/local/bin/drush': Permission denied
error: Looks like one of your build steps failed with [object Object]
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

Everything works but of course when you try to run `lando drush` it returns `/bin/sh: 1: drush: not found`, which is a dealbreaker for Drupal development.

**Comment by pirog** [comment] 2018-10-12 13:36
i *think* we are tracking this over at #1197 now
