### ISSUE TITLE
Lando 3.11.0 ucrtbase.dll

### ISSUE THREAD

**Issue by aeonshad** [lando/lando#3510] opened 2023-02-04 08:48 UTC
Hello, it's mentioned that with the update 3.11.0 the problem of installation on a computer with a language other than "en-us" is fixed. #3490.

So this patch solves the problem I had with the windows language. 
However, when I try to install I get this error: "Access violation at address 770CFE90 in module 'ucrtbase.dll'. Read of address 041972CC."

I tried to put my windows in "en-us" but I still get the same error.

**Comment by Sandy-Garrido** [comment] 2023-02-06 22:37
I have this error also with this version

**Comment by Sandy-Garrido** [comment] 2023-02-07 19:38
I have tried to install all landos as far back until one of them worked. The latest version that does NOT have this issue for me ins 3.6.4

So the problem starts in 3.8.0

**Comment by Sandy-Garrido** [comment] 2023-02-07 19:50
@aeonshad I had success installing it! The instructions were linked in an ticket that was closed 2 weeks ago

https://github.com/lando/lando/issues/3498#issuecomment-1405549937

**Comment by aeonshad** [comment] 2023-02-07 20:05
Hi, indeed by using a command prompt the installation can start, it's strange.

I put the installer on the desktop and created a .bat to run it.
```batch
@echo on
cd C:\Users\Aeon\Desktop
start lando-x64-v3.11.0.exe /LOG
```
@Sandy-Garrido Thank you for finding the solution temporarily

**Comment by MrVP** [comment] 2023-05-15 16:21
Hello,

I had the same issue but with lando-x64-v3.17.0.exe - same error
but @aeonshad script worked for me!

**Comment by gramos-vibrent** [comment] 2023-05-16 14:03
On windows - right click and run as administrator.... its a permissions issue

**Comment by AaronFeledy** [comment] 2023-08-25 18:29
Closing as duplicate of #3498. Check there for possible workarounds and updates.

**Closed by AaronFeledy** 2023-08-25 18:29 UTC
Labels: bug
