### ISSUE TITLE
Overriding the image used for Python service fails with TypeError

### ISSUE THREAD

**Issue by aleksijohansson** [lando/lando#724] opened 2018-02-26 10:45 UTC
Overriding the image used for Python service does not work. This forces the usage of the default Python image which is based on Debian Jessie and is huge compared to the Alpine based one:

```bash
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              3.6-jessie          336d482502ab        9 days ago          692MB
python              3.6-alpine3.7       4b00a94b6f26        6 weeks ago         83.4MB
```

I'm assuming this is a general bug related to overrides which in many cases would prevent the usage of Lando completely if it's not fixed.

Operating system: v3.0.0-beta.35 on macOS High Sierra 10.13.3.

`.lando.yml`:

```yml
name: python
services:
  appserver:
    type: python:3.6
    overrides:
      image: python:3.6-alpine3.7
```

Commands:
```bash
lando start
```

Error:
```bash
error:  TypeError: Cannot read property 'volumes' of undefined
    at mergeOver (/snapshot/cli/plugins/lando-services/lib/services.js:0:0)
    at Object.build (/snapshot/cli/plugins/lando-services/lib/services.js:0:0)
    at /snapshot/cli/plugins/lando-services/lib/config.js:0:0
    at isBind (/snapshot/cli/node_modules/lodash/lodash.js:4944:15)
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3001:24)
    at index (/snapshot/cli/node_modules/lodash/lodash.js:4913:18)
    at Function.forEach (/snapshot/cli/node_modules/lodash/lodash.js:9359:14)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/lib/config.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
    at runCallback (timers.js:800:20)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
From previous event:
    at instantiate (/snapshot/cli/lib/app.js:0:0)
    at /snapshot/cli/lib/app.js:0:0
From previous event:
    at Object.exports.get (/snapshot/cli/lib/app.js:0:0)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-tooling/lib/bootstrap.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Comment by dustinleblanc** [comment] 2018-03-18 17:46
Hmmm, @pirog do you think this happens because of the automagical second cli container business?

**Comment by dustinleblanc** [comment] 2018-04-03 13:16
Working to repro

**Comment by dustinleblanc** [comment] 2018-04-03 13:21
Hi @aleksijohansson!

Thanks fr the bug report, I created the following lando file to reproduce:

```yaml
name: lando-python
services:
    appserver:
        type: python:3.6
        overrides:
            image: python:3.6-alpine3.7
```
This is my output on beta 39:
```sh
☁  landoPython  lando start
Creating network "landopython_default" with the default driver
Creating volume "landopython_python_share" with default driver
Pulling appserver (python:3.6-jessie)...
Creating landopython_appserver_1 ... done
Waiting until appserver service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME      lando-python                             
 LOCATION  /home/dustinleblanc/Projects/landoPython 
 SERVICES  appserver                                
```
All the versions:
```sh
☁  landoPython  docker --version
Docker version 18.03.0-ce, build 0520e24
☁  landoPython  docker-compose --version
docker-compose version 1.20.1, build 5d8c71b
☁  landoPython  lando version
v3.0.0-beta.39
```

I am going to close this out for now, feel free to reopen if you are still able to reproduce this on the latest beta, thanks!

**Closed by dustinleblanc** 2018-04-03 13:21 UTC
Labels: bug, can not replicate, python

**Comment by aleksijohansson** [comment] 2018-04-04 08:46
This seems to work without any issues now in my project with beta 39, thanks!

**Comment by aleksijohansson** [comment] 2018-04-10 09:54
Hey! I missed a critical part when testing this. It's clearly visible in your output too. Lando is still pulling the jessie image of python. I also realised that the syntax for the overrides is wrong. It should be:

```
name: lando-python
services:
  appserver:
    type: python:3.6
    overrides:
      services:
        image: python:3.6-alpine3.7
```
Notice the additional `services` after `overrides`.

But that said, either of those don't fit the original scope of this issue so I'll open a new one.
