### ISSUE TITLE
Semantic drush version config does not work with lando v3.0.6

### ISSUE THREAD

**Issue by janadam** [lando/lando#2386] opened 2020-06-12 07:32 UTC
Using latest drush 8 with latest 3.0.6 is not working.
My test recipe:
```
cat .lando.yml 
name: test
recipe: drupal8
config:
  php: '7.2'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  drush: ^8
```
Error when trying to run drush:
`OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec format error": unknown
`
I guess it was this change:
https://github.com/lando/lando/commit/997a7e44b9611d164c3e0a21f83d23d769d93635#diff-b79126f26284ff4ed6725c2d8a37fa83R47

**Comment by pirog** [comment] 2020-06-22 18:43
@janadam i can replicate this. looks like a regression introduced by our new drush 10 "please do a site-local install" warning. I think we probably want to change the logic a bit:

1. If `options.drush` is not `false` then start by assuming a `composer install` method
2. If `options.drush` is `semvar.valid` and `semvar.major === 8` then switch to `phar` install method
3. if we can `semvar.coerce` a version that is `semver.gte > 10` then throw the drush 10 warning

**Comment by pirog** [comment] 2020-06-24 15:38
alright @jcandan this should be fixed in `3.0.7`

**Closed by pirog** 2020-06-24 15:38 UTC
Labels: bug, replicated

**Comment by jcandan** [comment] 2020-06-24 15:42
that's @janadam, not @jcandan. :)

**Comment by pirog** [comment] 2020-06-24 15:45
well, now you know too! and knowing is half the battle.
