### ISSUE TITLE
Help using Xdebug with VSCode and the Pantheon recipe

### ISSUE THREAD

**Issue by jacine** [lando/lando#2798] opened 2021-01-08 17:47 UTC
Hi! 

While spending the last few hours trying to debug why xDebug is no longer working, I realized there is a new version of xDebug, and tried to adjust the configuration to what [xDebug 3 needs](https://xdebug.org/docs/upgrade_guide). No matter what I do, my custom `php.ini` file is NOT being loaded, and apparently that seems to be on purpose with the Pantheon recipe according to https://github.com/lando/lando/issues/986#issuecomment-391401941.

I realize it will be supported in the next version of Lando, but until that happens is it possible to downgrade xDebug to version 2, so it can be used right now? Or do I need to dump the Pantheon recipe entirely (super frustrated with it and leaning toward this anyway, but I'm curious)?  

Any help would be greatly appreciated! Thank you! 😄

**Comment by jacine** [comment] 2021-01-08 20:48
I see the code to support v3 is in the latest release. However, it does not work, because `xdebug.start_with_request` needs `yes`, as opposed to `trigger`, and potentially [other settings](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug)... Hacking the `php.ini` files directly doesn't work, because they just get overridden when lando starts. 😭

**Comment by derickr** [comment] 2021-01-09 12:09
`trigger` should work in combination with any of the browser extensions to "trigger" the debugging request: https://xdebug.org/docs/step_debug#browser-extensions

**Comment by jacine** [comment] 2021-01-10 22:52
Hi @derickr,

Thank you so much for your help! 😄

I read that `trigger` should work as well, but for whatever reason it just didn't, until I changed that setting to `yes` (which I cannot do with the Pantheon recipe, because it doesn't allow a custom `php.ini`).

However, after your post, I went back and kept trying, because I can't see anyone else knowing better than you... and after more trial and error, I was able to get it working. It's still not 100%. I get an error (notice?) in the terminal with every Lando command, but it works where I need it, so I'm happily ignoring it for now.

Long story short:

- I needed `develop,debug` to activate step debugging.
- I needed to set `XDEBUG_SESSION_START: LANDO`

---

Here's the working config for anyone else that runs into this.

## Working config with Pantheon Recipe

```yml
name: name
recipe: pantheon
config:
  framework: drupal8
  xdebug: develop,debug
services:
  appserver:
    overrides:
      environment:
        # NOTE: Without this line, no local variables are available; only superglobal and user defined constants.
        XDEBUG_SESSION_START: LANDO
```

While the above works, I get this error/notice with every Lando command (sometimes multiple):

`Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (fallback through xdebug.client_host/xdebug.client_port) :-(`

## VS Code Config

Just in case it helps someone else, here is my `launch.json` file:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "log": true,
      "pathMappings": {
        "/app": "${workspaceRoot}",
      }
    }
  ]
}
```

**Comment by rbomhof** [comment] 2021-01-26 15:45
@jacine Thank you so much for posting this, was extremely helpful for me this morning trying to get XDebug back up and running with the Pantheon recipe!

**Comment by rabauss** [comment] 2021-01-26 18:33
You can even simply add `xdebug:true` - but for CLI debugging you need the environment variable!

````yml
...
services:
    appserver:
        xdebug: true
        overrides:
            environment:
                XDEBUG_SESSION_START: lando
````
We should add that config to the docs for xdebug!

**Comment by jacine** [comment] 2021-01-26 18:39
@rabauss You can... However,  just setting `xdebug: true` is the equivalent of setting the `XDEBUG_MODE` to `debug`.  If you need step debugging, you're going to want `develop` as well.  This is why I've used `xdebug: develop,debug` over just `xdebug: true`, as it results in `XDEBUG_MODE:  develop,debug`.

**Comment by derickr** [comment] 2021-01-26 20:07
On 26 January 2021 18:39:46 GMT, Jacine Luisi <notifications@github.com> wrote:
>@rabauss You can... However,  just setting `xdebug: true` is the
>equivalent of setting the `XDEBUG_MODE` to `debug`.  If you need step
>debugging, you're going to want `develop` as well.  This is why I've
>used `xdebug: develop,debug` over just `xdebug: true`, as it results in
>`XDEBUG_MODE:  develop,debug`.

You don't need `develop` for step debugging, only `debug`. But in most cases you'd like both on.

**Comment by reynoldsalec** [comment] 2021-11-23 00:09
I think everything but adding the environmental variable is reflected in the Lando docs. https://docs.lando.dev/guides/lando-with-vscode.html#advanced-setup

```
services:
  appserver:
    overrides:
      environment:
        # NOTE: Without this line, no local variables are available; only superglobal and user defined constants.
        XDEBUG_SESSION_START: LANDO
```

@rabauss + @jacine do you think we should mention that in the docs? I'm assuming by adding the env variable, it just always starts the session...I'm typically manually adding `XDEBU_SESSION_START=LANDO` as a URL parameter to start debugging.

**Comment by Farnoosh63** [comment] 2021-12-15 13:45
I am using Pantheon Recipe on drupal 9 with xdebug 2 and vscode. The xdebug works on `index.php` and other `.php` files such as `settings.php` but I have my preprocess on `.theme.inc` files and xdebug shows unverified breakpoint. Is this issue familiar for anyone? I appreciate any help. Thanks

**Comment by reynoldsalec** [comment] 2021-12-15 17:26
@Farnoosh63 I'm not familiar with that issue, but I know unverified breakpoint issues are typically caused by problems with xdebug mapping the path to the file, so I'd make sure the `pathMappings` value in your launch.json is setup correctly...remember that it's mapping to the virtual (Docker-ized) environment, which typically means the root path to your project is `/app/`. I think you can also get that error

If you have further questions, I'd recommend asking them either on the [Lando Slack](https://launchpass.com/devwithlando) or even the Drupal Slack, since this is probably not a Lando-specific issue.

Closing this issue out unless @jacine  or @rabauss has further advice on the docs.

**Closed by reynoldsalec** 2021-12-15 17:26 UTC
Labels: guide
