### ISSUE TITLE
lando does not start

### ISSUE THREAD

**Issue by quietone1** [lando/lando#660] opened 2018-01-21 05:01 UTC
I am following this: https://docs.devwithlando.io/tutorials/drupal8.html

What is your lando version and operating system? 
lando-v3.0.0-beta.35.deb 
Debian Stretch

**Tell us about your `.lando.yml`**
```
name: my-lando-app
recipe: drupal8
config:
  webroot: .
```

**Tell us about the command you were running**
```
cloned drupal8
lando init
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network c54b84f9ae94f1b58e33b69efa29411ca458cf794e407931a7785d7a396206ab (br-c54b84f9ae94): conflicts with network 6c25bf895a9447476ecad026b05c1d8f0d4f34246ccb745c63828e18d78db25e (br-6c25bf895a94): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network f979166c856a3e8e90b1abcb6232f3998e10525aacaf7ca0e75fa4cbb1effde6 (br-f979166c856a): conflicts with network 6c25bf895a9447476ecad026b05c1d8f0d4f34246ccb745c63828e18d78db25e (br-6c25bf895a94): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 6d6b1fe800923b4c3b56176a162e24c27dd8e320b6972ead00a2f50a9782044c (br-6d6b1fe80092): conflicts with network 6c25bf895a9447476ecad026b05c1d8f0d4f34246ccb745c63828e18d78db25e (br-6c25bf895a94): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 616d308ed2f7803e50902b4ce23d3a62672fd3f6eda81bacd9b84b854007beec (br-616d308ed2f7): conflicts with network 6c25bf895a9447476ecad026b05c1d8f0d4f34246ccb745c63828e18d78db25e (br-6c25bf895a94): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network d37e31a6a7714c785e283e881af68b6d5d620024aad95bdc05b45954bd050460 (br-d37e31a6a771): conflicts with network 6c25bf895a9447476ecad026b05c1d8f0d4f34246ccb745c63828e18d78db25e (br-6c25bf895a94): networks have overlapping IPv4
error:  Error: Error
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

**Comment by quietone1** [comment] 2018-01-22 21:13
On slack, dustinleblanc, asked if  `docker run hello-world` and `docker-compose` work?
Yes, they both work.

**Comment by serundeputy** [comment] 2018-01-22 21:35
Perhaps docker network prune;

**Comment by quietone1** [comment] 2018-01-22 23:22
Thanks for the idea but still doesn't start.
```
{~}$ docker network prune
WARNING! This will remove all networks not used by at least one container.
Are you sure you want to continue? [y/N] y
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network a562f86a0a77222a093260e10a236b6dced080692b17722bc2795b9c0b16b490 (br-a562f86a0a77): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 83e307a99fe3294327748f784c733778b043353b64240181c1a9e999e5607a64 (br-83e307a99fe3): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network f21bd982daf2c4f8eb7f5edba55db7738f18fb0eec4d3ca377ebb51a11038139 (br-f21bd982daf2): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 137375270ff91e4abec9c1d44c26a6e1e319a3fe876eb1ec2dfb40d0c465a2fe (br-137375270ff9): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network eb969b019b0df0e348866f64ee2376cf845d33a14b6f2b1d0db31ee4a6c7f06d (br-eb969b019b0d): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
error:  Error: Error
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by serundeputy** [comment] 2018-01-23 01:27
Can you please try lando rebuild;

**Comment by quietone1** [comment] 2018-01-23 20:22
@serundeputy, thank you. Same result. 

``
$ lando rebuild
? Are you sure you want to rebuild? Yes
Pulling appserver (devwithlando/php:7.1-apache)...
Pulling database (mysql:latest)...
appserver uses an image, skipping
database uses an image, skipping
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network ed88b94bd078a7cb0c4c9a0fcdd9ba529682c133468753ed88cfda8f0b1abeab (br-ed88b94bd078): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 10d613aee805b80fada8e5073033bfa8a4e5f2f6156df82a60d689eaa5aabf92 (br-10d613aee805): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network a4d156c52d54f663d4f696a9df27e1144fb15fbbed2d2638ee4e66db0d221c61 (br-a4d156c52d54): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 2e082dcb4f50fb95ee51b0536dd192712fd20ccbcce85f5fd6c528c741138493 (br-2e082dcb4f50): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
ERROR: cannot create network 3119672c78201ea2e15ffd5d8feb2665baf40437829102f9c74f91cdc83adcdc (br-3119672c7820): conflicts with network ba6b10b4d14487ad7212d9d9cb49f1f363b793064475c37e0ece9faa00ca23c5 (br-ba6b10b4d144): networks have overlapping IPv4
error:  Error: Error
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:0:0)
    at /snapshot/cli/lib/promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by quietone1** [comment] 2018-01-23 21:47
Talked to pirog on Slack and did the following.

Deleted the dev br-whatever
killed docker
restart docker
```
$ lando start
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "mylandoapp_default" with the default driver
Creating volume "mylandoapp_appserver" with default driver
Creating volume "mylandoapp_data" with default driver
Creating volume "mylandoapp_data_database" with default driver
Creating mylandoapp_appserver_1 ...
Creating mylandoapp_database_1 ...
Creating mylandoapp_appserver_1
Creating mylandoapp_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    342      0 --:--:--  0:00:01 --:--:--   342
100  267k  100  267k    0     0  67423      0  0:00:04  0:00:04 --:--:--  131k
Drush Launcher Version: 0.4.3
mv: cannot create regular file '/usr/local/bin/drush': Permission denied
error:  message=  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    342      0 --:--:--  0:00:01 --:--:--   342
100  267k  100  267k    0     0  67423      0  0:00:04  0:00:04 --:--:--  131k
Drush Launcher Version: 0.4.3
mv: cannot create regular file '/usr/local/bin/drush': Permission denied
, code=1
```

Found this issue, https://github.com/lando/lando/issues/493. The last entry suggested a simple lando stop/lando start helped them with wordpress. Tried that and it just hangs.
```
$ time lando stop
Stopping mylandoapp_database_1 ... done
Stopping mylandoapp_appserver_1 ... done
App stopped!

real    0m4.552s
user    0m1.744s
sys     0m0.120s
$ time lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting mylandoapp_appserver_1 ...
Starting mylandoapp_appserver_1
Starting mylandoapp_database_1 ...
Starting mylandoapp_appserver_1 ... done
^C

real    2m8.869s
user    0m5.800s
```

**Comment by quietone1** [comment] 2018-01-24 00:16
I shutdown the firewall, deleted the interface, lando stop, lando start and this time it worked.

```
$ time lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "mylandoapp_default" with the default driver
Starting mylandoapp_appserver_1 ...
Starting mylandoapp_appserver_1
Starting mylandoapp_database_1 ...
Starting mylandoapp_appserver_1 ... done

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            my-lando-app
 LOCATION        /home/me/projects/lando1/drupal
 SERVICES        appserver, database

 APPSERVER URLS  https://localhost:32768
                 http://localhost:32769
                 http://my-lando-app.lndo.site:8000
                 https://my-lando-app.lndo.site


real    0m11.857s
user    0m5.856s
sys     0m0.544s

```
Regarding the permission problem, I am not sure if the stop/start fixed it or it was the firewall. I have not made a test just for that.

I do have work to do to understand how to configure my firewall, but for now, I am satisfied that lando starts.

Thanks for the support on Slack!

**Comment by jsheffers** [comment] 2018-01-28 20:06
I'm getting the same issue here what was the solution?  I'm running lando latest beta 35 and Version 18.02.0-ce-rc1-mac50 (22256) of Docker.  Docker commands work just fine.  I've restarted docker, tried lando rebuild, still no dice.

**Comment by ajdavid** [comment] 2018-02-13 03:33
@jsheffers did you resolve your start problem?

My problem started this morning after months of operation,

I have done what was suggested above with respect to firewall, br-xxxxx devices etc; version checking, lando rebuild, checking docker is functioning etc
No success. I have a blow-by-blow set of notes if needed.
Latest attempt has the same result:
$ lando start
...
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... 
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network 95f5078a6f16702bf1eb2b769fb5e36b717899afc350d71c1010e724cc626209 not found
...

**Comment by dmsmidt** [comment] 2018-02-14 08:37
Leaving a note here that we are observing this strange behavior more and more in our company lately. This week already 5 ppl pinged me about the problem.

**Comment by ajdavid** [comment] 2018-02-15 22:41
grep for ^\* for steps taken to unsuccessfully investigate/resolve this
[lando-fail-notes.txt](https://github.com/lando/lando/files/1729633/lando-fail-notes.txt)

**Comment by ajdavid** [comment] 2018-02-19 22:01
Rather than updating this closed bug, I was going to open a new one.

lando start -- -vvv (for debugging)
It started!

There have been multiple restarts over the past week but no change to the failure until now.
Dependencies of docker-ce and lando have not been updated 
stopped and started successfully. Crossing fingers this is now resolved for me.

**Comment by MichaelRobertson93** [comment] 2018-02-19 23:10
I'm having the same problem, and it's only started happening recently.
Environment was fine and running well up until a couple days ago; Docker's also running completely fine.

Anyone got a solution for this?

**Comment by dmsmidt** [comment] 2018-02-20 10:35
The problem is easily reproducible: 
- `lando start` 
- Quit/Kill Docker for Mac
- Start Docker for Mac
-  `lando start` 
- Boom!

I can get an app running again after a `lando destroy` and a `docker rm landoproxyhyperion5000gandalfedition_proxy_1`.

After a normal 'lando poweroff' docker networks still exists for the proxy and apps (`docker network ls`). Also after restarting Docker for Mac. However when some containers are running and then Docker for Mac is restarted, all needed networks are gone.

Tested on Docker for Mac `Version 18.02.0-ce-mac53 (22617)` and Lando `v3.0.0-beta.35`.

**Comment by dmsmidt** [comment] 2018-02-20 19:49
@quietone1, @pirog or @serundeputy could you reopen this issue? I can't.

**Comment by honzahbf** [comment] 2018-02-21 08:55
On ubuntu 16.04 `docker rm landoproxyhyperion5000gandalfedition_proxy_1` helped me to ged rid of this error when starting lando app
Docker:18.02.0-ce
Lando:18.02.0-ce

**Comment by serundeputy** [comment] 2018-02-21 13:48
@dmsmidt i've reopened; thanks for the STR.

In light of those steps I'm not sure what can be done on the lando side though.
Maybe document your steps and add to known issues something like: 

> If you restart docker while lando has app(s) running. The networks for those apps will continue running and must be removed before you can `lando start` the apps in question again.

Some language like that along with your STR and solution? what do you think?

**Comment by Krilo89** [comment] 2018-03-01 14:32
@honzahbf , that's a temporary solution but the real problem stay's. Even after a restart of my computer, the problem appears. So before you restart your computer (for updates), you have to poweroff your Lando containers first. I hope there comes good fix for this problem.

Tested on Docker for Mac Version 18.02.0-ce-mac53 (22617) and Lando v3.0.0-beta.35

**Comment by honzahbf** [comment] 2018-03-02 08:38
@Krilo89 yes, i had to downgrade docker to:

> Docker version 17.12.1-ce, build 7390fc6

**Comment by dustinleblanc** [comment] 2018-03-14 01:23
@dmsmidt I can't reproduce on beta-35, here are my specs:

![image](https://user-images.githubusercontent.com/3948808/37378209-99a18624-2704-11e8-90e3-a2914e127a54.png)

Is anybody still experiencing this? I am going to mark unable to reproduce and move back to the backlog until a maintainer can reproduce.

**Comment by ajdavid** [comment] 2018-03-14 03:09
@honzahbf - Workaround by downgrading to  Docker version 17.12.1-ce, build 7390fc6 
@Krilo89 - lando stop before powering down worked for me, regardless of docker release. lando got into this state when I forgot to do the lando stop.
@dustinleblanc - the problem appeared for me using Docker version 18.02.0-ce, build fc4de44

**Comment by dustinleblanc** [comment] 2018-03-14 12:50
@ajdavid thanks for the additional contexts, I can test with that docker version I think, if that makes it replicable, I will likely call this a docker bug

**Comment by dustinleblanc** [comment] 2018-03-14 13:44
![image](https://user-images.githubusercontent.com/3948808/37405737-d05eb706-276b-11e8-9199-520f1ed93eec.png)

Still not reproducable on the latest edge release for me. I did the following per @dmsmidt:

1. `lando start` within a Pantheon app directory
2. Quit Docker for Mac
3. Start Docker for Mac
4. `lando start` within the app again

@dmsmidt can you still reproduce? Anyone else still getting this with beta 35? Still trying to isolate and reproduce so we can get it into a sprint and fix if there is still a bug out there

**Comment by paul94010** [comment] 2018-03-14 17:23
Yes, I have this problem also.   I trying to start a plain drupal 8 site.   Everything seems fine until “lando start” hangs.   No messages, nothing.

On 14 Mar 2018, at 6:44 AM, Dustin LeBlanc <notifications@github.com> wrote:

 <https://user-images.githubusercontent.com/3948808/37405737-d05eb706-276b-11e8-9199-520f1ed93eec.png>
Still not reproducable on the latest edge release for me. I did the following per @dmsmidt <https://github.com/dmsmidt>:

lando start within a Pantheon app directory
Quit Docker for Mac
Start Docker for Mac
lando start within the app again
@dmsmidt <https://github.com/dmsmidt> can you still reproduce? Anyone else still getting this with beta 35? Still trying to isolate and reproduce so we can get it into a sprint and fix if there is still a bug out there

**Comment by jsheffers** [comment] 2018-03-14 18:58
I'm also getting still getting this error, but it seems sporadic.  For example I started up one of my projects today and it worked, but sometimes if I don't touch it for a week and I come back to start it, I get this error.  I know that's not very helpful, but I think this is still present.

**Comment by dustinleblanc** [comment] 2018-03-14 19:06
@paul94010 Lando hanging is a different outcome than the one others are mentioning, so that might be a separate issue. @jsheffers Can you confirm your OS, Docker Version and Lando version. Does the issue happen only on vanilla D8 recipes?

@paul94010 if you get any error output let us know. If not, where does it hang? Lando can spend several minutes pulling images when it starts an app in circumstances where you don't have a cache of the images locally so that is a common place for it to look 'stuck'. If that's what is happening, we could definitely improve that UI

**Comment by pirog** [comment] 2018-03-14 19:15
@dustinleblanc @paul94010's issue was surfaced elsewhere but i think i closed it do to lack of reproducibility and feedback. feel free to reopen it @paul94010 if you have new info to help guide us in resolving it.

**Comment by philltran** [comment] 2018-03-21 18:01
I was experiencing the same issue with landoproxyhyperion5000gandalfedition_proxy_1 on Mac OS X 10.11.6. Even after reboot I was still getting the error - 

> "ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy"

Lando successfully started  after running a "lando destroy" and  "docker rm landoproxyhyperion5000gandalfedition_proxy_1"

Thanks for the work around. 

Lando : v3.0.0-beta.35
Docker: Version 18.03.0-ce-rc4-mac57 (23360)

**Comment by paul94010** [comment] 2018-03-22 00:14
Mike, I have tried the simplest possible install with lando and it still doesn’t start.  I must be misunderstanding the documentation because lando is working well with so many other users in so many complex environments.   Mine is very simple powerbook with nothing fancy installed.  (I did a clean re-install of the OS with a wiped disk.)

Here is the latest round.  Maybe you can see my mistake:

1.  Removed already installed lando by running  <uninstall> command script on the install package.

2.   Installed new lando from package on Github.

3.  Reset existing docker to “factory settings”.  Now running this version of docker:  Version 17.09.1-ce-mac42 (21090)  Channel: stable  3176a6af01

8.  Installed Lando for Drupal8 using the instructions at <https://docs.devwithlando.io/tutorials/drupal8.html>

Last login: Mon Mar 19 14:31:11 on ttys001
Paul-Powerbook:~ paul$ ls
Desktop		Downloads	Music		Sites
Desktop alias	Library		PIX		dwhelper
Documents	Movies		Pictures	installer.phar
Paul-Powerbook:~ paul$ cd Sites
Paul-Powerbook:Sites paul$ mkdir drupal8
Paul-Powerbook:Sites paul$ cd drupal8
Paul-Powerbook:drupal8 paul$ ls
Paul-Powerbook:drupal8 paul$ lando init
? What recipe do you want to use? drupal8
? Where is your webroot relative to the init destination? web
? What do you want to call this app? landod-8

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run
`lando start` to get rolling.

Check the LOCATION printed below if you are unsure where to go.

Here are some vitals:

 NAME      landod-8                                            
 LOCATION  /Users/paul/Sites/drupal8                           
 RECIPE    drupal8                                             
 DOCS      https://docs.devwithlando.io/tutorials/drupal8.html 

Paul-Powerbook:drupal8 paul$

9. Here is the resulting .lando.yml

name: landod-8
recipe: drupal8
config:
  webroot: web

10.  Finally I run <lando start>

Paul-Powerbook:drupal8 paul$ lando start -vvvv

Nothing happens.  terminal goes dead.

11.  Next I tried to remove lando and re-install.

Paul-Powerbook:drupal8 paul$ lando destroy


There is an update available!!!
Install it to get the latest and greatest


Updating helps us provide the best support
https://github.com/lando/lando/releases/tag/v3.0.0-beta.37


? Are you sure you want to DESTROY? Yes
Stopping landod8_appserver_1 ... done
Removing landod8_appserver_1 ... done
Removing network landod8_default
Removing volume landod8_appserver
Removing volume landod8_data
Removing volume landod8_data_database
App destroyed!
Paul-Powerbook:drupal8 paul$ lando rebuild


There is an update available!!!
Install it to get the latest and greatest


Updating helps us provide the best support
https://github.com/lando/lando/releases/tag/v3.0.0-beta.37


? Are you sure you want to rebuild? Yes
Pulling appserver (devwithlando/php:7.1-apache)...
Pulling database (mysql:latest)...
appserver uses an image, skipping
database uses an image, skipping

Again, terminal hangs.

Crazy, right?

Here is the OS environment:

MacOS High Sierra version 10.13.3

Docker environment:

Version 17.09.1-ce-mac42 (21090)
Channel: stable
3176a6af01

Here are the machine variables:

 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,1
  Processor Name:	Intel Core i5
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	8 GB
  Boot ROM Version:	MBP111.0142.B00
  SMC Version (system):	2.16f68


On 14 Mar 2018, at 12:15 PM, Mike Pirog <notifications@github.com> wrote:

@dustinleblanc <https://github.com/dustinleblanc> @paul94010 <https://github.com/paul94010>'s issue was surfaced elsewhere but i think i closed it do to lack of reproducibility and feedback. feel free to reopen it @paul94010 <https://github.com/paul94010> if you have new info to help guide us in resolving it.

**Comment by pirog** [comment] 2018-03-30 03:26
@paul94010 word on the street is that you've figure this one out! dying to hear what it was!

**Comment by Etroid** [comment] 2018-04-03 19:06
Running into the same issue as of this morning. Funny thing is it was working earlier this week...

Lando: v3.0.0-beta.39-26-g787e
Docker: 18.03.0-ce-mac60

**Comment by dustinleblanc** [comment] 2018-04-03 19:09
@Etroid do you have vagrant running @paul94010 did?

**Comment by Etroid** [comment] 2018-04-03 19:12
@dustinleblanc I do not.

**Comment by explorier** [comment] 2018-04-03 22:41
I've gotten this error as well, to be specific here's how it looks for me:
`ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (7c7d91245f36ea45bf5f7721f08c49ae40f453f21c7ca5c0ee084f76d580968d): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use`

Eventually I found this solution:

`sudo netstat -nlp | grep docker`
then look for the PIDs attached to ports 80 and 443 and run
`sudo kill {PID}`

This works for me using Lando v3.0.0-beta.35 on Ubuntu 16.04.3. I had to downgrade from the most recent Lando versions due to a bug.

**Comment by paul94010** [comment] 2018-04-04 14:50
Mike, I have continued to try to get lando to work for me.   I believe I have removed all the conflicting environment apps that were causing problems, including vagrant and all the anti-virus software.   However, I still have not be able to install a site using lando.   

I have written up each attempt but I am reluctant to submit these as “bugs”.   Obviously there something unusual in what I am doing.   I am viewing my problems as a mis-understanding of how lando fundamentally works.   Is there a description of the architecture and what is happening “under the covers”?

Is there a place where general “newbie” problems should be raised?   I don’t want to bother you busy developers.  

Paul

On 14 Mar 2018, at 12:15 PM, Mike Pirog <notifications@github.com> wrote:

@dustinleblanc <https://github.com/dustinleblanc> @paul94010 <https://github.com/paul94010>'s issue was surfaced elsewhere but i think i closed it do to lack of reproducibility and feedback. feel free to reopen it @paul94010 <https://github.com/paul94010> if you have new info to help guide us in resolving it.

**Comment by dustinleblanc** [comment] 2018-04-04 15:07
Hey @paul94010 

The overview of the architecure is really just that we use Docker and Docker Compose to handle all of the app spinup, networking, and routing, with a thin wrapper of NodeJS code to handle some things like tooling and the generation of the Docker-Compose files.

There is also a proxy that is run inside Docker using Traefik to provide nice pretty URLs for accessing sites. You can disable the proxy to troubleshoot if it causes issues
```sh
# Edit the config
echo "proxy: 'OFF'" >> ~/.lando/config.yml

# Poweroff lando
lando poweroff

# Reboot an app
lando start SOMEAPP
```

Otherwise, when it comes to app runtime, this is pretty much vanilla Docker Compose. You can check the compose files in your `~/.lando/compose` directory to see what we are generating

**Comment by makbeta** [comment] 2018-05-10 00:33
I uninstalled and then reinstalled Lando and Docker and that seemed to have solved the issue for me.

**Comment by protitude** [comment] 2018-05-15 00:53
So for me I upgraded lando which then started this issue for me. 

I used @dustinleblanc temporary fix above, though using localhost with rotating ports wasn't ideal. I tried @makbeta solution above and still didn't get the result I wanted, but then I realized just uninstalling Lando didn't get rid of my local lando folder with all of my settings. On macOS you can find it at ```~/.lando``` so I uninstalled lando, moved that folder to my desktop and re-installed lando. After a lando start my issue appeared to be fixed.

**Comment by dustinleblanc** [comment] 2018-05-15 13:32
@protitude ah yeah, nuking the `~/.lando` was suggested in our release note for several of the latest upgrades because of some changes we made, so glad to hear that worked.

**Closed** 2018-05-15 13:33 UTC
Labels: can not replicate, documentation, pantheon
