### ISSUE TITLE
D8/Nginx 404s on RC10

### ISSUE THREAD

**Issue by dustinleblanc** [lando/lando#1478] opened 2019-02-20 14:22 UTC
Last night I upgraded to RC10 and had a few failures on a D8/Nginx app on Platform.sh. 

1. Immediately after upgrading I had some random Docker error messages. I didn't capture these messages and factory reset docker.
2. After getting back up and running, some of our Node build steps were failing
3. The site was throwing a nginx 404 after it finally came back up

Downgrading to RC9 fixed the issue for me. Also, interestingly, RC10 told me it was _downgrading_ Lando when I installed it using Eddy (though RC10 was reported correctly from the CLI).

**Comment by lslinnet** [comment] 2019-02-20 14:23
Was just about to report the exact same issue, digging into it it seems the nginx configuration used in lando doesn't support "pretty" urls.

**Comment by dustinleblanc** [comment] 2019-02-20 14:24
Thanks @lslinnet!

**Comment by pirog** [comment] 2019-02-20 14:44
Yah i can confirm this. Looks like a regression caused by consolidating our config file loading. I'm going to roll a hotfix release for this one

**Comment by pirog** [comment] 2019-02-20 15:03
Alright this should be fixed in 
https://github.com/lando/lando/releases/tag/v3.0.0-rc.11

Might take 10 minutes or so for all the released to build and show up. @dustinleblanc if you could confirm that resolves your issue and then close this out that would be appreciated.

**Closed** 2019-02-20 21:55 UTC
Labels: bug
