### ISSUE TITLE
Feature request: Combine block sequences together in a single request

### ISSUE THREAD

**Issue by uberhacker** [lando/lando#1878] opened 2019-11-29 21:17 UTC
Currently, if a block sequence of commands is specified in `.lando.yml`, each command runs in a separate container instance that requires stopping and restarting.  With only a handful of commands, this is not really a problem but when there are 3 or more commands, it can start to slow down the startup process.  I know it's possible to combine all the commands together in a single script and call that but it would be nice if you could do this in `.lando.yml`.  Below is a simple example:
```yaml
name: mysite
recipe: drupal8
config:
  webroot: web 
services:
  appserver:
    build_as_root:
      - apt update
      - apt install vim -y
```
This generates output as follows:
```
Stopping mysite_appserver_1 ... done
Starting mysite_appserver_1 ... done
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease                     
Hit:3 http://apt.postgresql.org/pub/repos/apt stretch-pgdg InRelease     
Hit:4 http://deb.debian.org/debian stretch-updates InRelease
Hit:5 http://deb.debian.org/debian stretch Release 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Stopping mysite_appserver_1 ... done
Starting mysite_appserver_1 ... done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgpm2 vim-common vim-runtime xxd
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime xxd
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 6769 kB of archives.
After this operation, 31.2 MB of additional disk space will be used.
```
Notice the Stopping and Starting lines:
```
Stopping mysite_appserver_1 ... done
Starting mysite_appserver_1 ... done
```

**Comment by uberhacker** [comment] 2020-01-05 23:50
Unstale

**Comment by pirog** [comment] 2020-03-05 20:19
@uberhacker definitely agreed. this was a regression introduced by a fix we did for the `mysql` container which required a proper shutdown, as a consequence all other containers shutdowns became much slower. I'm going to address this as part of #2013 but generally i think the improvements we want to make are

1. Allow us to specify whether containers require a "safe" shutdown or not and then only safe shutdown those that need it
2. Do not run each build step in a separate container, boot up the container, run all the build steps in that container, and then turn off the container

This should considerably speed up builds and rebuilds, particularly if there are many steps and it should also speed up shutdown/startup. Going to close this out since im tracking this in #2013

**Closed by pirog** 2020-03-05 20:19 UTC
Labels: feature
