### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by raupie** [lando/lando#3372] opened 2022-04-07 19:56 UTC
``
(base)    ~  lando version
dov3.6.2
(base)    ~  docker --version
Docker version 20.10.14, build a224086
```

```
lando start --vvvv
Let's get this party started! Starting app drupal9...
ERROR ==> Cannot read property 'split' of undefined message=Cannot read property 'split' of undefined, stack=TypeError: Cannot read property 'split' of undefined
    at /snapshot/cli/node_modules/@lando/platformsh/lib/config.js
    at arrayMap (/snapshot/cli/node_modules/lodash/lodash.js:653:23)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at interceptor (/snapshot/cli/node_modules/lodash/lodash.js:17094:35)
    at Function.thru (/snapshot/cli/node_modules/lodash/lodash.js:8859:14)
    at /snapshot/cli/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/snapshot/cli/node_modules/lodash/lodash.js:697:21)
    at baseWrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:4429:14)
    at LodashWrapper.wrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:9114:14)
    at Object.getSyncableRelationships (/snapshot/cli/node_modules/@lando/platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/platformsh/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.init (/snapshot/cli/lib/app.js)
    at initAndReport (/snapshot/cli/lib/app.js)
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==> Cannot read property 'split' of undefined 
```

I'm dead in the water.

**Comment by reynoldsalec** [comment] 2022-04-07 20:13
Duplicate of https://github.com/lando/platformsh/issues/48.

**Closed by reynoldsalec** 2022-04-07 20:13 UTC
