### ISSUE TITLE
Permissions error and drush failure on beta40 in elementaryOS

### ISSUE THREAD

**Issue by bmcclure** [lando/lando#887] opened 2018-04-10 23:18 UTC
**Tell us about your setup**

v3.0.0-beta40 on elementaryOS Loki.

**Tell us about your `.lando.yml`**

.lando.yml:
```yml
name: myapp
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: myapp
  id: [redacted]
  xdebug: true
```

pantheon.yml:
```yml
api_version: 1

php_version: 7.0
drush_version: 8
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
# Clone git repo with my .lando.yml as above
lando start
# composer.json permissions Error comes up
lando drush cr
# drush error comes up
lando rebuild
# composer.json permissions Error comes up
```

**Tell us about the error you got**

```bash
lando rebuild -- -vvvv
```

Tail of the lines leading up to the error:
```
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
debug: Retrieved from memcache with key engineup
debug: Trying to retrieve from file cache with key myapp.last_build
debug: File cache miss with key myapp.last_build
debug: Retrieved from memcache with key engineup
verbose: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
Pantheon pre-run scripting
Setting up client key /lando/keys/pantheon/myapp/cert.pem
Changed current directory to /var/www/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
verbose: Error {"message":"\u001b[32mChanged current directory to /var/www/.composer\u001b[39m\r\n\r\n\u001b[37;41m                                                                                \u001b[39;49m\r\n\u001b[37;41m  [ErrorException]                                                              \u001b[39;49m\r\n\u001b[37;41m  file_put_contents(./composer.json): failed to open stream: Permission denied  \u001b[39;49m\r\n\u001b[37;41m                                                                                \u001b[39;49m\r\n\r\n\u001b[32mrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [\u001b[39m\u001b[32m<packages>\u001b[39m\u001b[32m]...\u001b[39m\r\n\r\n","code":1}
```

**Tell us generally about your bug**

I updated to beta40, and have been experiencing these permissions issues trying to rebuild (or start from scratch) my D8 site from Pantheon.

After this error occurs, the application starts, but drush fails with `/bin/sh: 1: drush: not found`.

Sometimes, if I now run `lando restart`, composer will install prestissimo and I'm not sure what else and things seem to work. Except if I try to rebuild again, the error occurs again.

Reproduction steps:
```bash
1. Updated from beta35 (I think) to beta40
2. Opened a terminal and went to my existing application's directory (a d8 pantheon app)
3. Ran `lando rebuild` and this error occurred
4. Ran `lando destroy`
5. Verified ownership and permissions of all files in the app directory and in ~/.lando. All looked good.
6. Deleted files from within ~/.lando related to that application
7. Went back to the app directory and ran `lando start` and received the error again.
```

**Comment by dustinleblanc** [comment] 2018-04-22 01:33
@bmcclure did you ever get around this? I have run several installs on both elementary and ubuntu and haven't run across this. I'd recommend completely uninstalling docker and lando, rebooting the machine, and starting the install again. Going to close this as can't reproduce for now, but if it keeps coming up, let us know. thanks!

**Closed by dustinleblanc** 2018-04-22 01:33 UTC
Labels: can not replicate

**Comment by bmcclure** [comment] 2018-05-02 03:45
@dustinleblanc This is still occurring.

I've gone so far as to delete lando, delete my ~/.lando directory, delete all containers, images, and volumes from docker, completely uninstall docker-ce and delete /var/lib/docker, and reinstall the latest version of Lando.

Upon trying to start my first application, I'm still faced with the same issue:

```
Pantheon pre-run scripting
Setting up client key /lando/keys/pantheon/truepartners/cert.pem
Changed current directory to /var/www/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

**Comment by bmcclure** [comment] 2018-05-02 04:13
Also, I can't tell if this is related or not, but at the same time this problem started happening, I started noticing that new "files" (uploads) pulled down from Pantheon return a 404 when trying to visit the file's URL. Existing files from before this issue continue to work, but I can't find a way to get the website to see any new files even though they exist in my local machine's uploads dir.

**Comment by RichardDavies** [comment] 2018-05-09 21:35
I've been experiencing this issue too with a Pantheon recipe (along with several other members of my team). I'm running beta 44 and my team members are running beta 40 and 43. Basically we get the Composer error mentioned above whenever we run `lando rebuild` and then `lando drush` doesn't work. But if we run `lando start` Composer doesn't error and `lando drush` will work.

**Comment by dustinleblanc** [comment] 2018-05-10 12:16
Thanks @bmcclure @RichardDavies. SO one thing we seem to know is that there is some sort of goofy permissions issue for some folks when installing Composer deps on build, so the plan of attack is to stop doing that and to ship the helpers we install in the images instead, thanks for your patience all!

**Comment by RichardDavies** [comment] 2018-05-10 15:48
@dustinleblanc It certainly does seem like there's some sort of permissions issue at play here... but if `lando start` can successfully navigate the permission issue and run Composer, why can't `lando rebuild`? It seems like rebuild is doing something slightly different that is causing issues.

Also, why is this issue marked as closed if it's obviously not resolved and still an issue?
