### ISSUE TITLE
Extra "app" symlink showing up in project after a rebuild

### ISSUE THREAD

**Issue by bmcclure** [lando/lando#1043] opened 2018-06-13 23:26 UTC
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.47 on elementaryOS Loki

**Tell us about your `.lando.yml`**

```yml
name: mysite
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: mysite
  id: c4d05745-2c4a-4127-9b54-2a09905a5292
  xdebug: true
```
pantheon.yml:
```yml
api_version: 1
php_version: 7.0
drush_version: 8
```

**Tell us about the command you were running**

```bash
lando rebuild -y
```

**Tell us about the error you got**

In this case, there is no error, but just an extra symlink showing up in the code.

**Tell us generally about your bug**

It seems like rebuilding the app as of one of the most recent Lando releases also adds a new "app" symlink to the code directory which points to `/app`. It shows up as a new file in the git repository and is easy to accidentally commit if you don't watch out for it. Deleting the file doesn't seem to break anything.

**Comment by jcandan** [comment] 2018-07-23 20:05
I see `app -> /app` as well, but not with a `lando rebuild`. It shows up after a `lando pull` for me.

**Comment by seanr** [comment] 2018-08-02 22:54
I see this on rebuild as well.

**Comment by neclimdul** [comment] 2018-08-03 18:54
comes from here though I don't know why its there.

https://github.com/lando/lando/blob/master/plugins/lando-recipes/recipes/pantheon/pantheon.sh#L24

**Comment by truls1502** [comment] 2018-08-06 20:49
I can confirm @seanr 's comment where I have already added it to .gitignore and it works fine.

**Comment by bmcclure** [comment] 2018-08-08 17:14
I'm not sure I understand the reasoning behind leaving this behavior in. This isn't really mimicking Pantheon's behavior, because you don't end up with an "app" symlink inside the code directory on Pantheon.

Yes, adding it to .gitignore works, but I am not in agreement about that being the best solution.

**Comment by pirog** [comment] 2019-01-13 00:17
@bmcclure it mimics pantheons behavior because `$HOME/code` should point to your applications code, which is `/app` on lando. 

The issue is basically symlink transitivity so it works fine the first time but subsequent times its resolving the `/var/www/code` to `/app` and you end up with `/app` -> `/app`. 

That said this should be fixed in forthcoming rc2

**Closed by pirog** 2019-01-13 00:17 UTC
