### ISSUE TITLE
New version disturbs drush output

### ISSUE THREAD

**Issue by parijke** [lando/lando#1011] opened 2018-06-03 10:06 UTC
Running:
lando drush sql-dump > ./config/sync/dump.sql

results in invalid SQL when there's a new version available. This is added to the header:

There is an update available!!!
Install it to get the latest and greatest

Updating helps us provide the best support.
https://github.com/lando/lando/releases/tag/v3.0.0-beta.47

-- MySQL dump 10.13  Distrib 5.5.60, for debian-linux-gnu (x86_64)
--
-- Host: database    Database: drupal8
-- ------------------------------------------------------
-- Server version       5.7.22

**Comment by parijke** [comment] 2018-06-03 10:14
Workaround:
lando db-export --stdout > ./config/sync/dump.sql

**Comment by pirog** [comment] 2018-06-04 12:46
@parijke this is by design. we want you to upgrade!

going to close this in favor of #1000

**Closed by pirog** 2018-06-04 12:46 UTC
