### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN after a some time

### ISSUE THREAD

**Issue by edwinsiebel** [lando/lando#1201] opened 2018-09-18 19:49 UTC
What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-beta.47 on Ubuntu 18.04*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: test
recipe: wordpress

config:
    type: php:7.0
    via: nginx:1.13
    ssl: true
    webroot: htdocs
    xdebug: true

    conf:
      server: provision/nginx/default.conf

proxy:
  web:
  mailhog:
    - mail.test.lndo.site
  pma:
    - pma.test.lndo.site

services:
  web:
    type: php:7.0
  pma:
    type: phpmyadmin:4.6
    ssl: true
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  redis:
    type: redis:4.0
    portforward: 6380
    persist: true
  database:
    type: mariadb
    config:
      confd: provision/mysql

  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

    overrides:
      services:
        environment:
          environment: 'development'
          DB_HOST: 'database'

    config:
      conf: provision/php/php.ini

    environment:
      - environment=development
      - DB_HOST=database

  node:
    type: node:6.10

    globals:
      webpack: "latest"
      npm: "latest"
      yarn: "latest"

tooling:
  deploy:
    service: appserver
    cmd: ./vendor/bin/dep deploy
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"

  webpack:
    service: node
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

Lando starts perfect, nginx/database/redis/etc works perfect. However, after some time, Chrome give met the DNS_PROBE_FINISHED_NXDOMAIN error, and the page cannot be displayed anymore. Lando ssh, for example, still works.

**Tell us generally about your bug**

Lando starts perfect, nginx/database/redis/etc works perfect. However, after some time, Chrome give met the DNS_PROBE_FINISHED_NXDOMAIN error, and the page cannot be displayed anymore. Lando ssh, for example, still works.
So, this must be something related to DNS. 

Looking at the landoproxyhyperion/traefik container, no errors are shown.
A ```lando poweroff``` and a ```lando start``` will not result in success: nginx fails to start (however, in the logs nothing special is visible).
I have to do a reboot of the system to fix the problem.

Never had this before, but got a new laptop, and this recently appears.

**Comment by dustinleblanc** [comment] 2018-09-18 22:30
@edwinsiebel I assume you are accessing test.lndo.site and getting this error? If so, this is caused by your DNS not finding *.lndo.site. We rely on a real proxy on the internet, make sure you aren't falling prey to https://docs.devwithlando.io/issues/dns-rebind.html. If all else fails, use Google's DNS, or Cloudflare's or something.

**Comment by edwinsiebel** [comment] 2018-09-19 07:13
Hi @dustinleblanc,

Thanks for the reply.

I'm accessing and working perfectly with test.lndo.site. Started test.lndo.site about half an hour ago, and it worked perfect.

However, I have been debugging just now, and the above mentioned error appeared again.

```
nslookup test.lndo.site

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
*** Can't find test.lndo.site: No answer
```

I can access any other (live) site, however, any *.lndo.site not anymore.

Can I try to access your real proxy, just to see if that works? What is that address?

**Comment by edwinsiebel** [comment] 2018-09-19 20:47
It occured again, however, now at home (while the above occured at work).

However, when I put ```12.7.0.0.1     test.lndo.site``` in my /etc/hosts everything works again.

Do you know any workaround to fix this?

**Comment by dustinleblanc** [comment] 2018-09-20 13:07
@edwinsiebel the best workaround I've ever seen is to use a rock solid reliable DNS provider for your machine. Google's DNS (8.8.8.8) and Cloudflare's (1.1.1.1) have always proven to be quite reliable for resolving any hostnames I've seen people struggle with, including the .lndo.site one as well as Pantheon's dev site hostnames. I'd recommend that as your most solid work around. If that gives you trouble, your hosts hack and/or following the [offline dev docs](https://docs.devwithlando.io/tutorials/offline-dev.html) can work too.

Going to go ahead and close this out, let us know if you have further issues, catch us on Slack if you want to chat, thanks!

**Closed by dustinleblanc** 2018-09-20 13:07 UTC
