### ISSUE TITLE
add a mac and windows binary that doesn't have docker install on them in the releases page ?

### ISSUE THREAD

**Issue by souhaiebtar** [lando/lando#2213] opened 2020-05-04 14:24 UTC
Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

**Please explain your request and its importance in the form of a user story.**

i always try to get the install the latest version of lando, but the download for mac and windows are very big because they integrate docker install with it,(which is already installed), would you please add an other entry in the releases page that contain only the binary that i can copy manually, for example for mac the files that goes under `/usr/local/bin`, in the end thanks for your great work,

**Please provide some detail on how lando can help solve this problem**

*Example: Place an option on the "site pull" screen to exclude cache tables.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pirog** [comment] 2020-05-04 14:30
@souhaiebtar this is a duplicate of https://github.com/lando/lando/issues/2169.

**Closed by pirog** 2020-05-04 14:30 UTC
Labels: feature
