### ISSUE TITLE
lando init --source=pantheon and subsequent lando pull will not pull live Pantheon database

### ISSUE THREAD

**Issue by JohnVieth** [lando/lando#2568] opened 2020-08-17 18:43 UTC
lando init --source=pantheon and subsequent lando pull will not pull live Pantheon database. When I do a lando pull, I select none for code and files, and only update the database, choosing "live" for database, but lando always pulls the dev database from my pantheon project. I have destroyed my lando/Docker containers, uninstalled lando and Docker Desktop using the official uninstallers, restarted, reinstalled, and re-init, and re-pull, and I continue to get the same result. This always used to work until I upgraded to the latest stable release of lando.

Docker version: 2.3.0.3 (45519)
Lando version: v3.0.9

**Comment by KurtTrowbridge** [comment] 2020-08-18 12:09
Just noticed this on two projects here as well since having updated to v3.0.11 last week; they've been existing Lando projects for a while. `lando pull` with only a database pull from `live` results in the `sql-dump` pulling from the `dev` environment:

```
Making sure your site is awake...
 [notice] OK >> live-site-name.pantheonsite.io responded
Pulling your database... This miiiiight take a minute
 [notice] Command: site-name.dev -- drush sql-dump [Exit: 0] 
```

Docker version: 2.3.0.4 (46911)
Lando version: v3.0.11

**Comment by xaqrox** [comment] 2020-08-18 16:07
Can confirm this with same versions as @KurtTrowbridge. Been happening for a couple weeks now... Would it be helpful to test older versions?

**Comment by JohnVieth** [comment] 2020-08-18 16:16
I can't upgrade my environment rightnow due to deadlines, but it's nice
that @KurtTrowbridge and I are both experiencing this issue in v3.0.9 and
later. Hard to know what version this glitch first appeared, but it's clear
a recent phenomenon. This had always worked perfectly for me in the past.
-JV

**Comment by xaqrox** [comment] 2020-08-18 16:19
I have a colleague still on v3.0.5 that seems to be able to do this successfully. I'm going to try a downgrade to see for myself.

**Comment by xaqrox** [comment] 2020-08-18 16:20
Wonder if it has to do with #2402 which came in in v3.0.8...?

**Comment by xaqrox** [comment] 2020-08-18 16:33
v3.0.5 works. bisecting...

**Comment by xaqrox** [comment] 2020-08-18 17:14
v3.0.7 also worked as expected, but v3.0.8 did not, so looks like that's when this was introduced. I'm afraid I'm not set up to do an actual `git bisect` to find the commit with the regression, but that'd be the next step... or if @pirog happens to know exactly what happened here, that would work too :wink:

_a few minutes later..._

I looked at the source and it doesn't look like the `site.env` is included at any point. I'm gonna try a fix...

https://github.com/lando/lando/blob/9deade963e9f4ca5df80ff9370911891ea7a7abd/integrations/lando-pantheon/lib/pull.js#L72-L81

https://github.com/lando/lando/blob/9deade963e9f4ca5df80ff9370911891ea7a7abd/integrations/lando-pantheon/scripts/pull.sh#L131

https://github.com/lando/lando/blob/9deade963e9f4ca5df80ff9370911891ea7a7abd/integrations/lando-pantheon/scripts/pull.sh#L163

**Comment by xaqrox** [comment] 2020-08-18 19:29
I may not get to this for a couple days so if anyone else has a fix in mind go for it.

**Comment by xaqrox** [comment] 2020-08-25 17:34
Pull request is up, if anyone has the bandwidth to test, that'd be great!

**Comment by pirog** [comment] 2020-09-24 16:05
@xaqrox very nice! merged this in!

**Closed by pirog** 2020-09-24 16:05 UTC
Labels: bug
