### ISSUE TITLE
Recoverable fatal error after switching to php 7.2

### ISSUE THREAD

**Issue by robbdavis** [lando/lando#747] opened 2018-03-09 18:16 UTC
**My set up**
v3.0.0-beta.35 - Mac OS - Sierra

**My `.lando.yml`**
Pantheon recipe - drupal8 framework

After switching to PHP 7.2 I'm getting the following error:

> PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0

I've switched back to php 7.1 and the error goes away. Drupal is recommending php7.2 now for version 8.5 so this is probably an issue that will become more common as people try updating.

**Comment by pirog** [comment] 2018-03-15 07:15
@robbdavis is this a problem with lando iself? seems like this is something triggered by your app's code?

**Comment by robbdavis** [comment] 2018-03-16 16:41
The app is Drupal 8.5. It runs fine on php7.1 but throws this error with php7.2. I also didn't see any errors when I ran the same codebase on Pantheon using php7.2.  That said, maybe I didn't look hard enough. When I get a chance, I'll do some tests again with php7.2 and re-check the pantheon logs.

**Comment by dustinleblanc** [comment] 2018-03-18 13:18
I'll test this out @pirog. However, Its not an error I see on Pantheon, so I'd imagine if I can repro, we have something goofy going on here.

Google brought this up in a search https://github.com/php/php-src/blob/master/ext/session/tests/session_set_save_handler_class_014.phpt

**Comment by dustinleblanc** [comment] 2018-03-18 13:27
Can confirm this happens when altering the php value in pantheon.yml:

![image](https://user-images.githubusercontent.com/3948808/37566371-8a4e7d3e-2a8e-11e8-89fa-afd35e0628df.png)

**Comment by dustinleblanc** [comment] 2018-03-18 13:45
I can confirm this doesn't happen in Drupal 8 recipe

**Comment by pirog** [comment] 2018-03-19 19:47
@robbdavis @dustinleblanc i suspect this is because the pantheon php image is still on an older version of php (eg 7.2.1). I'm going to rebase the images and im *guessing* that might eb sufficient to close this out.

**Comment by robbdavis** [comment] 2018-03-20 15:54
Thanks for hunting this down @dustinleblanc and @pirog!

**Comment by pirog** [comment] 2018-03-20 21:59
@dustinleblanc if you can confirm a `lando rebuild` updates to the latest `7.2.3` then feel free to close this out

**Comment by dustinleblanc** [comment] 2018-03-20 22:26
@pirog not working on my latest pull of master. still causing the same error to dump to stderr/stdout but it 7.2.3

```sh
Setting up client key /lando/keys/pantheon/bethanys-art-shop/index.pem
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4454k  100 4454k    0     0  2275k      0  0:00:01  0:00:01 --:--:-- 2275k
PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0
OS:	Linux 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64
Shell:
PHP binary:	/usr/local/bin/php
PHP version:	7.2.3
php.ini used:
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/tmp
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	1.5.0
/bin/sh: 1: drush: not found
error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

**Comment by pirog** [comment] 2018-03-20 22:30
you might need to `lando rebuild` since i just updated the images for master

**Comment by dustinleblanc** [comment] 2018-03-21 09:47
rebuilding off master this morning

**Comment by dustinleblanc** [comment] 2018-03-21 17:10
I am starting on #742 and I think I can lump this in there with it as I will be mucking with the recipe

**Comment by shaal** [comment] 2018-03-27 17:55
Same here, running lando35, Drupal 8.5, with pantheon recipe.
Got that error as above.

After I updated pantheon.yml to php7.1 and set composer.json to use PHP 7.1, the error disappeared and it's working without an error.

**Comment by mmwebaze** [comment] 2018-03-28 00:00
I am getting the same error with lando v3.0.0-beta.35, Drupal 8.5 and pantheon recipe

**Comment by pirog** [comment] 2018-03-28 16:03
We are definitely working on this but it's also worth mentioning that you SHOULD be able to safely ignore this reported error

**Comment by dustinleblanc** [comment] 2018-03-30 16:38
This is reproducible on Pantheon with PHP 7.2. At this point, I am going to call this an upstream bug, no fix from Lando. We simply surface the bug.

**Comment by truls1502** [comment] 2018-06-28 09:20
I still face it, it would be good to resolve the issue if it is possible. It is annoying for us who got such messages when we have upgraded PHP to 7.2

**Comment by pirog** [comment] 2018-06-28 09:44
I think there are more pressing issues to deal with than a **_recoverable_** fatal error that happens on one php version of one recipe that happens to "annoy" you.

**Comment by truls1502** [comment] 2018-06-28 10:57
I understand you @pirog - but would it not be great to post a **known issue** on https://docs.devwithlando.io/services/php.html regarding with the Pantheon recipe? So it can help the developers with less of a waste of the time to troubleshoot for this one issue. 😊

**Comment by pirog** [comment] 2018-06-28 11:13
Pretty sure this issue thread does that already.

**Comment by truls1502** [comment] 2018-07-03 11:50
I still keep getting the error such as: 
`PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0`

Could anyone help me to point out what the problem with it is?

**Comment by alphex** [comment] 2018-07-07 17:50
@truls1502 read this thread - its a non error, error... more annoying than anything else.

**Comment by robbdavis** [comment] 2018-07-07 18:39
I've learned to just live with it but "it's just annoying so leave it" isn't really a good approach. It is very annoying; it pops up twice every singe time I run a drush command. 

Have we determined it is coming from Pantheon? If someone gives me some details on how/why this is coming from Pantheon, I'll contact them.

All that said, version v3.0.0-beta.47 has been otherwise running flawlessly for me so I'm not complaining!

**Comment by pirog** [comment] 2018-07-09 06:45
@robbdavis to be fair, im not sure anyone here is legitimately advocating "it's just annoying so leave it" as the solution. Seems like the summary of this thread is essentially:

1. This is an upstream issue that also exists on Pantheon (although its harder to spot because you dont really see the logs like you do in lando) so while its something that **could** be fixed in Lando its **probably** better if its addressed on Pantheon first and then rolled into lando
2. There are other this-is-blocking-my-dev problems with Lando that are higher priority than this issue which while "annoying" is not really a show stopper.

**Comment by aekong** [comment] 2018-08-17 18:15
i'm having problems running phpunit _i think_ because of this exception.  phpunit catches it and errors out my very simple test.

**Comment by dustinleblanc** [comment] 2018-08-30 16:55
Just dropping a note here from today's slack convo, this is still occasionally getting thrown on Pantheon too, so still considered an upstream bug

**Comment by colinlord** [comment] 2018-09-04 21:15
Just chiming in to say that I'm also experiencing this same error like others have documented above.

**Comment by amklose** [comment] 2018-09-06 16:06
I realize it's not a critical issue but I just want to report that I'm getting the error on a Pantheon wordpress site as well, which would make sense since it's also using the pantheon recipe with php 7.2.

**Comment by dustinleblanc** [comment] 2018-09-06 16:54
Going to go ahead and lock conversation on this, we already have this identified as an upstream bug, if anyone wants to chime in on it, jump on over to slack.

**Closed** 2019-01-28 21:33 UTC
Labels: pantheon, upstream bug
