### ISSUE TITLE
Lando pull validating git repo as valid environment

### ISSUE THREAD

**Issue by sdubois** [lando/lando#2208] opened 2020-05-03 23:09 UTC
I have a project that is hosted on Pantheon, but I am using a Gitlab repo for development.

When I am on a branch of this repo and I run "lando pull" to copy the live database to my local evironment, the process ends while trying to verify my current branch as a valid environment

`steven@sligo:~/Sites/pcaaca$ lando pull
? Pull code from? none
? Pull database from? live
? Pull files from? none
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as steven@cknweb.it
Verifying that you have accesss to pcaaca...
 ------------------ ------------------------------------------------------------------------------------- 
  ID                 d1b4e7d0-cb81-442c-b15d-67469080e6f6                                                 
  Name               pcaaca                                                                               
  Label              PCA/ACA                                                                              
  Created            2017-05-15 20:47:10                                                                  
  Framework          drupal                                                                               
  Region             United States                                                                        
  Organization                                                                                            
  Plan               Performance Medium                                                                   
  Max Multidevs      10                                                                                   
  Upstream           21e1fada-199c-492b-97bd-0b36b53a9da0: git://github.com/pantheon-systems/drops-7.git  
  Holder Type        user                                                                                 
  Holder ID          5b0aaff9-5252-46dd-8fc5-10ec9e7659b8                                                 
  Owner              5b0aaff9-5252-46dd-8fc5-10ec9e7659b8                                                 
  Is Frozen?         false                                                                                
  Date Last Frozen   1970-01-01 00:00:00                                                                  
 ------------------ ------------------------------------------------------------------------------------- 
Certificate will not expire
Cert is good!
Validating whether 44-remove-sched is a valid environment and that you have access to it
steven@sligo:~/Sites/pcaaca$ 
`

**Comment by pirog** [comment] 2020-05-03 23:18
@sdubois i think this is a duplicate of #2153 which is fixed in the latest edge release

**Closed by pirog** 2020-05-03 23:18 UTC
Labels: bug

**Comment by sdubois** [comment] 2020-05-03 23:24
sounds like it! didn't noticed that when i looked through the bugs
