### ISSUE TITLE
`lando rebuild -s` leaves some services stopped

### ISSUE THREAD

**Issue by tpluscode** [lando/lando#3341] opened 2022-03-02 09:53 UTC
Using lando 3.6.0

Start [this project](https://github.com/zazuko/cube-creator/blob/2c926c7dfb5fd56713bf61361e670790bb3da901/.lando.yml)

After `lando restart -s store`, most services will not go up again:

https://user-images.githubusercontent.com/588128/156338690-35a1cb4f-10b4-4589-8a41-a8742d9989fc.mp4

**Comment by reynoldsalec** [comment] 2022-03-02 19:49
Hmm @tpluscode, I'm not sure how I'm going to be able to recreate that. I strongly suspect based on some of the other issues we've been discussing that this might be related to something about the construction of your custom `store` service. Does `lando logs` say anything interesting? Could try targeting the `store` service individually as well...that might be more helpful (`lando logs -s store`), especially if you tail it (`lando logs -s store -f`)

If you can share me your project I can recreate.

**Comment by rabauss** [comment] 2022-03-03 15:30
I realized that problem in different `lamp` projects, too!

**Comment by tpluscode** [comment] 2022-03-03 15:48
> If you can share me your project I can recreate.

Link in the issue description. @reynoldsalec 

Pointing at a commit but I suppose this will be reproducible in general

**Comment by reynoldsalec** [comment] 2022-03-03 17:25
@tpluscode interestingly enough, running https://github.com/zazuko/cube-creator from the master branch I don't see this error; the all services are back up and running.

```
git pull https://github.com/zazuko/cube-creator
lando start
lando rebuild -s store 
```

Interestingly enough I am able to reproduce an issue with the stock `lamp` recipe that may coincide with @rabauss's issue; when I run a `lando rebuild -s appserver`, the database service fails to restart. If I do a `lando rebuild -s database` all services start up fine. I suspect this could be an M1 compatibility issue, since I know people have had stability issues with the `bitnami:mariadb` image...certainly is an independent issue from what you're encountering with `cube-creator`.

Happy to look at some log output if you have something that seems like a likely culprit!

**Comment by reynoldsalec** [comment] 2022-03-09 19:37
Looks like we may not have more grist for the mill (IE replication pathways) for the issue here, so going to close this out, but feel free to reopen if you get some more data @tpluscode!

**Closed by reynoldsalec** 2022-03-09 19:37 UTC
Labels: bug, can not replicate
