### ISSUE TITLE
Startup error "services.proxy.ports contains an invalid type"

### ISSUE THREAD

**Issue by north-krimsly-hp** [lando/lando#1857] opened 2019-11-11 21:28 UTC
I am running lando v3.0.0-rc.22 on Mac OS X Catalina 10.15.1. Every time I execute a "lando start" after shutting down my Mac then restarting, I get the following error. 

```lando start
Let's get this party started! Starting app..
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
ERROR: The Compose file '/Users/north/.lando/proxy/proxy-1.yml' is invalid because:
services.proxy.ports contains an invalid type, it should be a number, or an object
warn: Something is wrong with the proxy! Error
warn: Trying to take corrective action...
error: Error: Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
    at container.(anonymous function).catch.err (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at containerOpt (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at Landerode.remove (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at exports.destroy.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
From previous event:
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

Then I have to blow away the Lando container and start over with a rebuild, as follows:

```lando stop
rm -rf ~/.lando 
docker ps -a 
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)
lando start
```

After that it runs fine until I shut down my Mac again. Once I shut down my Mac and again restart, Lando fails in the same way and I have to rebuild the Lando container again. This happens every time I shut down then restart my Mac. It is time-consuming to do a rebuild every time I reboot so I am hoping there is a solution for this issue.

Here is my .lando.yml. I am using the Lando 'drupal7' recipe with a few changes:

```name: hpcorp
recipe: drupal7
config:
  webroot: .
  php: 7.2
  config: 'php:.lando.php.ini'
services:
  appserver:
    type: 'php:7.2'
    build_as_root:
      - apt-get update -y
      - apt-get install -y libmcrypt-dev
      - pecl install mcrypt-1.0.1
      - docker-php-ext-enable mcrypt
```

Please advise and thanks.

**Comment by north-krimsly-hp** [comment] 2019-12-12 16:31
Is there someone who can look at this bug please, rather than marking as stale or closing it? It continues to be a problem when using Lando v3.0.0-rc.22 on Mac OS X Catalina 10.15.1.
Thanks.

**Comment by north-krimsly-hp** [comment] 2020-01-13 19:03
Still a problem. Does anyone have time to look at this?
Thanks.

**Comment by north-krimsly-hp** [comment] 2020-02-19 21:23
This is still a problem. Can someone please look at it?
Thanks.

**Comment by pirog** [comment] 2020-03-31 13:07
@north-krimsly-hp what are the contents of the invalid file? `/Users/north/.lando/proxy/proxy-1.yml`?

Best guess here is you have invalid `yaml` somewhere in one of your Landofiles.

**Comment by north-krimsly-hp** [comment] 2020-04-01 19:48
Hi Pirog, please see my Lando .yml file at the beginning of this issue report above. Unfortunately, I don't think it is a problem with the Lando .yml file since the same exact file works sometimes, but not others when I start Lando up. My .lando.yml file is the only one I created, all other .yml files would have been provided by the Lando recipe.

**Comment by pirog** [comment] 2020-04-01 19:54
I'm not asking for the contents of the Landofile. I'm asking for the contents of the generated file at `/Users/north/.lando/proxy/proxy-1.yml`, it probably going to be pretty easy to spot whats wrong in that file.

**Comment by jan-di** [comment] 2020-04-09 08:37
Hello, same issue here. The proxy-1.yml has this content:

```yml
services:
  proxy:
    ports:
      - ':80'
      - '443:443'
      - '58087:8080'
version: '3.6'
```

I think the issue is on the line with port :80. Even if i correct it manually, on starting lando the change is getting reversed.
v3.0.0.-rrc.1

**Comment by north-krimsly-hp** [comment] 2020-04-09 16:32
Hi jan-di, yes thank you for doing a better job describing the problem than I did. The problem is that even if I fix the proxy-1.yml file manually, it will get regenerated (and broken again) the next time I start up Lando. This happens nearly every time (but not every time) I start Lando. I am hoping the Lando team will implement a long-term fix. I am on a Mac and you are on Windows, so it does not look like a system-specific problem.

**Comment by pirog** [comment] 2020-04-11 19:28
Thanks @jan-di, that is helpful. 

Probably not a huge surprise that i cant replicate this. I'm guessing this is an edge case otherwise we'd be getting more feedback given how essential the proxy is to Lando. 

That said, let me try to step through the code and see if there are any situations that can cause the external http port assignment to set to nothing. The immediately obvious thing that comes to mind is if Lando cannot find an open port, which could happen if you've got a bunch of ports locked down, then you might end up here. In those circumstances it would be good for Lando to report to the user that the proxy is not usable on any of the ports.

**Comment by pirog** [comment] 2020-04-16 12:09
Alright, if Lando cannot set up the proxy correctly it will skip it and warn the user this means the app should still boot up correctly but with only localhost addresses and the user will be given advice on how to remediate.

**Comment by pirog** [comment] 2020-04-16 13:06
This will be in the next release

**Closed by pirog** 2020-04-16 13:06 UTC
Labels: bug
