### ISSUE TITLE
[v3.0.0-rrc.1] Output of URLs is broken on Windows

### ISSUE THREAD

**Issue by rabauss** [lando/lando#2063] opened 2020-03-20 13:27 UTC
Unfortunately the output of the container urls is broken on windows since v3.0.0-aft.1.
The labels of the services are missing and the start of the urls is missing.
![image](https://user-images.githubusercontent.com/14016098/77167235-ea416300-6ab5-11ea-96e8-96b1848689e4.png)

I even have projects with more broken output - see:
![image](https://user-images.githubusercontent.com/14016098/77167415-52904480-6ab6-11ea-807e-3cccab955f94.png)

please ignore the red marks - this is just for data protection ;-)
tested with powershell, cmd and conemu and two different windows systems!

any suggestions why this is broken?

**Comment by RichardDavies** [comment] 2020-03-20 18:08
I can confirm the same on two different Windows PCs:
![image](https://user-images.githubusercontent.com/13959/77193183-0f74a800-6a9b-11ea-9dbb-0347953eb1b9.png)

**Comment by pirog** [comment] 2020-03-23 14:43
weird! no f idea, either of you investigate this at all or have any clue why this would happen?

**Comment by rabauss** [comment] 2020-03-23 16:07
I really tested on friday with the dev version an added a few debug strings to the table - here: https://github.com/lando/lando/blob/5bd22692737d3b77ffe2e997145abfff22a5f068/lib/table.js#L55

But they weren't in the output, so I have no idea for now why this happens - maybe I can research a bit more in the next days

**Comment by pirog** [comment] 2020-03-23 16:09
@rabauss have you checked out the issue queue for the CLI TABLE module we are using? that seems like the likely place where this is coming from

**Comment by rabauss** [comment] 2020-03-23 16:11
Yes, I only checked this briefly, but I also suspect that the cause is there!

**Comment by rabauss** [comment] 2020-03-23 21:03
I enabled the borders and got the following output - maybe it will help.
![image](https://user-images.githubusercontent.com/14016098/77361594-dadd4680-6d4f-11ea-94c0-b0f0943ee9fb.png)

But I guess it's really the cli-table3. Although I don't understand why the service titles are missing.
It might be related to https://github.com/cli-table/cli-table3/issues/147 ?

**Comment by rabauss** [comment] 2020-03-24 00:27
Okay I tested some scenarios - and finally with this result on `rrc.1` with windows:
![image](https://user-images.githubusercontent.com/14016098/77375540-1981f980-6d6e-11ea-8575-ee27c899610c.png)

I replaced `os.EOL` to `'\n'` in the `table.js`
https://github.com/lando/lando/blob/55efb0e02ec5282251728a996e93e410fdea4e7c/lib/table.js#L32

But I'm not sure, if this is really the solution for all OS...

**Comment by pirog** [comment] 2020-03-24 13:03
`\n` is the POSIX line ending eg what we are already using for mac/Linux

So if whatever reason that is what we need on Windows then that _should_ be cross platform. I'm a little surprised Windows likes `\n` instead of `\r\n` but works for me!

Thanks for investigating this @rabauss, thats super helpful!

**Comment by pirog** [comment] 2020-03-25 02:53
ok this should be fixed in the next release!

**Closed by pirog** 2020-03-25 02:53 UTC
Labels: bug
