### ISSUE TITLE
lando db-import can not find file

### ISSUE THREAD

**Issue by kinglouie** [lando/lando#2170] opened 2020-04-20 07:51 UTC
*v3.0.0-rrc.4 on arch linux*

*lando.yml:*

```yml
name: shopware
recipe: lamp
config:
  webroot: ./public
```

*Steps to cause this bug:*

```bash
$ lando start
$ lando db-export test.sql
Preparing to export /app/test.sql from database 'lamp' on service 'database' as user root...
Success /app/test.sql.gz was created!
$ lando db-import test.sql.gz
File /app/test.sql.gz not found!
```

After exporting the database I checked that the file `test.sql.gz` is created and I also checked with `lando ssh` that the file is there as well. 
Is this some kind of permission issue between the app and database container?

Also check this https://github.com/lando/lando/issues/1815#issuecomment-612527721 with a user facing the same issue. The temporary solution mentioned there also worked for me.

**Comment by pirog** [comment] 2020-04-20 12:39
I cannot replicate this

**Comment by kinglouie** [comment] 2020-04-20 12:58
I made a few more tests, it is a permission issue.
When I do `lando ssh -s database` and then isue `ls` I get a permission denied error.
When I do `lando ssh -s appserver` and then isue `ls -la` I get the app directory with `user` and `group` set to `www-data`.
When I do `lando ssh -s appserver --user root` and then isue `ls -la` I get the app directory with `user` and `group` set to `1000` which is my users id.

Is there a reason `lando db-export` is run as root while `db-import` is not?

**Comment by boabjohn** [comment] 2020-04-24 23:25
Newbie here, sorry if this is a distraction, but:
- Win10Pro/64 running the very freshest default install of lando -rrc.3
- Lando init of a clean Pantheon site
- Lando fails every time with a connection problem. Here's Lando:
```
error:
Client:  Debug Mode: false
Server:
ERROR: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
```
And here's the database log:
```
database_1         | 2020-04-24 12:42:17 139630097030976 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.44-MariaDB) s
database_1         | 2020-04-24 12:42:17 139630097030976 [ERROR] Could not open mysql.plugin table. Some plugins may be not be loaded
```

**Comment by boabjohn** [comment] 2020-04-25 11:19
I have rolled back to rrc-1 and am functional once more, but I had to manually uninstall Docker desktop and then reinstall Lando,

**Comment by pirog** [comment] 2020-05-05 00:12
@kinglouie that would certainly explain the behavior. 

Dove a bit deeper and tried this out on ubuntu with the latest rrc.8 and still could not replicate. If i `lando ssh -s database` and `ls` it shows the expected with the files set to my UID

**Comment by kinglouie** [comment] 2020-05-05 08:14
@pirog I just checked on the latest edge 3.0.0 release and the issue is still there. 
I just noticed that when I run `lando ssh -s database` I connect as user `www-data`, is this intended? This user has uid of 33 but the relevant directories are set to uid of 1000 which is my host user. That would explain why these permission issues arise.

**Comment by pirog** [comment] 2020-05-08 03:48
@kinglouie i wouldnt expect it to be solved in `3.0.0` considering we are still trying to figure out what the actual problem is in this thread. 

This would be the expected behavior although its sadly not what we'd prefer. 

The mysql image we use under the hood cannot boot up as `root` which we need to do the correct `host:container` permissions mapping. I suspect this is why `lando db-export` runs as `root` so we can handle any needed permission handling on the script level. 
https://github.com/lando/lando/blob/master/plugins/lando-services/scripts/sql-export.sh#L91

Generally this perm mismatch is fine since Linux users arent generally shelling into their database services to modify their codebase and the db-export script is modifying the only file that is likely to suffer from this. 

That said, clearly there is some other permission issue here, its strange that i cant replicate on Linux. Changing the `db-import` script to also run as `root` is probably the easiest way to just resolve this.

**Comment by jefftrnr** [comment] 2020-05-08 22:13
It does not seem to find the file unless it's in the project root

try moving the file.sql to the lando project root dir then
`lando db-import file.sql`

**Comment by kinglouie** [comment] 2020-05-09 07:29
@jefftrnr this is not about the file location but about the permissions. The .sql.gz is in the projects root dir. As I already found out the issue stems from lando starting the database container with UID 33 (www-data) but settings the file permissions to UID 1000 which is my host computers user.

I see 3 possible ways to resolve this issue:

1. Start the database container with UID 33 and also set file ownership of the files in projectroot to UID 33. (This is the way the permissions are set on the appserver container)

2. Start the database container with UID 1000 (or whatever else the hosts computers UID is) and leave the projectroot permissions as is.

3. Run db-import.sh as root.

For me 1. would be the preferred way since the appserver container uses the same UID.
I'm wondering why for me the is a permission mismatch while others don't have this issue. I would investigate this myself but I could not find the corresponding code in the codebase where the containers are booted up.

**Comment by pirog** [comment] 2020-05-10 12:33
@kinglouie the entire point of this comment https://github.com/lando/lando/issues/2170#issuecomment-625614683 is that 1. and 2. are not possible

**Comment by pirog** [comment] 2020-05-12 11:54
Alright @kinglouie since we cant replicate this we cant 100% say that https://github.com/lando/lando/commit/b44f157378fbbf943c4c08ba0454a8e7fb2fb38f will resolve your issue but we've switched `db-import` to run as `root` and this will be in the next release

If for whatever reason that does _not_ resolve this then please reopen

**Closed by pirog** 2020-05-12 11:54 UTC
Labels: bug, can not replicate

**Comment by vadiminsk** [comment] 2021-11-16 13:24
> It does not seem to find the file unless it's in the project root
> 
> try moving the file.sql to the lando project root dir then `lando db-import file.sql`

works for me!

**Comment by tahireu** [comment] 2021-12-11 15:38
In my case problem was in db file permissions and ownership. I've experienced this issue on the PhpStorm terminal. Using the regular, MacBook Terminal instead solved it for me.

**Comment by msypes-icf** [comment] 2022-01-05 16:51
I've got this same problem suddenly; in the past, it's worked just fine for me. 
File is in the root directory of the project. `lando db-import file.sql` responds with `File app/file.sql not found!`
Lando version 3.4.2
file.sql permissions are 666

**Comment by rjbain** [comment] 2022-09-12 21:18
`lando rebuild` worked for me.

**Comment by djassie** [comment] 2024-01-05 06:04
`lando rebuild -y` works

**Comment by ankitamin** [comment] 2024-11-19 06:50
works for me !
