### ISSUE TITLE
DOCKER COMPOSE version warning

### ISSUE THREAD

**Issue by kburakozdemir** [lando/lando#3050] opened 2021-06-17 09:19 UTC
I use 

```txt
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

Lando version: v3.1.4
docker-compose version: docker-compose version 1.29.0, build 07737305
docker version: Docker version 20.10.7, build f0df350
```

When I run `lando start` I get a warning about the docker-compose version:

```txt
 ■ Using an unsupported version of DOCKER COMPOSE
   You have version 1.29.1 but Lando wants something in the 1.23.0 - 1.29.0 range.
   If you have purposefully installed an unsupported version and know what you are doing
   you can probably ignore this warning. If not we recommend you use a supported version
   as this ensures we can provide the best support and stability.
   https://docs.docker.com/compose/install/#install-compose-on-linux-systems
```

I also tried the following

- remove docker-compose and installed docker-compose version 1.28.6 and the warning is the same.
- `lando rebuild` and then also destroy everything via `lando destroy`.
- then I also removed lando (purging all configuration), delete all containers, images, networks, volumes, and installed a clean, fresh version.

The result is the same. You can see the screenshot after the clean, fresh installation. 

Note: I use Drupal 8, and the app works fine on my local dev, although the warning exists.

![image](https://user-images.githubusercontent.com/1656836/122368862-5edba980-cf66-11eb-87fe-fcd8b84b4d22.png)

**Comment by Adrianm6254** [comment] 2021-06-17 17:22
I am having the same issue except my docker-compose is 1.29.0

![Lando-Docker-Compose-Issue](https://user-images.githubusercontent.com/13153806/122444942-aa8e5300-cf66-11eb-8fbf-899617dfa3ea.png)

**Comment by sebastienserre** [comment] 2021-06-18 05:33
Hello,

Same error here on Ubuntu 20.04 with a WordPress recipe.
When checking the link given, https://docs.docker.com/compose/install/#install-compose-on-linux-systems, latest Compose version is 1.29.2

**Comment by marcandreappel** [comment] 2021-06-21 15:10
Same here on Pop_OS 20.10 with any recipe.

**Comment by felix-berlin** [comment] 2021-06-21 15:24
Same here > Win 10 > WSL Ubuntu 20 LTS.

**Comment by JorisVanEijden** [comment] 2021-06-22 06:16
Duplicate of #3010

**Comment by mrspiderbrain** [comment] 2021-06-25 06:50
I have the same issue. It looks like 3.1.4 was released with an incompatible set of dependencies...?

**Comment by dustinleblanc** [comment] 2021-07-06 15:50
Closing as dupe of #3010

**Closed by dustinleblanc** 2021-07-06 15:50 UTC
Labels: bug, duplicate
