### ISSUE TITLE
curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by RichardDavies** [lando/lando#1071] opened 2018-06-28 23:34 UTC
Bug Report
==========

**Tell us about your setup**

v3.0.0-beta.47 on Windows 10 Professional

**Tell us about your `.lando.yml`**

```yml
name: portlandor
recipe: pantheon
config:
  framework: drupal8
  site: portlandor
  id: 5c6715db-abac-4633-ada8-1c9efe354629
framework: drupal8
xdebug: true
services:
  appserver:
    xdebug: true
    config:
      conf: xdebug.ini
drush: composer
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
```

**Tell us about your `pantheon.yml`**

```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1

web_docroot: true

php_version: 7.1

# Add a comment to trigger a deploy on Pantheon
workflows:
  clear_cache:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  clone_database:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  create_cloud_development_environment:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  deploy:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
  sync_code:
    after:
      - type: webphp
        description: Post deployment notification to Slack
        script: private/scripts/slack_deploy_notification.php
```

**Tell us about the command you were running**

```bash
git clone -c core.symlinks=true git@github.com:eGovPDX/portlandor.git
git config core.autocrlf false
lando start
```

**Tell us about the error you got**

```bash
lando start -- -vvvv
.
.
.
verbose: Running spawn C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe with args ["--project-name","port
landor","--file","C:\\Users\\csrichardd\\.lando\\compose\\portlandor\\portlandor-2.yml","--file","C:\\Users\\csrichardd\
\.lando\\proxy\\portlandor-proxy-3.yml","exec","--user","www-data","appserver","/bin/sh","-c","cd /tmp && curl https://g
ithub.com/drush-ops/drush/releases/download/8.1.16/drush.phar -L -o drush.phar && chmod +x drush.phar && ./drush.phar co
re-status && mv drush.phar /usr/local/bin/drush"]
debug: In mode attach with detached false
debug: With env ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal, ALLUSERSPROFILE=C:\ProgramData, APPDATA=C:\Users
\csrichardd\AppData\Roaming, ChocolateyInstall=C:\ProgramData\chocolatey, ChocolateyLastPathUpdate=Wed Jan 31 15:13:00 2
018...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   2715      0 --:--:-- --:--:-- --:--:--  2722
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
verbose: Spawn exited with code: 60
silly: Spawn finished with
error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
verbose: Error {"code":60}
```

**Tell us generally about your bug**

I tried to create a Pantheon site but keep getting this curl error when it's attempting to download drush from github: "curl: (60) SSL certificate problem: unable to get local issuer certificate"

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

Start command prompt as an administrator and run the following commands:

```bash
git clone -c core.symlinks=true git@github.com:eGovPDX/portlandor.git
cd portlandor
git config core.autocrlf false
lando start
```

You can also reproduce it this way if Lando is already running by mimicking the commands Lando executes :

```bash
lando ssh
cd /tmp
curl https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar -L -o drush.phar
```

**Tell us more**

As the curl error message states, you can bypass this error by disabling SSL certificate validation by using curl with the -k option.

Does this bug prevent you from using lando?

Yes

**Comment by pirog** [comment] 2018-06-29 06:54
@RichardDavies this is a known issue thats been discussed on the slack channel a few times but (surprisingly) looks like there isnt a github issue for this until now. 

To provide some more detail for people who end up getting this. the tl;dr is there is currently a race condition that exists between regenerating your container certs so that they all trust the local Lando CA and build steps eg drush. The easiest workaround for now is to just continue running `lando start/restart` until your build process completes without an error.

We are gearing up to release the RC1 which will revamp our build step logic to better handle things like this. The summary there is we will be doing cert regeneration in the background after all other build steps are run so that it doesnt block the container from starting and doesnt interfere with buid logic. 

Look for this to be fixed in RC1

**Comment by RichardDavies** [comment] 2018-06-29 15:18
Thanks for the info @pirog ! That helps to explain why it sometimes works and then other times I get this error. However, for a race condition, there seems to be a pretty consistent winner (and loser). I've restarted at least 10 times and haven't gotten it to work yet... any other tips to improve my odds?

**Comment by pirog** [comment] 2018-06-29 15:23
Hard for me to say since i pretty consistently seem to have a winner. I've only been able to replicate this on a slower Windoze 10 box and it *usually* takes 3-4 restarts for me but it can definitely be a lot slower if the machine is under heavy resource load.

**Comment by RichardDavies** [comment] 2018-06-29 18:45
Hmm. I've attempted it another 5 or so times and still no luck. My machine has a quad-core 3.2 GHz CPU and 16 GB of RAM (w/ 4 GB dedicated to Docker). It's probably about two years old but I wouldn't necessarily classify it as a "slow" PC.

In the meantime, it looks like I can workaround it by manually executing the commands after Lando  finishes starting:

```bash
lando ssh
cd /tmp
curl -k https://github.com/drush-ops/drush/releases/download/8.1.16/drush.phar -L -o drush.phar
chmod +x drush.phar
./drush.phar core-status
mv drush.phar /usr/local/bin/drush
```

**Comment by RichardDavies** [comment] 2018-07-10 15:41
Although as mentioned in my previous comment, I found a workaround for the SSL error when starting Lando, I also get similar SSL errors when running lando composer install to which I have no known workaround.

I've restarted and rebuilt my Lando containers probably 20-30 times while troubleshooting this and have yet to get a clean working build. I find it hard to believe that this error is truly a result of a random race condition...

Any idea when the RC1 release is to be expected? This issue basically renders Lando inoperable for me.

**Comment by pirog** [comment] 2018-07-10 15:47
i feel pretty confident saying it is a race condition. That said "rebuilding" an app is going to start the race over again, "restarting" and app is what you will want to do. 

we are currently looking to roll out the rc1 late July or early August but it all depends on how our test coverage pans out once we get things in order. We aren't going to roll out an RC until at least all our current examples can run.

**Comment by RichardDavies** [comment] 2018-07-10 15:54
Thanks for the info. I feel like this issue/error started with one of the recent releases as I was successfully using Lando for some time before I began experiencing this error. Would you happen to have any idea which release introduced this race condition? I might need to consider downgrading until the RC is released as "restarting" isn't fixing it for me.

**Comment by zuernBernhard** [comment] 2018-08-03 12:28
Same problem here with latest -beta47 on macbook

**Comment by zuernBernhard** [comment] 2018-08-03 12:29
The Workaround from RichardDavies helps me.

**Comment by com2** [comment] 2018-08-07 09:32
RichardDavies work around only is good for the indicated version. For Drupal 8.5.x you have to install drush 9.3.0 and I could not find a drush.phar URL for that version.

**Comment by ralkeon** [comment] 2018-08-28 13:40
Have someone found another workaround, in addition to the rebuilding one?

**Comment by RichardDavies** [comment] 2018-08-28 18:48
@ralkeon You might try downgrading to version beta 44. Since downgrading I seem to have avoided this issue.

**Comment by ralkeon** [comment] 2018-08-29 07:49
Thank you so much!

**Closed** 2018-09-03 04:05 UTC

**Comment by dgpalmer** [comment] 2018-11-02 18:07
I am getting this error when I am attempting to make a POST request with Guzzle. Any advice or suggestions? Not getting this error with the same code in Drupalvm but I'd prefer to use Lando.

Thanks!

**Comment by pirog** [comment] 2018-11-03 02:53
@dgpalmer what version of lando are you using and what OS?

**Comment by edurenye** [comment] 2019-03-26 09:51
I have the same case than @dgpalmer, I'm using RC1 and Ubuntu 18.10. 
The problem is documented here:
https://www.drupal.org/node/2481341

**Comment by brooke-heaton** [comment] 2019-08-03 03:19
Happening to me on Pop OS 19, System76 machine.
