### ISSUE TITLE
Current master has all sql commands failing; db-import, db-export, pull, push; lando pull db fails for pantheon recipe

### ISSUE THREAD

**Issue by msschwartz** [lando/lando#711] opened 2018-02-15 20:24 UTC
In our site the wordpress files are not inside the root directory (i.e. they exist in `/web`). When running `lando pull --database=dev --files=none --code=none` the command will fail at the end when replacing dev URLs with local URLs. 

*Error message*
```
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

*System*
v3.0.0-beta.36 on macOS Sierra

*.lando.yml*
```
name: super-awesome-site
recipe: pantheon
config:
  framework: wordpress
  site: super-awesome-site
  id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

*pantheon.yml*
```
api_version: 1
php_version: 5.6
web_docroot: true
```

**Comment by serundeputy** [comment] 2018-03-10 14:42
Dumping research from the current PR discussion:

```bash
geoff@yep 711-lpr (master) exit code: [0] $ lando.dev pull --code none --database dev --files none
/bin/sh: 1: ./pull.sh: not found
```

When I ssh into the `appserver` this is what the permissions on the `*.sh` scripts inside `/helpers` look like:

```bash
geoff@yep 711-lpr (master) exit code: [0] $ lando.dev ssh
www-data@ed0be986c02e:/app$ cd /helpers/
www-data@ed0be986c02e:/helpers$ ls
mysql-export.sh  mysql-import.sh  pantheon.sh  pull.sh	push.sh  switch.sh
www-data@ed0be986c02e:/helpers$ ls -alh
ls: cannot access 'pantheon.sh': No such file or directory
ls: cannot access 'pull.sh': No such file or directory
ls: cannot access 'mysql-export.sh': No such file or directory
ls: cannot access 'switch.sh': No such file or directory
ls: cannot access 'push.sh': No such file or directory
ls: cannot access 'mysql-import.sh': No such file or directory
total 8.0K
drwxr-xr-x 2 root root 4.0K Mar  4 16:57 .
drwxr-xr-x 1 root root 4.0K Mar  4 16:57 ..
-????????? ? ?    ?       ?            ? mysql-export.sh
-????????? ? ?    ?       ?            ? mysql-import.sh
-????????? ? ?    ?       ?            ? pantheon.sh
-????????? ? ?    ?       ?            ? pull.sh
-????????? ? ?    ?       ?            ? push.sh
-????????? ? ?    ?       ?            ? switch.sh
```

I'm guessing when we mount these helpers in the container we are not setting the permissions correctly and then we can not use them.

I checked out `beta.35` and here is what the permissions look like on that version of lando:

```bash
www-data@5048f26b1590:/app$ ls -alh /helpers/
total 40K
drwxr-xr-x 2 root     root     4.0K Mar  4 17:25 .
drwxr-xr-x 1 root     root     4.0K Mar  4 17:25 ..
-rwxr-xr-x 1 www-data www-data 2.4K Mar  4 17:25 mysql-export.sh
-rwxr-xr-x 1 www-data www-data 3.8K Mar  4 17:25 mysql-import.sh
-rwxr-xr-x 1 www-data www-data 1.6K Mar  4 17:25 pantheon.sh
-rwxr-xr-x 1 www-data www-data 5.9K Mar  4 17:25 pull.sh
-rwxr-xr-x 1 www-data www-data 4.5K Mar  4 17:25 push.sh
-rwxr-xr-x 1 www-data www-data 1.7K Mar  4 17:25 switch.sh
```

**Comment by pirog** [comment] 2018-03-15 02:15
@serundeputy i can def reproduce this although it happened to me on the first try. I'll chalk that up to beginners luck ;). I think your hunch about `fs-extra` is probably spot on @serundeputy

**Comment by pirog** [comment] 2018-03-15 02:29
So first thing noticed is we lost the `+x` on `SOME` of the files in the repo itself. weird.

**Comment by pirog** [comment] 2018-03-15 02:42
Second thing is this seems to be a docker issue although im not exactly sure when it happened

**Comment by pirog** [comment] 2018-03-15 04:03
ok circling back around on this. @serundeputy is def right about `fs-extra` and here are the steps to verify. this assumes you start from the latest master with latest npm deps installed.

cc: @dustinleblanc 

```bash
# Go back to pre-fs-extra-upgrade
git checkout da401020f7ec0f14168115eeca3c123f38380e49
rm -rf node_modules
yarn
cd examples/lemp2
lando.dev start
lando.dev ssh -c "ls -lsa / | grep user-perms"
# 4 -rwxr-xr-x   1 www-data www-data 2526 Mar 15 03:56 user-perms.sh

# Now break it
cd ../..
yarn add fs-extra@4.0.3
cd examples/lemp2
lando.dev destroy -y
lando.dev start
lando.dev ssh -c "ls -lsa / | grep user-perms"
ls: cannot access /user-perms.sh: No such file or directory
? -?????????   ? ?        ?           ?            ? user-perms.sh
```

Looks like the thing missing between the two is the preservation of the osx `@` extended attributes when we copy our config from source to `.lando` which im guessing is happening here:
https://github.com/lando/lando/blob/master/plugins/lando-engine/lib/utils.js#L75

**Comment by pirog** [comment] 2018-03-15 04:38
This also seems to be a showstopper in the packaged CLI binary. I'm going to explore if a revert to 
a previous version is feasible.

**Comment by pirog** [comment] 2018-03-15 05:36
@serundeputy @dustinleblanc alright gents. reverting to the older fs-extra seems to be our fastest pathway forward here so ive done that. ive also verified the older version works in OTHER PROJECTS so lets just close this and maybe return in the future

**Closed by pirog** 2018-03-15 05:36 UTC
Labels: bug, pantheon
